### ISSUE TITLE
Example use cases

### ISSUE THREAD

**Issue by markrendle** [Microsoft/bond#1]
Could you add some concrete example use cases for this to the README or the docs? It would be helpful to know what problems it is being used to solve.

**Comment by xplicit** [comment]
@markrendle Are you looking this https://microsoft.github.io/bond/manual/bond_cs.html ?

**Comment by markrendle** [comment]
Yes. It's got plenty of how-to-use, but not where or why to use it.

**Comment by sapek** [comment]
Does this http://microsoft.github.io/bond/why_bond.html help?
Adam Sapek sapek authored 5 minutes ago
