### ISSUE TITLE
Bond python support

### ISSUE THREAD

**Issue by clrusby** [microsoft/bond#1004]
Has any thought been given to creating a python-native bond interface, or (maybe simpler) using [pybind11](https://github.com/pybind/pybind11) instead of boost::python?

A python-native solution would probably only be viable for prototyping as I imagine it will be rather slow to serialize/deserialize the data.

However, a pybind11-based solution has the huge advantage of being header only, and hence trivial to support multiple python variants.  Using boost::python means a full rebuild of the entire boost framework for each python variant one wishes to support, and this is not something to be undertaken lightly.

Thanks

**Comment by chwarr** [comment]
We've not looked into pybind11 nor an all-Python implementation.

An all-Python implementation would be welcome. We don't have any current plans to write one at Microsoft. If you're in a position to contribute this, please let us know here.

Similarly, pybind11 support would also be welcome, if you're willing to contribute it. For the foreseeable future, it would need to be able to co-exist with the boost::python implementation such that existing uses of the boost::python implementation are not affected.

**Comment by chwarr** [comment]
I'm going to close this issue for now since I haven't seen any activity in a couple of weeks. If there's something more here, please post another comment. Thanks.
