### ISSUE TITLE
Bond failed to build due to CMake Error at stack_build.cmake with MSVC on windows

### ISSUE THREAD

**Issue by spacelg** [microsoft/bond#1006]
Environment:
Windows Server 2016 + VS2017 + bond master branch latest srouce code.

Bond failed to build due to CMake Error at stack_build.cmake with MSVC on windows. It can be first reproduced on master revision 7038e5b . Could you help have a look about this issue? Thanks in advance!

1. git clone --recursive https://github.com/Microsoft/bond.git D:\bond\src
2. Open a VS 2017 x64 command prompt as admin and browse to D:\bond\src
3. cd compiler
4. powershell.exe -NoProfile -ExecutionPolicy Bypass ..\..\tool\Setup.ps1
5. cd ../..
5. mkdir build_x64 && pushd build_x64
6. cmake -G "Visual Studio 15 2017 Win64" -DCMAKE_SYSTEM_VERSION=10.0.17134.0 ..\src
7. msbuild bond.sln /p:Configuration=Release;Platform=x64 /t:Rebuild

[log_x64_build.log](https://github.com/microsoft/bond/files/3723594/log_x64_build.log)

Actual result:
...
CustomBuild:
  Generating build/gbc/gbc.exe
  CMake Error at stack_build.cmake:21 (message):
    Version 1.5.1, Git revision 600c1f01435a10d127938709556c1682ecfd694e x86_64
    hpack-0.17.1
  
    2019-10-13 17:30:11.038663: [debug] Checking for project config at:
    D:\Bond\src\compiler\stack.yaml
  
    @(Stack\Config.hs:974:9)
  
    2019-10-13 17:30:11.038663: [debug] Loading project config file stack.yaml
  
    @(Stack\Config.hs:999:13)
  
    2019-10-13 17:30:11.101162: [debug] Trying to decode
    C:\sr\build-plan-cache\x86_64-windows\lts-14.4.cache
  
    @(Data\Store\VersionTagged.hs:72:5)
  
    2019-10-13 17:30:11.101162: [debug] Exception ignored when attempting to
    load C:\sr\build-plan-cache\x86_64-windows\lts-14.4.cache:
    C:\sr\build-plan-cache\x86_64-windows\lts-14.4.cache: openBinaryFile: does
    not exist (No such file or directory)
  
    @(Data\Store\VersionTagged.hs:90:9)
  
    2019-10-13 17:30:11.101162: [debug] Failure decoding
    C:\sr\build-plan-cache\x86_64-windows\lts-14.4.cache
  
    @(Data\Store\VersionTagged.hs:79:13)
  
    2019-10-13 17:30:11.101162: [debug] Decoding build plan from:
    C:\sr\build-plan\lts-14.4.yaml
  
    @(Stack\BuildPlan.hs:515:5)
  
    2019-10-13 17:30:11.116784: [debug] Decoding build plan from file failed:
    InvalidYaml (Just (YamlException "Yaml file not found:
    C:\\sr\\build-plan\\lts-14.4.yaml"))
  
    @(Stack\BuildPlan.hs:520:13)
  
    2019-10-13 17:30:11.116784: [info] Downloading lts-14.4 build plan ...
  
    @(Stack\BuildPlan.hs:524:13)
  
    2019-10-13 17:30:11.116784: [debug] Downloading build plan from:
    https://raw.githubusercontent.com/fpco/lts-haskell/master//lts-14.4.yaml
  
    @(Stack\BuildPlan.hs:525:13)
  
    2019-10-13 17:30:11.116784: [debug] Downloading
    /fpco/lts-haskell/master//lts-14.4.yaml
  
    @(Network\HTTP\Download.hs:78:5)
  
    2019-10-13 17:30:11.616785: [info] Downloaded lts-14.4 build plan.
  
    @(Stack\BuildPlan.hs:527:13)
  
    AesonException "Error in $['system-info']: key \"os\" not present"
  
C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(209,5): error MSB6006: "cmd.exe" exited with code 1. [D:\Bond\build_x64\compiler\gbc.vcxproj]
Done Building Project "D:\Bond\build_x64\compiler\gbc.vcxproj" (Rebuild target(s)) -- FAILED.
Done Building Project "D:\Bond\build_x64\compiler\gbc.vcxproj.metaproj" (Rebuild target(s)) -- FAILED.
Done Building Project "D:\Bond\build_x64\cpp\bond.vcxproj.metaproj" (Rebuild target(s)) -- FAILED.
Done Building Project "D:\Bond\build_x64\examples\cpp\core\bf\bf.vcxproj.metaproj" (Rebuild target(s)) -- FAILED.

**Comment by chwarr** [comment]
Can you try using a newer version of the Haskell Stack tool? The CI builds for both Linux & Windows are successful with version 2.1.3, but you're using 1.5.1. You may need to manually delete your stack config and caches if they're no longer compatible with each other. The [Haskell Stack site](https://docs.haskellstack.org/en/stable/README/) has details about where these may be located on your machine.

**Comment by chwarr** [comment]
I'm going to close this issue for now since I haven't seen any activity in a couple of weeks. If you're still having this problem or have additional details, please add a comment. Thanks.
