### ISSUE TITLE
What is the most efficient way to serialize to/read from a std::string

### ISSUE THREAD

**Issue by KerstinKeller** [microsoft/bond#1014]
An API which I am using requires me to provide the serialized data as a `std::string`. So I am wondering what is the most efficient way to serialize bond data to a `std::string`.

```
  Some::Custom::Type msg_;
  std::string buffer_;
  
  ::bond::OutputBuffer output_buffer;
  ::bond::SimpleBinaryWriter<::bond::OutputBuffer> writer(output_buffer);
  ::bond::Serialize(msg_, writer);
  auto blob = output_buffer.GetBuffer();
  buffer_.clear();
  buffer_.assign(blob.content(), blob.size());
```

The following code works, but I guess that it is not very efficient.
I would assume that I have a least 2 memcopies, once copying from `output_buffer` to `blob`, and then from `blob` to `buffer_` (the target `std::string`).

Do you know if / how I can get either the SimpleBinaryWriter or the OutputBuffer to directly serialize to a `std::string`, or do you have another proposal how I can achieve that?

Also, is there a way to reset / clear the Output buffer, so that I can reuse the buffer als well as the writer? If I repeatedly call the `Serialize` method, the data gets aggregated in the `OutputBuffer` object.

Thanks for your help!

**Comment by sapek** [comment]
Take a look at this [example](https://github.com/microsoft/bond/tree/master/examples/cpp/core/output_stream_allocator).

**Comment by chwarr** [comment]
I believe this question has been answered. If not, feel free to re-open this issue with additional details. Thank you.

**Comment by jasonzio** [comment]
If you're using C++17, modify the CustomAllocator() type in the example to return an std::string_view of the used portion of the buffer. That gives you zero copy access in what most callers will accept as a "string".
