### ISSUE TITLE
undefined use of std::memcpy in OutputBuffer

### ISSUE THREAD

**Issue by pgit** [microsoft/bond#1018]
Discovered while running **ubsan** on an example serializing into a default-constructed **OutputBuffer**:

https://github.com/microsoft/bond/blob/25eda41a016e4b8b183051c86005cf350271b99d/cpp/inc/bond/stream/output_buffer.h#L225

On the first call to Write, std::memcpy() is called with a nullptr destination and a size of zero. While this should be safe in practice, it is undefined behaviour: https://en.cppreference.com/w/cpp/string/byte/memcpy

A simple check if **sizePart** is 0 should fix this.

**Comment by chwarr** [comment]
Makes sense. Would you be interested in submitting a PR with the fix?

**Comment by chwarr** [comment]
Fix merged. Thanks!
