### ISSUE TITLE
BinSkim error BA2022: Images should be correctly signed by trusted publishers using cryptographically secure signature algorithms.

### ISSUE THREAD

**Issue by zendu** [microsoft/bond#1019]
BinSkim analysis shows error BA2022 for following dlls:
Bond.Attributes.dll
Bond.dll
Bond.IO.dll
Bond.JSON.dll

Error message:
Images should be correctly signed by trusted publishers using cryptographically secure signature algorithms. This rule invokes WinTrustVerify to validate that binary hash, signing and public key algorithms are secure and, where configurable, that key sizes meet acceptable size thresholds.

Cryptographically weak signatures: [digest algorithm: 'sha1NoSign' + digest encryption algorithm: 'RSA']

**Comment by chwarr** [comment]
What version of Bond are you using? Anything later than 8.0.0 is [dual signed with SHA1 and SHA2](https://github.com/microsoft/bond/blob/master/CHANGELOG.md#800-2018-05-30).

**Comment by chwarr** [comment]
Bond 9.0 is now only signed using SHA-2 signatures. I believe this was addressed in 8.0 but should be addressed for sure in 9.0.

If not, please re-open this with additional details about the version your using and what signature you're seeing on the Bond binaries you're consuming (To rule out a private build that isn't code signed at all, for example.).
