### ISSUE TITLE
Managed c++/cli support - unable to reference Bond.Core.CSharp

### ISSUE THREAD

**Issue by mediabuff** [microsoft/bond#1023]
This used to work before. Now I get:
'Could not install package 'Bond.Core.CSharp 8.2.0'. You are trying to install this package into a project that targets 'native,Version=v0.0', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.'

You may try compiling IPC.bond - managed library
https://github.com/microsoft/IPC.Bond/tree/master/Managed

**Comment by ara-ayvazyan** [comment]
Can you be more specific about the issue? I don't see any issues with the [latest build](https://ci.appveyor.com/project/ara-ayvazyan/ipc-bond/branch/master).

From the description it looks like that you are trying to use `8.2.0`, while the existing one is still on older `6.0.0` version. More details would help to better understand the problem.

**Comment by mediabuff** [comment]
I started working on updating both of your projects IPC and IPC.bond a week back. It looks like you have started upgrading it as well - last few days. Thanks for that.

Yes, I was using the latest tools and version. Specifically, in this case 8.2.0 . Please try upgrading to this version of Bond.

Also, I am modified the projects to use vcpkg for Bond and Boost linking.

**Comment by ara-ayvazyan** [comment]
I've tried upgrading to `8.2.0` locally (without `vcpkg`) and still did not see issues.

**Comment by ara-ayvazyan** [comment]
Upgrade to `8.2.0` in [this commit](https://github.com/microsoft/IPC.Bond/commit/cea5ebac796a92f61e26adcaf279959918b5954c).

**Comment by mediabuff** [comment]
Thanks. Any chance of enabling x86

**Comment by ara-ayvazyan** [comment]
Could you move this discussion to corresponding project? Let's do not spam this project with unrelated topic :).

**Comment by chwarr** [comment]
Since this appears to be about IPC.Bond, I'm going to close this issue.
