### ISSUE TITLE
Release 9.0?

### ISSUE THREAD

**Issue by bhardwajs** [microsoft/bond#1034]
With the commits to remove MSVC 2013 conditional code and make Bond C++ 20 compatible, would it be possible to get new release of `Bond.Compiler`?

https://github.com/microsoft/bond/commit/f1cb7071349cc935ae5c1c71b6ac33d06111a310
https://github.com/microsoft/bond/commit/f89c8241a526c111116a5a8b5893df47cc5f668d

**Comment by chwarr** [comment]
Not opposed to it, but it probably won't happen this week.

**Comment by chwarr** [comment]
It would be a 9.0 release. Title updated.

**Comment by jthelin** [comment]
X-ref: https://github.com/microsoft/bond/issues/1027#issuecomment-631753395

**Comment by vaboca** [comment]
Looking forward to upgrade this, can't use Visual Studio 2019 16.6 due to C5208.

Thanks.

**Comment by mdslack** [comment]
Yes, please ASAP. Visual Studio 2019 16.6 is wreaking havoc.

**Comment by chwarr** [comment]
On my to do list for today.

**Comment by chwarr** [comment]
The [9.0.0 release](https://github.com/microsoft/bond/releases/tag/9.0.0) is live now. NuGet.org has the packages too.
