### ISSUE TITLE
Build steps failing due to -Werror=class-memaccess

### ISSUE THREAD

**Issue by JerryJoyce** [microsoft/bond#1042]
I'm trying to build this repo in a Docker container following the steps in the readme.  Here is an excerpt from my Dockerfile:

```
FROM mcr.microsoft.com/dotnet/core/sdk:3.1

ARG tools_dependencies="gcc cmake libboost-dev libboost-thread-dev unzip zlib1g-dev"
RUN DEBIAN_FRONTEND=noninteractive apt-get update && apt-get install -y --no-install-recommends \
    ${tools_dependencies}

RUN curl -sSL https://get.haskellstack.org/ | sh

RUN cd /tmp && \
    git clone --recursive https://github.com/microsoft/bond.git && \
    cd bond && \
    mkdir build && \
    cd build && \
    cmake -DBOND_ENABLE_GRPC=FALSE .. && \
    make -j $(nproc) && \
    make install && \
    cd ../.. && \
    rm -rm /tmp/bond
```
The make step fails with:

```
/tmp/bond/thirdparty/rapidjson/include/rapidjson/document.h:1939:24: error: 'void* memcpy(void*, const void*, size_t)' writing to an object of type 'class rapidjson::GenericValue<rapidjson::UTF8<> >' with no trivial copy-assignment; use copy-assignment or copy-initialization instead [-Werror=class-memaccess]
             std::memcpy(e, values, count * sizeof(GenericValue));

```

**Comment by chwarr** [comment]
Looks like there are some reports of this in [the upstream](https://github.com/Tencent/rapidjson/issues?q=is%3Aissue+class-memaccess) with [some fixes](https://github.com/Tencent/rapidjson/pull/1323). Does it build if you change the RapidJSON submodule to point to commit [2bbd33b332](https://github.com/Tencent/rapidjson/commit/2bbd33b33217ff4a73434ebf10cdac41e2ef5e34) or later?

If so, a PR to bump the RapidJSON submodule version would be appreciated.

If not, can you either contribute a PR
* to upstream that fixes this issue that can be consumed here or
* to Bond that pushes/pops a suppression for this error around the RapidJSON `#include`s?

**Comment by bhardwajs** [comment]
@chwarr - Any issues with bumping up RapidJSON submodule to the latest commit that is building correctly on upstream? I am thinking of [8f4c021](https://github.com/Tencent/rapidjson/commit/8f4c021fa2f1e001d2376095928fc0532adf2ae6) on Apr 10?

I can send a PR for this.

**Comment by chwarr** [comment]
Probably not.
