### ISSUE TITLE
grpc asp.net core need BindService

### ISSUE THREAD

**Issue by wuzhuoqing** [microsoft/bond#1048]
C# bond 8.2

grpc asp.net core need BindService(ServiceBinderBase serviceBinder, ServiceBase serviceImpl) which is not generated.

**Comment by chwarr** [comment]
I haven't looked into what it would take to support the https://github.com/grpc/grpc-dotnet stack in C#. (It didn't exist when Bond's gRPC bindings were created, and none of the current users of Bond-over-gRPC# have needed it.)

If this is something that you want, would you be interested in contributing it?

**Comment by wuzhuoqing** [comment]
@chwarr thanks for reply. My workaround for now is manually edit the generated service file and manually include the attribute following the official visual studio proto grpc service example. 

I don't have much info about how to contribute though. Will this just some template change?

`[BindServiceMethod(typeof(DataService), "BindService")]` and `public static void BindService(ServiceBinderBase serviceBinder, DataServiceBase serviceImpl)`

```
        [BindServiceMethod(typeof(DataService), "BindService")]
        public abstract class DataServiceBase
        {
            public abstract global::System.Threading.Tasks.Task<global::Bond.Grpc.IMessage<BondDataResponse>> Get(global::Bond.Grpc.IMessage<BondDataRequest> request, global::Grpc.Core.ServerCallContext context);
        }

        public static void BindService(ServiceBinderBase serviceBinder, DataServiceBase serviceImpl)
        {
            serviceBinder.AddMethod(Method_Get, serviceImpl == null ? null : (UnaryServerMethod<IMessage<BondDataRequest>, IMessage<BondDataResponse>>)serviceImpl.Get);
        }
```

**Comment by wuzhuoqing** [comment]
Looking further seems the BindService is still experimental API. Guess can wait until that's in stable state first.

```
/// <summary>Register service method with a service binder with or without implementation. Useful when customizing the  service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
```

**Comment by chwarr** [comment]
Sounds good. Closing for now.
