### ISSUE TITLE
Upload bond to conan C++ package source

### ISSUE THREAD

**Issue by yelu** [microsoft/bond#1061]
Conan is a popular C++ management system. Do we have a plan to upload bond into it?

Conan: https://conan.io/center/

**Comment by chwarr** [comment]
The Bond team currently doesn't maintain any definitions for C++ package management systems, and we don't plan to start maintaining them in the foreseeable future. You're welcome to submit one to Conan yourself, and if there are ways that Bond can be improved to make this easier, please open issues and pull requests.

The vcpkg definition is maintained by those using Bond with vcpkg, and they submitted the README and CMake changes needed to get it working.
