### ISSUE TITLE
why am I missing type_traits when trying to build c/cpp extension for python?

### ISSUE THREAD

**Issue by YinYangOfDao** [microsoft/bond#1068]
I have installed bond on my ubuntu 18.04
I checked and confirmed that my libstdc++-7-dev is already the newest version (7.5.0-3ubuntu1~18.04).

when I tried to build an extension as [guided](https://microsoft.github.io/bond/manual/bond_py.html#about),
I got following issues:

> running build
running build_ext
building 'example' extension
x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include/python3.6m -c record.c -o build/temp.linux-x86_64-3.6/record.o
In file included from /usr/local/include/bond/core/bond_version.h:6:0,
                 from example_types.h:16,
                 from example_reflection.h:16,
                 from record.c:1:
/usr/local/include/bond/core/config.h:87:1: error: unknown type name ‘namespace’
 namespace bond { namespace ext
 ^~~~~~~~~
/usr/local/include/bond/core/config.h:87:16: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘{’ token
 namespace bond { namespace ext
                ^
In file included from example_types.h:16:0,
                 from example_reflection.h:16,
                 from record.c:1:
/usr/local/include/bond/core/bond_version.h:9:10: fatal error: type_traits: No such file or directory
 #include <type_traits>
          ^~~~~~~~~~~~~
compilation terminated.
error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

**Comment by chwarr** [comment]
It looks like CMake is isn't finding a C++ compiler but is, instead, finding a C compiler. I don't have any guidance for how to debug this particular issue, unfortunately. I've never seen it before.

On my Ubuntu 20.04 machine, `c++` resolves to `g++` which eventually resolves to <code>/usr/bin/x86_64-linux-gnu-g<b>++</b>-9</code>. Notice the `++` instead of the `cc`.

**Comment by YinYangOfDao** [comment]
ohh, thanks a lot for the comment. I realized that I should use .cpp as extension name and specify it in setup file at the sametime. now I can compile and install it (although I got segmentfault after importing, I'd further investigate).
