### ISSUE TITLE
can build c++ extension but failed to import in python

### ISSUE THREAD

**Issue by YinYangOfDao** [microsoft/bond#1069]
I followed [bond python tutorial ](https://microsoft.github.io/bond/manual/bond_py.html#basic-example), and since the tutorial didn't mention file name of following code, I created a recordmodule.cpp:

> #include "example_reflection.h"
#include <bond/python/struct.h>
BOOST_PYTHON_MODULE(example)
{
    bond::python::struct_<example::Record>()
        .def();
}

then I did some search and created a setup_example.py:

> #!/usr/bin/env python
from distutils.core import setup
from distutils.extension import Extension
setup(name="PackageName",
    ext_modules=[
        Extension("example", ["examplemodule.cpp"],
        libraries = ["boost_python"])
    ])

then I ran `python setup_example.py build` and `sudo python setup_example.py install` to build and install the extension
how ever when I tried to import it from an interactive session, I got this ImportError:

> ImportError: /usr/local/lib/python2.7/dist-packages/example.so: undefined symbol: _ZN7example6Record6Schema15s_name_metadataE

I also tried to turn on `-Wl,--no-undefined` linker option, and got a lot of error logs, and here I pick same examples:

> /usr/local/include/bond/core/parser.h:275: undefined reference to `bond::Variant::Schema::s_nothing_metadata'
/usr/local/include/bond/core/parser.h:275: undefined reference to `bond::Variant::Schema::s_wstring_value_metadata'
/usr/include/boost/python/with_custodian_and_ward.hpp:93: undefined reference to `PyExc_IndexError'
/usr/include/boost/python/with_custodian_and_ward.hpp:93: undefined reference to `PyErr_SetString'

however I didn't have any issue when installing bond on my ubuntu18.04 machine.

**Comment by chwarr** [comment]
The missing symbol `_ZN7example6Record6Schema15s_name_metadataE` suggests that your extension hasn't compiled or linked with the generated _types.cpp that gbc emits. Bond's [Python example](https://github.com/microsoft/bond/blob/2104c33c10c0feddedc01744ce87af4911963945/examples/python/core/extension/CMakeLists.txt) uses a CMake helper function, [`add_bond_python_module`](https://github.com/microsoft/bond/blob/8d0842280856f357664d6ea9d3d010497444e8ab/cmake/Bond.cmake#L149-L186) which arranges for code generation on line 166. Make sure your build is invoking gbc on your .bond files, compiling the generated .cpp files, and arranging for these to be linked into your extension (E.g., by directly linking the .o files or packing them into a .a that eventually gets linked in.).

The errors about `bond::Variant::Schema::s_nothing_metadata` being missing suggests that your extensions isn't linking with libbond.a or libbond_apply.a. The same helper function, `add_bond_python_module`, arranges for this as well on lines 173 and 174. You will need to replicate this in your build system too.

**Comment by chwarr** [comment]
Since there hasn't been any reply from @YinYangOfDao for a few weeks, I'm going to close this issue for now. If you still need assistance, please comment with details about where you are now. Thanks.
