### ISSUE TITLE
bond::bonded<MyType> raises UnknownProtocolException when used with custom stream 

### ISSUE THREAD

**Issue by jeanga** [microsoft/bond#1077]
I have defined a custom stream type following the docs here https://microsoft.github.io/bond/manual/bond_cpp.html#custom-streams.
All was great until I decided to use this stream with a bond::bonded object.

The compiler asked for a "buffer_magic" for my stream, leading me to add:
```cpp
namespace bond {
    BOND_DEFINE_BUFFER_MAGIC(FullyQualidedNamespace::MyStream, 0x4944 );
}
```
to my stream's header file.
Now, I am getting UnknownProtocolException which, in term, lead me to review this PR: https://github.com/microsoft/bond/pull/425

To be honest, I got lost there and really did not get how to proceed from here (and even if it was related to my problem at all...).

Any help how to use my custom stream with bond::bonded objects would really help unlock my project stalled on this issue right now.
Thanks!

**Comment by jeanga** [comment]
I have made some progress thanks to the great code sample fg (referenced in https://github.com/microsoft/bond/pull/425 that I previously overlooked).

The main change (in my case) were adding:
```cpp
using MyProtocols = bond::BuiltInProtocols::Append<
    bond::CompactBinaryReader<FullyQualidedNamespace::MyStream>
```
and then, use: 
```cpp
bond::bonded<To> bonded(base);
To obj;
bonded.Deserialize<MyProtocols>(obj);
```
Another important point was the implementation of the Read protocol/concept:
The copy contructor (from the fg code sample):
```cpp
// Copy ctor opens a new stream in order to keep independent file pointer.
MyStream(const MyStream& that);
```
must make sure the original and copy will have independent file pointers.

I also added CreateInputBuffer&GetCurrentBuffer from the fg sample but I am not sure how that affects the outcome...

Anyways, thank you for the great work on bond, many niceties to use and leverage here.
I will make sure I read&understand the code samples as they complement nicely the documentation.
(a quick summary of which sample demonstrates what would be nice though :-))

**Comment by chwarr** [comment]
Yup, what you ended up doing makes sense. If it helps anyone else, the bf example shows how to [implement][stream] a [custom stream][cs] atop a `std::ifstream` and how to [use this new stream type when invoking various Bond APIs][protocol-list].

[cs]: https://microsoft.github.io/bond/manual/bond_cpp.html#custom-streams
[protocol-list]: https://github.com/microsoft/bond/blob/05c57981a3f9e259526e41f1ca92c0f1a5a6d786/examples/cpp/core/bf/main.cpp#L100-L113
[stream]: https://github.com/microsoft/bond/blob/05c57981a3f9e259526e41f1ca92c0f1a5a6d786/examples/cpp/core/bf/input_file.h

**Comment by chwarr** [comment]
I believe this has been answered, so I'm going to close this issue. Feel free to add more comments if needed.
