### ISSUE TITLE
std::ptr_fun deprecatd in C++11 and removed in C++17

### ISSUE THREAD

**Issue by jpg85** [microsoft/bond#1080]
https://github.com/microsoft/bond/blob/05c57981a3f9e259526e41f1ca92c0f1a5a6d786/python/inc/bond/python/converters.h#L81

Function should be replaced with alternative. Since boost is already being used, "boost::ptr_fun" should be a direct replacement.

**Comment by chwarr** [comment]
Looks like a lambda works too. Proposed fix [is in PR](https://github.com/microsoft/bond/pull/1081).
