### ISSUE TITLE
List of companies using Bond apart from Microsoft

### ISSUE THREAD

**Issue by jviotti** [microsoft/bond#1095]
I'm interested in collecting a small list of companies using Bond for research purposes (I'm writing a paper that discussed Bond and a bit of its history and present use).

Do you know where I can find this information? The "Used by" GitHub tab (https://github.com/microsoft/bond/network/dependents?package_id=UGFja2FnZS0xNTY5MjM1NjE%3D) is very hard to browse, as the majority of its items involve individuals and not organisations.

**Comment by chwarr** [comment]
No, we have nothing we can share here. Sorry.
