### ISSUE TITLE
Does cloning support Bond aliases?

### ISSUE THREAD

**Issue by Redbolts** [Microsoft/bond#110]
It works fine for serialising and deserialising (blob<->guid) but I get a :

System.TypeInitializationException : The type initializer for 'Cache`1' threw an exception.
---- System.ArgumentException : Instance property 'Array' is not defined for type 'System.Guid'

cheers,

Guy

**Comment by sapek** [comment]
[Yes](https://github.com/Microsoft/bond/blob/master/cs/test/core/TypeAliasTests.cs#L253). Can you post the code you have problem with?

**Comment by Redbolts** [comment]
ah sorry. didn't spot that test. Unfortunately can't post code but given it should work, error probably in my code.
 cheers,

Guy
