### ISSUE TITLE
Bond vs Google Protobuf

### ISSUE THREAD

**Issue by soroshsabz** [microsoft/bond#1111]
ITNOA

As I can see this repo is very inactive, so my first question is this repo live or dead?

the second question is where is benchmark between Microsoft Bond and new Google Protobuf and Google Flat Buffer and Captain proto and Thrift and etc.

thanks

**Comment by chwarr** [comment]
Microsoft hasn't needed to make many changes in Bond lately, so there hasn't been much activity from us.

For a discussion about how Bond compares to similar frameworks see [Why Bond](https://microsoft.github.io/bond/why_bond.html).

For benchmarks, see these previous discussions for details:

* [Issue #122: Slow serialization](https://github.com/microsoft/bond/issues/122)
* [Issue #63: Benchmarks](https://github.com/microsoft/bond/issues/63)

**Comment by soroshsabz** [comment]
@chwarr as you can see (know) #122 and #63 is very old, and Google Protobuf and Google flatbuffer has many many performance improvement until today, So my question is did know any fair and update benchmark between Bond and Google Protobuf?

thanks

**Comment by soroshsabz** [comment]
related to #978

**Comment by chwarr** [comment]
The Bond open source project does not maintain benchmarks like what you are looking for, nor do maintain a list of current benchmarks.

Serialization benchmarks are highly dependent on your expected use cases. If you need this level of detail, I encourage you to benchmark with your own representative schemas and payloads.

**Comment by chwarr** [comment]
I believe your questions have been answered as best Microsoft can, so I'm going to close this issue. Feel free to re-open it or to open other issues. Thanks!
