### ISSUE TITLE
Question: any plan to support go-lang?

### ISSUE THREAD

**Issue by hcoona** [microsoft/bond#1116]
Glad to know that bond already supported C++/C#/Python/Java. I'd like to know if there was any plan to support go-lang or any third-party support for it. 

Go is keeping in Top 10 popularity for a few years according to GitHub programming language stats. I think it would be of great helpful to support such a PL.

**Comment by chwarr** [comment]
Duplicate of [Suggestion: Support of Go language generation](https://github.com/microsoft/bond/issues/949):

> As of November 2020 and for the foreseeable future, no new languages will be added to Bond by Microsoft.
