### ISSUE TITLE
[MSVC] Boringssl emits warning C4191 on MSVC when building Bond

### ISSUE THREAD

**Issue by QuellaZhang** [microsoft/bond#1132]
Bond fails to build on latest MSVC due to warning C4191. Looking at the details of the error, this error was actually issued by Boringssl which is a third-party of grpc and has been removed upstream https://github.com/grpc/grpc/tree/master/third_party. Can you help look?

**Note**: This is an internal test, only reproduced on unreleased MSVC, the next version of VS will have this behavior.

**Build steps:**

1. open VS2022 x64 tools command
2. git clone https://github.com/microsoft/bond.git F:\gitP\Microsoft\bond
3. set path=F:\gitP\Microsoft\bond\tool;%PATH%
4. set PreferredToolArchitecture=x64
5. set BOOST_ROOT=F:\tools\boost_1_77_0\x64
6. set BOOST_LIBRARYDIR=F:\tools\boost_1_77_0\x64\lib64-msvc-14.1
7. cd compiler
8. powershell.exe -NoProfile -ExecutionPolicy Bypass "..\tool\Setup.ps1"
9. mkdir F:\gitP\Microsoft\bond\build_amd64
10. cd F:\gitP\Microsoft\bond\build_amd64
11. cmake -G "Visual Studio 16 2019" -A x64 -DCMAKE_SYSTEM_VERSION=10.0.18362.0 ..
12. msbuild /p:Platform=x64 /p:Configuration=Release bond.sln /t:Rebuild

Build log: [build.log](https://github.com/microsoft/bond/files/8038559/build.log)

**Error info:**
a_bitstr.c
F:\gitP\microsoft\bond\thirdparty\grpc\third_party\boringssl\crypto\..\include\openssl/stack.h(375,1): error C2220: the following warning is treated as an error
F:\gitP\microsoft\bond\thirdparty\grpc\third_party\boringssl\crypto\..\include\openssl/stack.h(375,1): warning C4191: 'type cast': unsafe conversion from 'stack_OPENSSL_STRING_cmp_func' to 'stack_cmp_func'
        Calling this function through the result pointer may cause your program to fail
F:\gitP\microsoft\bond\thirdparty\grpc\third_party\boringssl\crypto\..\include\openssl/stack.h(375,1): warning C4191: 'type cast': unsafe conversion from 'void (__cdecl *)(OPENSSL_STRING)' to 'void (__cdecl *)(void *)'
        Calling this function through the result pointer may cause your program to fail
F:\gitP\microsoft\bond\thirdparty\grpc\third_party\boringssl\crypto\..\include\openssl/stack.h(375,1): warning C4191: 'type cast': unsafe conversion from 'stack_cmp_func' to 'stack_OPENSSL_STRING_cmp_func'
        Calling this function through the result pointer may cause your program to fail
F:\gitP\microsoft\bond\thirdparty\grpc\third_party\boringssl\crypto\..\include\openssl/stack.h(375,1): warning C4191: 'type cast': unsafe conversion from 'OPENSSL_STRING (__cdecl *)(OPENSSL_STRING)' to 'void *(__cdecl *)(void *)'
        Calling this function through the result pointer may cause your program to fail
F:\gitP\microsoft\bond\thirdparty\grpc\third_party\boringssl\crypto\..\include\openssl/bio.h(80,1): warning C4191: 'type cast': unsafe conversion from 'stack_BIO_cmp_func' to 'stack_cmp_func'
        Calling this function through the result pointer may cause your program to fail
F:\gitP\microsoft\bond\thirdparty\grpc\third_party\boringssl\crypto\..\include\openssl/bio.h(80,1): warning C4191: 'type cast': unsafe conversion from 'void (__cdecl *)(BIO *)' to 'void (__cdecl *)(void *)'
        Calling this function through the result pointer may cause your program to fail
F:\gitP\microsoft\bond\thirdparty\grpc\third_party\boringssl\crypto\..\include\openssl/bio.h(80,1): warning C4191: 'type cast': unsafe conversion from 'stack_cmp_func' to 'stack_BIO_cmp_func'

**Comment by chwarr** [comment]
Thanks for the report. Given that we're planning to remove the Bond-over-gRPC components in [May 2022](https://github.com/microsoft/bond/issues/1131), we have no plans to change the gRPC version between now and then. Users of Bond with the newer version of MSVC will be able to use a forthcoming version of Bond without the gRPC components. You can disable the gRPC components today by passing `-DBOND_ENABLE_GRPC=FALSE` to CMake.
