### ISSUE TITLE
Bond.JSON silently references Newtonsoft.Json v9

### ISSUE THREAD

**Issue by z-10** [microsoft/bond#1133]
Bond.JSON silently references Newtonsoft.Json v9 with no listed dependencies in nuget feed.

**Comment by chwarr** [comment]
Can you be more specific about the package you are referring to? There's no [official Bond package named "Bond.JSON"](https://microsoft.github.io/bond/manual/bond_cs.html#nuget-packages). Bond.Runtime.CSharp ([.nuspec](https://github.com/microsoft/bond/blob/48dfc058380d88b85daa0165ad66d15e4205601a/cs/nuget/bond.runtime.csharp.nuspec#L27)/[NuGet.org listing](https://www.nuget.org/packages/Bond.Runtime.CSharp/)) is where the JSON serialization code lives. It lists Newtonsoft.Json >= 9.0.1 as a dependency.

**Comment by z-10** [comment]
My bad didn't realized that it referenced runtime package.
