### ISSUE TITLE
The MSVC team recently test Bond project failed to Build due to error MSB8066: Custom build on windows_x64 mode

### ISSUE THREAD

**Issue by rachelhe123** [microsoft/bond#1145]
Hi All,

The MSVC team recently test Bond project failed to Build due to error MSB8066: Custom build for on windows_x64 mode

**Describe the bug**
Bond project failed to Build due to error MSB8066: Custom build for on windows_x64 mode. Could you please help look at this issue or provide some workarounds? Thanks in advance. 

**To Reproduce on Windows**
1. git -C "F:\gitP\Microsoft\bond" rev-parse --git-dir
2.git -C "F:\gitP" clone https://github.com/Microsoft/bond Microsoft\bond
3. git -C "F:\gitP\Microsoft\bond" checkout e6a1a8f
4. git -C "F:\gitP\Microsoft\bond" submodule sync
5. git -C "F:\gitP\Microsoft\bond" submodule foreach git reset --hard
6. git -C "F:\gitP\Microsoft\bond" submodule foreach git clean -xdf
7. git -C "F:\gitP\Microsoft\bond" submodule update --init --recursive
8. set VSCMD_SKIP_SENDTELEMETRY=1 & "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\Tools\VsDevCmd.bat" -host_arch=amd64 -arch=amd64
9. cd F:\gitP\Microsoft\bond
10.xcopy F:\tools\bond\tool F:\gitP\Microsoft\bond\tool /k/r/e/i/s/c/h/f/y
11. set path=F:\gitP\Microsoft\bond\tool;%PATH%
12. set PreferredToolArchitecture=x64
13. set BOOST_ROOT=F:\tools\boost_1_77_0\x64
14. set BOOST_LIBRARYDIR=F:\tools\boost_1_77_0\x64\lib64-msvc-14.1
15. cd compiler
16. powershell.exe -NoProfile -ExecutionPolicy Bypass "..\tool\Setup.ps1" 2>&1
17. mkdir F:\gitP\Microsoft\bond\build_amd64
18. cd F:\gitP\Microsoft\bond\build_amd64
19. cmake -G "Visual Studio 16 2019" -A x64 -DCMAKE_SYSTEM_VERSION=10.0.18362.0 .. 2>&1
20. set VSCMD_SKIP_SENDTELEMETRY=1 & "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\Tools\VsDevCmd.bat" -host_arch=amd64 -arch=amd64
21. set _CL_=/wd5026 /wd4774 /wd4996 /wd4702 /wd5045 /wd4643 /wd5208 /wd4191
22. msbuild /m /p:Platform=x64 /p:Configuration=Release bond.sln /t:Rebuild 2>&1

**Error message**
Build FAILED.
       "F:\gitP\microsoft\bond\build_amd64\bond.sln" (Rebuild target) (1) ->
       "F:\gitP\microsoft\bond\build_amd64\compiler\gbc.vcxproj.metaproj" (Rebuild target) (30) ->
       "F:\gitP\microsoft\bond\build_amd64\compiler\gbc.vcxproj" (Rebuild target) (87) ->
       (CustomBuild target) ->
         C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.t
       argets(241,5): error MSB8066: Custom build for 'F:\gitP\microsoft\bond\build_amd64\CMakeFiles\4c242fb8b092c9e7f1
       18e302042f3822\gbc.exe.rule;F:\gitP\microsoft\bond\build_amd64\CMakeFiles\934707dc81f49805876bd564bd8a233b\gbc.c
       omp.rule;F:\gitP\microsoft\bond\build_amd64\CMakeFiles\a9986663bac8f2666be4c4b72ff35507\gbc.rule;F:\gitP\microso
       ft\bond\compiler\CMakeLists.txt' exited with code 1. [F:\gitP\microsoft\bond\build_amd64\compiler\gbc.vcxproj]

**Expected behavior**
Test should be run pass and output total test log on the windows_x86.

**Setup**
VS 2019 + Windows Server 2019

**Additional context**
build log
[buildlog.txt](https://github.com/microsoft/bond/files/8529149/buildlog.txt)

**Comment by chwarr** [comment]
Building the gbc tool (which is written in Haskell and needs a Haskell toolchain) failed for you. From the error message, it looks like either 1) there was a transient networking issue fetching packages from the Haskell Stack package repository or 2) you may be using an older version of [the Haskell Stack tool](https://docs.haskellstack.org/en/stable/README/) that doesn't know about newer certificates.

What version of stack.exe do you have installed? Do you still encounter this issue if you update to the current version?

Here's the more detailed error message I see in the log:

```plain
       CustomBuild:
         "The build of 'F:\gitP\microsoft\bond\build_amd64\CMakeFiles\934707dc81f49805876bd564bd8a233b\gbc.comp.rule' depends on 'F:\GITP\MICROSOFT\BOND\BUILD_AMD64\COMPILER\BUILD\GBC\GBC.EXE' which is produced by the build of 'F:\gitP\microsoft\bond\build_amd64\CMakeFiles\4c242fb8b092c9e7f118e302042f3822\gbc.exe.rule'. The items cannot be built in parallel."
         "The build of 'F:\gitP\microsoft\bond\build_amd64\CMakeFiles\a9986663bac8f2666be4c4b72ff35507\gbc.rule' depends on 'F:\GITP\MICROSOFT\BOND\BUILD_AMD64\COMPILER\GBC.COMP' which is produced by the build of 'F:\gitP\microsoft\bond\build_amd64\CMakeFiles\934707dc81f49805876bd564bd8a233b\gbc.comp.rule'. The items cannot be built in parallel."
         Generating build/gbc/gbc.exe
         'stty' is not recognized as an internal or external command,
         operable program or batch file.
         [0mF:\gitP\microsoft\bond\compiler\bond.cabal was generated with a newer version of hpack,
         please upgrade and try again.[0m
         [0mCabal file info not found for aeson-1.4.4.0@sha256:c70d78f78efb1d766f1c5b594c9eadcc1bc9587d83e5a50714b9a91105fb2ca4,6963, updating[0m
         [0mSelected mirror https://s3.amazonaws.com/hackage.fpcomplete.com/[0m
         [0mDownloading root[0m
         [0mHttpExceptionRequest Request {
           host                 = "s3.amazonaws.com"
           port                 = 443
           secure               = True
           requestHeaders       = [("Accept-Encoding",""),("Cache-Control","no-transform"),("User-Agent","Haskell pantry package")]
           path                 = "/hackage.fpcomplete.com/root.json"
           queryString          = ""
           method               = "GET"
           proxy                = Nothing
           rawBody              = False
           redirectCount        = 10
           responseTimeout      = ResponseTimeoutDefault
           requestVersion       = HTTP/1.1
         }
          (InternalException (HandshakeFailed (Error_Protocol ("certificate has unknown CA",True,UnknownCa))))
```

**Comment by rachelhe123** [comment]
I update the stack app, then it worked, so closed this bug.
