### ISSUE TITLE
Potential breaking change: Upgrade to exclusively use Newtonsoft.Json >= 13.0.1

### ISSUE THREAD

**Issue by ankitC** [microsoft/bond#1156]
In the wake of a new vulnerability discovered in the Newtonsoft.Json library, it is recommended that consumers use version greater than or equal to 13.0.1. (https://github.com/JamesNK/Newtonsoft.Json/issues/2457)

In order to comply with the recommendation, I propose the community to consider upgrading the dependency on Netwonsoft.Json to the recommended version. It will help all the consumers of the Bond library to make their applications and services inherently more secure.

The Bond library states it's dependency as >= 9.0.1, and consumers are free to use any version that suits their needs. While this recommendation is not incorrect, it's not in the best interests of the consumers as we have the knowledge of the Newtonsoft issue. As a best practice, the latest version of the library should be using the most secure dependencies.

If there are enough community members that agree to this proposal, I'd be happy to work with the community and contribute to the proposed change.

**Comment by chwarr** [comment]
I don't see a compelling reason to take this breaking change in Bond, so I'm going to leave Bond at the minimum version of Newtonsoft.Json that is requires.
