### ISSUE TITLE
Merge API support for C#?

### ISSUE THREAD

**Issue by DerrikCreates** [microsoft/bond#1172]
I've been trying to find if there is a way to use the merge API in C# for the past few hours and haven't had any luck. Is this not supported or is there another C# specific approach to this?

**Comment by chwarr** [comment]
No, there is no merge API in C# Bond.

Microsoft has no plans to implement such an API (We don't need it for our own use of Bond internally.), but it would fit in to Bond, if you wanted [to contribute it](https://github.com/microsoft/bond/blob/master/CONTRIBUTING.md).

The C++ Merge API takes a payload and an object and produces a payload. In C#, you could implement a variation on a [Serializer](https://github.com/microsoft/bond/blob/e02fd28ee30d946d3f4b234151b68c26fc1f15ba/cs/src/core/Serializer.cs) that did something like this.

If you just want something for your codebase, I suspect you'd need to duplicate a lot of the "infrastructure" code that Serializer uses that isn't public.

If you are interested in contributing, can you please create a new issue that outlines the API shape, semantics, implementation plan, and test plan?

**Comment by chwarr** [comment]
I believe this has been answered.
