### ISSUE TITLE
Include enums in Bond runtime schema

### ISSUE THREAD

**Issue by wibotwi** [microsoft/bond#1178]
Now enums are included in schema as int32. Dynamic parsers might need a way to resolve int32 to enum value as a string.
I suggest to include it in the runtime schema like this:
```json
"structs": [
 {
  "metadata": {
     "name": "SomeStruct"
   },
  "fields": [
   {
      "metadata": {
         "name": "someField"
       },
      "id" : 1,
      "type": {
          "id": 16,
          "struct_def": 0,
          "enum_def": 7    -- this is new field that references Enum. Or we can reuse "struct_def" when type id is 16
       },
   },
  ]
 }
],
"enums": [      -- new top level node with all Enums
  {
    "metadata": {
         "name": "Direction",
    },
    "items": [
        {
            "item": "LEFT",
            "id": 1,
        },
        {
            "item": "RIGHT",
            "id": 2,
        },
    ]
  }  
]
```

**Comment by chwarr** [comment]
This is a good idea, but this is not a change the Bond project wants to make now or in the foreseeable future, as it has a high potential to break existing, deployed applications. I'm going to close this as "Won't Fix".

Changes to Bond's runtime schema--even additive ones like this that should be a non-breaking change--are basically impossible to make without breaking existing applications. There are, unfortunately, many applications that have serialized runtime schema data in Simple Binary and these applications have no way to deal with any schema changes to runtime schemas. (For example, see [the Bond 5.0.0 release](https://github.com/microsoft/bond/blob/master/CHANGELOG.md#500-2016-09-12) where we had to back out an additive change to runtime schemas.)
