### ISSUE TITLE
[C#] gbc.exe: Exec format error inside mcr.microsoft.com/dotnet/sdk:latest docker image.

### ISSUE THREAD

**Issue by RavMazurek** [microsoft/bond#1182]
Looks like compilation of project with bond package is impossible in docker sdk image - is that correct? Same problem on 10.0

```
MSBuild version 17.5.0-preview-23061-01+040e2a90e for .NET
          Determining projects to restore...
          Restored /var/workdir/aaa/bbb.csproj (in 11.23 sec).
          /bin/sh: 2: /tmp/MSBuildTemproot/tmp07e2245471a6416d99ff3965ff6cc96e.exec.cmd: /app/.nuget/packages/bond.csharp/9.0.5/build/../tools/gbc.exe: Exec format error
        /app/.nuget/packages/bond.csharp/9.0.5/build/Common.targets(161,5): error MSB3073: The command ""/app/.nuget/packages/bond.csharp/9.0.5/build/../tools/gbc.exe" c# --import-dir="/app/.nuget/packages/bond.csharp/9.0.5/build/../tools/inc"  --jobs=-2 --namespace=bond=Bond --output-dir="obj/Release/netstandard2.1/" --using="DateTime=System.DateTime" @"obj/Release/netstandard2.1/bonddefaultcodegen.in"" exited with code 126. [/var/workdir/aaa/bbb.csproj]
        
        Build FAILED.
```

**Comment by chwarr** [comment]
It looks like you are trying to run gbc on Linux. There is no pre-compiled version of gbc for Linux. The gbc included in the NuGet packages is only for Windows.

You will need to compile gbc yourself targeting Linux and set the environment variable (or MSBuild property) `BOND_COMPILER_PATH` the path to the gbc that you have built.

For more details, see [issue #940, gbc for Linux?](https://github.com/microsoft/bond/issues/940).

**Comment by chwarr** [comment]
(This question appears to have been cross-posted on StackOverflow.com as well under [How can I compile .net app that uses bond in docker?](https://stackoverflow.com/questions/75631473/how-can-i-compile-net-app-that-uses-bond-in-docker).)

**Comment by chwarr** [comment]
I think this has been answered. Let me know if not.
