### ISSUE TITLE
[C#] Deserializing bond-like strings into dynamic type

### ISSUE THREAD

**Issue by misoferrari** [microsoft/bond#1184]
I'm trying to deserialize a bond-like string structure into a C# dynamic type, something like:

```cs
var schema = @"
    struct Person {
        0: string Name;
    }
";

var byteArray = Encoding.UTF8.GetBytes(schema);

var inputBuffer = new InputBuffer(byteArray);

var reader = new FastBinaryReader<InputBuffer>(inputBuffer);

var @object = Deserialize<dynamic>.From(reader);

Console.WriteLine(@object);
```

Failing with: 

> An unhandled exception of type 'System.IO.InvalidDataException' occurred in Bond.dll: 'Invalid BondDataType 32'

What is the correct way to do these kind of deserializations?

**Comment by chwarr** [comment]
I'm not entirely sure what you are trying to do. In your example, what members and values do you expect `@object` to have?

Right now, the `schema` string is a snippet of the Bond interface definition language. The code then 
"coerces" this into a FastBinary payload. This is not a valid FastBinary payload.

-----

Focusing on just `Deserialize<dynamic>.From(reader)`, no, Bond does not support deserializing into `dynamic` objects out-of-the-box. You need to deserialize into a object with a known, fixed schema.

To handle arbitrary, unknown schemas one option is to move down a layer and use the protocol readers directly. See for example, issue #1162 "[In C# implementation, how to parse to structs separated by BT_STOP_BASE](https://github.com/microsoft/bond/issues/1162)", and issue #1163 ["Correct way to read list of mapped values in C#"](https://github.com/microsoft/bond/issues/1163) for examples of someone else processing payloads via readers. Tagged payloads like FastBinary do not include field names. You'll need to get that information from another source, like a [`SchemaDef`](https://microsoft.github.io/bond/manual/bond_cs.html#runtime-schema) that exactly matches the payload when it was created.

Another option would be to implement an algorithm similar to what's in [`DeserializerTransform`](https://github.com/microsoft/bond/blob/master/cs/src/core/expressions/DeserializerTransform.cs) but that has a target of a `dynamic` object. Note: `DeserializerTransform` isn't a public API, so you'll need to duplicate much of the code if you take this approach.

-----

Related: issue #585, "[Deserialize objects with incomplete or inexisting type information](https://github.com/microsoft/bond/issues/585)"

**Comment by chwarr** [comment]
Let me know if you have any follow up questions or additional details. I'm going to close this issue for now.
