### ISSUE TITLE
Is this project still being maintained?

### ISSUE THREAD

**Issue by chenrui333** [microsoft/bond#1194]
👋 looks like there are some activities based on reading the issues, but the most recent release is built with ghc 8.6, and on the homebrew side, we are thinking to [disable the formula](https://github.com/Homebrew/homebrew-core/pull/141610).

**Comment by chwarr** [comment]
Microsoft's current needs are met by ghc 8.6. We have no current plans to update the version ourselves, but would [welcome a contribution](https://github.com/microsoft/bond/blob/master/CONTRIBUTING.md) to update to a new LTS.

Microsoft has no need for the Homebrew formula ourselves and we have no plans to maintain it ourselves. We will defer to the Homebrew community for what they want to do.

**Comment by chwarr** [comment]
I believe this has been answered. Let us know if not.
