### ISSUE TITLE
bond on aarch64 is failing with unsupported LLVM

### ISSUE THREAD

**Issue by GoreshM** [microsoft/bond#1197]
Hi,
I have setup LLVM to ```clang version 15.0.6, ```
but on compilation of bond i get error saying it only supports llvm 6
````
base-orphans        > [1 of 2] Compiling Data.Orphans
base-orphans        > You are using an unsupported version of LLVM!
````

What is the plan to add support for later clang versions, or any specific reason to keep it at 6.0

Also, if i have to compile bond in cross-platform model (Host-> x86_64 and target -> aarch64) is it currently supported, if yes what are the required steps  over it?

![Uploading image.png…]()

**Comment by chwarr** [comment]
Bond doesn't have good support for cross-compilation, and this isn't something that we plan to invest in at present. The architectures we target with full support are only x86 and x64 only.

Given this, we have no plans to improve the support for ARM or other versions of LLVM.

**Comment by chwarr** [comment]
Bond doesn't have good support for cross-compilation, and this isn't something that we plan to invest in at present. The architectures we target with full support are only x86 and x64 only.

Given this, we have no plans to improve the support for ARM or other versions of LLVM.
