### ISSUE TITLE
Is it possible to use Python bindings without Boost?

### ISSUE THREAD

**Issue by fralik** [microsoft/bond#1203]
I am wondering if it is possible to use python bindings without Boost? Whether pybind11 or something else, which is more python-friendly, would work?

The problem I experienced with boost: I struggle to understand how to compile python binding for an arbitrary python version. Boost.python requires it's own python. I am using CMake + vcpkg, if I simply ask for Boost::python, then it either finds one version (let's say python 3.11) or it fails to find one (if I am building with python 3.9). The problem may be of course not related to bond, but rather to the tooling I use.

**Comment by chwarr** [comment]
No, Boost.Python is required. Microsoft has no plans to change this, and we don't want to take the project in a different direction here.
