### ISSUE TITLE
Following HLint suggestions?

### ISSUE THREAD

**Issue by philderbeast** [microsoft/bond#1206]
Running `hlint-3.8`, I'm finding 163 hints when run on `compiler`, excluding `compiler/src/Language/Bond/Codegen/Cpp/Types_h.hs` that HLint cannot parse[^1].

# Warnings currently triggered by your code
- [ ] Avoid lambda, # 1 hint
- [ ] Avoid lambda using `infix`, # 1 hint
- [ ] Eta reduce, # 9 hints
- [ ] Functor law, # 1 hint
- [ ] Move brackets to avoid $, # 3 hints
- [ ] Redundant $, # 4 hints
- [ ] Redundant <$>, # 5 hints
- [ ] Redundant bracket, # 44 hints
- [ ] Redundant case, # 5 hints
- [ ] Redundant id, # 1 hint
- [ ] Redundant return, # 1 hint
- [ ] Unused LANGUAGE pragma, # 1 hint
- [ ] Use $>, # 28 hints
- [ ] Use <$>, # 1 hint
- [ ] Use camelCase, # 41 hints
- [ ] Use concatMap, # 2 hints
- [ ] Use fmap, # 2 hints
- [ ] Use guards, # 3 hints
- [ ] Use infix, # 1 hint
- [ ] Use isJust, # 1 hint
- [ ] Use isNothing, # 3 hints
- [ ] Use newtype instead of data, # 2 hints
- [ ] Use notElem, # 2 hints
- [ ] Use when, # 1 hint

Are you open to following these suggestions? If so then I'd be happy to contribute those changes.

[^1]:  I can make it parse by adding `#ifndef __HLINT__` around lines that don't parse (adds 7 more suggestions).

**Comment by chwarr** [comment]
Thanks for making these suggestions. These changes are not ones we are planning to make to Bond. They take the project in a direction that we don't want to go.
