### ISSUE TITLE
Slow serialization

### ISSUE THREAD

**Issue by theburningmonk** [Microsoft/bond#122]
Hello, I did [some benchmark](http://theburningmonk.com/2016/01/ms-bond-and-chiron-benchmarked/) against Bond vs a bunch of other binary serializers and the results are fascinating.
 
![image](https://cloud.githubusercontent.com/assets/546969/12398580/8ff0ef2e-be0c-11e5-9ad0-e011206cb326.png)

Bond produces the smallest payload and has the fastest deserialization speed by some margin, but is also the slowest at serialization (almost 2x slower than BinaryFormatter in this case).

Was this a design decision to optimize for payload size and deserialization speed so in a simple client-server setting you're optimized for the server side of the equation? But doesn't this start to break down in the increasingly popular service-oriented architectures where there are a lot of server-to-server communications?

Love to hear your thoughts on this.

**Comment by sapek** [comment]
Thanks for adding Bond to your benchmark.

The likely cause of slow serialization in this test is this [line](https://github.com/theburningmonk/SimpleSpeedTester/blob/815c3d4ae5308966470cc4b9f533e169b6f2a2bf/examples/BinarySerializersBenchmark/BinarySerializersSpeedTest.cs#L318). `OutputBuffer` by default uses 64 KB initial buffer size, which is often a good choice in real world services but obviously bad for a micro benchmark with 40 byte payload: the serialization time is dominated by allocation of 64 KB buffer which in .Net results in zeroing out the memory. 

To measure actual serialization cost you can configure the the `OutputBuffer` to a [smaller initial size](https://github.com/theburningmonk/SimpleSpeedTester/pull/14). You don't need to know the exact size, it will reallocate if necessary, but for the best performance you should try to tune it such that you avoid both over-allocation of initial buffer and too much reallocation required to grow.

See also: [tuning Bond performance](https://microsoft.github.io/bond/manual/bond_cs.html#performance).

**Comment by theburningmonk** [comment]
Thanks, that made a huge difference!

![image](https://cloud.githubusercontent.com/assets/546969/12405543/103d350e-be3d-11e5-9a57-f2503b2f8674.png)

which brings up another related question - are you using a buffer pool already? wouldn't that mitigate the cost of constantly allocating large arrays (with the 64kb default)?

**Comment by sapek** [comment]
Pooling is often a good strategy. However it involves a lot of policy decisions, like threading and locking, which are better left to the higher level code. `OutputBuffer` is intended to be a flexible, low level implementation of [`IOutputStream`](https://github.com/Microsoft/bond/blob/master/cs/src/core/io/IOutputStream.cs) optimized for raw write speed to a managed memory (`OutputPointer` is the equivalent for unmanaged memory). 

*I took the liberty to rename your issue to "Slow serialization" to better reflect your original problem - this way it will be more helpful to others in the future.*

**Comment by benaadams** [comment]
@sapek not sure if the lifespan of the buffer is known, but if is can use System.Buffers `ArrayPool<byte>.Shared.Rent()` and `ArrayPool<byte>.Shared.Return()` ?

**Comment by sapek** [comment]
The buffer contains serialized data, so the lifetime is controlled by the application. 

An implementation of [`IOutputStream`](https://github.com/Microsoft/bond/blob/master/cs/src/core/io/IOutputStream.cs) on top of `ArrayPool<byte>` probably would be useful in some cases.

**Comment by sapek** [comment]
Please feel free to reopen if you have other related questions.
