### ISSUE TITLE
Add support for C# "char" type.

### ISSUE THREAD

**Issue by xplicit** [Microsoft/bond#13]
Currently to serialize deserialize .NET primitive type `char`, I have to write 

	[global::Bond.Id(5), global::Bond.Type(typeof(UInt16))]
	public char CharVar { get; set; }

It would be good if the `char` type has the native support from bond library, without explicitly mapping to UInt16

So the code becomes 

	[global::Bond.Id(5)]
	public char CharVar { get; set; }

and `CharVar` will be seriliazed into uint16 bond protocol field.

**Comment by sapek** [comment]
Our solution for this is [type aliases](http://microsoft.github.io/bond/manual/bond_cs.html#custom-type-mappings). 

In this case it is particularly easy because `char` is implicitly convertible to `ushort`.

In .bond file:

    using char = uint16;
    struct Foo
    {
        0: char CharVar;
    }

and then pass `--using=char=char` to gbc when compiling the file:

    <BondCodegen Include="schema.bond">
          <Options>--using=char=char</Options>
    </BondCodegen>

**Comment by sapek** [comment]
I thought about this quite a bit. It would be *very* simple to automatically handle `char` as `uint16`, basically just add a case statement [here](https://github.com/Microsoft/bond/blob/14cac06f3a996ea69df51068cbd406b74b0e9529/cs/src/core/Reflection.cs#L224-L225). However I don't think it is the right thing to do. Imagine if we wanted to extend Bond type system and add a `char` type. If we had hijacked C# `char` then we couldn't map the new type to it. Not that it is very likely that we will add `char` type, but I think it is better to keep the rule that type remapping is explicit, done using `[global::Bond.Type]`.
