### ISSUE TITLE
Support for complex types in set<T> and map<K,V>?

### ISSUE THREAD

**Issue by pkreise** [Microsoft/bond#131]
It looks like only common types are supported as the value in `set<T>` or as the key in `map<K,V>`.  Is there an easy way to accomplish this if the custom type cannot easily be aliased to a built-in type?

For example, we'd like to have a `set<bond.GUID>` as well as a `map<bond.GUID, SomeStruct>`.  GUIDs are a 128-bit value, so it doesn't look like there's a built-in type that this can alias to without losing information (without resorting to strings).  Do you have any recommendations on how to handle this?

**Comment by chwarr** [comment]
`gbc` [checks](https://github.com/Microsoft/bond/blob/6b5060c3a639b2f682d242a531b20b74790c668d/compiler/src/Language/Bond/Parser.hs#L308) that the key type of a map [is a scalar](https://github.com/Microsoft/bond/blob/abfb3a7dffbcabe78888a569f28f78417c932315/compiler/src/Language/Bond/Syntax/Util.hs#L49), so you're going to have to alias to a scalar type. And, yes, unfortunately, strings will double (more-or-less, which protocol is being used matters) the size of your GUIDs.

Issue #133 tracks support for 128-bit integer types, which would a space efficient way to represent GUIDs.
