### ISSUE TITLE
Making a current class Bond-compatible (vis-a-vis protobuf-net Decorators)

### ISSUE THREAD

**Issue by BrutalSimplicity** [Microsoft/bond#134]
I just learned about Bond about 30 minutes before this post, so please forgive me if this question seems ill-informed. I've spent the last month learning about Google's protocol buffers and ended up beginning to translate a fairly complex class structure to take advantage of protocol buffers using the protobuf-net library.

My question is - Is it possible to use Bond with current classes that were not originally generated with the gbc?

**Comment by sapek** [comment]
If you are asking about C# then yes. 

You can annotate your classes with Bond [attributes](https://microsoft.github.io/bond/manual/bond_cs.html#attributes). You may also want to read about [type aliases](https://microsoft.github.io/bond/manual/bond_cs.html#custom-type-mappings) if you are using some types that are not supported by default.

The same is also possible for C++, however you would need to write more code, equivalent of what `gbc` generates in [*_reflection.h files](https://github.com/Microsoft/bond/blob/master/compiler/tests/generated/basic_types_reflection.h).

**Comment by BrutalSimplicity** [comment]
Yep C#, that answers my question clearly. Thank you very much.
