### ISSUE TITLE
gbc should output more structured error messages

### ISSUE THREAD

**Issue by chwarr** [Microsoft/bond#136]
The error messages from gbc should be more structured so that tools like Visual Studio/Emacs/whathaveyou can provide quick navigation to errors.

MSBuild and Visual Studio support [this format](http://blogs.msdn.com/b/msbuild/archive/2006/11/03/msbuild-visual-studio-aware-error-messages-and-message-formats.aspx).

**Comment by tstein** [comment]
This is implemented in comm (bcb36cc). Leaving this open until we get that merged into master.

**Comment by tstein** [comment]
bcb36cc has been merged into master.
