### ISSUE TITLE
Failed to build on Win8.1 + VS2013

### ISSUE THREAD

**Issue by bigheadzen** [Microsoft/bond#14]
I'm trying to build it myself, but met following error.

##############################################################
2>------ Build started: Project: compiler, Configuration: Debug Win32 ------
3>------ Build started: Project: bond_unit_test_main, Configuration: Debug Win32 ------
3>  Building Custom Rule D:/repos/bond/cpp/test/core/CMakeLists.txt
3>  CMake does not need to re-run because D:\repos\bond.build\cpp\test\core\CMakeFiles\generate.stamp is up-to-date.
3>  main.cpp
2>  Building Custom Rule D:/repos/bond/compiler/CMakeLists.txt
2>  CMake does not need to re-run because D:\repos\bond.build\compiler\CMakeFiles\generate.stamp is up-to-date.
2>  Generating D:/repos/bond/compiler/cabal.sandbox.config
2>  Writing a default package environment file to
2>  
2>  D:\repos\bond\compiler\cabal.sandbox.config
2>  
2>  Using an existing sandbox located at D:\repos\bond\compiler\.cabal-sandbox
2>  
2>  Generating build/gbc/gbc.exe
2>  Resolving dependencies...
2>  
2>  Notice: installing into a sandbox located at
2>  
2>  D:\repos\bond\compiler\.cabal-sandbox
2>  
2>  Downloading aeson-0.7.0.6...
2>  
2>  cabal.exe: mallocPlainForeignPtrBytes: size must be >= 0
2>  Resolving dependencies...
2>  
2>  Configuring gbc-3.0.2.0...
2>  
2>  cabal.exe: At least the following dependencies are missing:
2>  
2>  shakespeare >=2.0
2>  
2>  Package has never been configured. Configuring with default flags. If this
2>  
2>  fails, please run configure manually.
2>  
2>  Resolving dependencies...
2>  
2>  Configuring gbc-3.0.2.0...
2>  
2>  cabal.exe: At least the following dependencies are missing:
2>  
2>  shakespeare >=2.0
2>  
2>  Generating gbc.comp
2>  'build\gbc\gbc.exe' is not recognized as an internal or external command,
################################################################

It seems to be cabal failed to install shakespear. So I tried to install shakespeare manually. However, it failed again.

##########################################
D:\repos\bond.build>cabal install shakespeare
Resolving dependencies...
Downloading text-1.2.0.4...
Configuring exceptions-0.6.1...
Configuring dlist-0.7.1...
Configuring text-1.2.0.4...
Building exceptions-0.6.1...
Building dlist-0.7.1...
Building text-1.2.0.4...
Installed dlist-0.7.1
Installed exceptions-0.6.1
Installed text-1.2.0.4
Downloading hashable-1.2.3.1...
Downloading parsec-3.1.8...
Configuring system-filepath-0.4.13.1...
Configuring blaze-builder-0.3.3.4...
Configuring hashable-1.2.3.1...
Configuring parsec-3.1.8...
Building blaze-builder-0.3.3.4...
Building hashable-1.2.3.1...
Building parsec-3.1.8...
Building system-filepath-0.4.13.1...
Installed hashable-1.2.3.1
Downloading unordered-containers-0.2.5.1...
Configuring scientific-0.3.3.5...
Building scientific-0.3.3.5...
Installed blaze-builder-0.3.3.4
Configuring blaze-markup-0.6.2.0...
Building blaze-markup-0.6.2.0...
cabal: mallocPlainForeignPtrBytes: size must be >= 0
##############################################

Env:
Win8.1
VS 2013
Boost 1.57
Python 2.7.6
Haskell 2014.2.0.0-x86_64
Cabal-install 1.18.0.5

Anyone has same issues?

**Comment by sapek** [comment]
Are you behind a proxy? There is a [bug](https://github.com/haskell/HTTP/issues/72) in HTTP library that Cabal is using and it fails to discover proxy setting on Win8.

There is a simple workaround:

    set HTTP_PROXY=http://proxy:port

where `proxy` and `port` correct settings for your network.

If you are no behind proxy, it might also be caused by some [network/server issues](http://www.reddit.com/r/haskell/comments/2siokx/haskellorg_takes_forever_to_load_anybody_else/) with haskell.org had today that caused it to be very slow. Try again tomorrow.

**Comment by bigheadzen** [comment]
@sapek  Thanks a lot. It works. Sorry for missing this info in Readme.
