### ISSUE TITLE
Request: Support attributes on Enum members C#

### ISSUE THREAD

**Issue by chandramouleswaran** [Microsoft/bond#144]
We would like support added to the bond schema for attributes on top of Enum and member values

    [Summary("Gives the state of the Bank account")]
    [System.Runtime.Serialization.DataContract("Namespace = Namespaces.Bank")]
    enum State
    {
        [Summary("Default value. Nothing has been done yet.")]
        [System.Runtime.Serialization.EnumMember()]
        Unknown = 0,       

        [Summary("Means that the account is opened")]
        [System.Runtime.Serialization.EnumMember()]
        Opened = 1,
    }

Currently, we are using WCF and we would like to move towards Bond. In the mean time, we wanted the ability to convert Bond schema to data contracts as well. We have a custom attributes converter that we are using to do the same. Supporting attributes on Enum members will be ideal for services to move to the Bond world.

**Comment by chwarr** [comment]
Support for Bond attributes on enum members is issue #138.

But, I think that you're asking for the generated C# code to be able to contain arbitrary C# attributes, not just [Bond attributes](https://microsoft.github.io/bond/manual/compiler.html#custom-attributes) (which end up in C# as [`Bond.AttributeAttribute`](https://microsoft.github.io/bond/manual/bond_cs.html#attributeattribute)).

Am I understanding this correctly?

You can, today, write this in a .bond file:

```
[System.Runtime.Serialization.DataContract("Namespace = Namespaces.Bank")]
enum State
{
   ...
}
```

and it will generate C# code like:

```
    [global::Bond.Attribute("System.Runtime.Serialization.DataContract", "Namespace = Namespaces.Bank")]
    [System.CodeDom.Compiler.GeneratedCode("gbc", "0.4.0.1")]
    public enum State
    {
        ...
    }
```

But notice that `System.Runtime.Serialization.DataContract` is just a string.

**Comment by chandramouleswaran** [comment]
Same as issue #138 - you can close this if you want. I will track #138.
Yes - you are right. The value is a string - we had our own converter which converted Bond.Attributes to actual attributes in our own targets file.
