### ISSUE TITLE
JSON serialization for nullable containers

### ISSUE THREAD

**Issue by bdangh** [Microsoft/bond#148]
Is there any particular reason for wrapping nullable containers inside of array when deserializing /serializing from/to JSON?

This is blocker for creating a schema which can parse existing JSON structure.

**Comment by chwarr** [comment]
In the Bond, `nullable<T>` is represented in serialized payloads identically to `list<T>` for all serialization protocols. At the serialization/deserialization level, this is an elegant, protocol-agnostic way to encode presence/absence of a value. In hindsight, was this perhaps a poor choice five years ago? That's debatable. Can it be changed in the protocols we have today? Nope: that would break a ton of existing serialized data.

Another thing to remember: Bond's Simple JSON protocol isn't intended to parse existing, arbitrary JSON structures. The goal with the Simple JSON protocol is to use valid JSON that is _relatively_ easy to work with using other JSON libraries. However, the goal is not to output fully idiomatic JSON or to be an arbitrary JSON serialization/deserialization library: other libraries already have that covered. Bond focuses more on the efficient manipulation of schematized data across languages and formats.

To parse your existing JSON structures, you could either transform them into JSON that the Simple JSON protocol expects or implement your own [parser](https://microsoft.github.io/bond/manual/bond_cs.html#protocol-decoration)/[transform](https://microsoft.github.io/bond/manual/bond_cpp.html#transforms). Issue #100 tracks the need to have a customer transform example to make solving this sort of problem more accessible to more people.

Hope this helps.

**Comment by bdangh** [comment]
Thanks for detailed answer, I used custom contract resolver for JSON.NET to deserialize JSON and then Bond's binary serializer to wire it to the backend. Though, I'm not sure about performance of this solution.
