### ISSUE TITLE
Add the ability to serialize byte array into blob field

### ISSUE THREAD

**Issue by xplicit** [Microsoft/bond#15]
Currently, Bond library requires to use `ArraySegment<byte>` in objects to serialize bytes into blobs. If I use byte array `byte []` serializer/desirializer uses algorithm for Lists to serialize/desirialize the array. This is significally slower than using `Buffer.BlockCopy`, which is used for ArraySegment.

if I add an explicity declaration to use a blob for byte array

		[global::Bond.Id(0), global::Bond.Type(typeof(global::Bond.Tag.blob))]
		public byte[] Arr { get; set; }

Then I'll get an exception, `System.ArgumentException : Instance property 'Array' is not defined for type 'System.Byte[]'`

It would be nice if byte arrays serializes into blobs by default.

**Comment by xplicit** [comment]
The code

			var output = new OutputBuffer();
			var writer = new CompactBinaryWriter<OutputBuffer>(output);

			var ser = new Serializer<CompactBinaryWriter<OutputBuffer>> (typeof(ByteArray64K));
			var deser = new Deserializer<CompactBinaryReader<InputBuffer>>(typeof(ByteArray64K));
			var arr = ByteArray64K.Create();

			ser.Serialize (arr, writer);

			var input = new InputBuffer(output.Data);
			var reader = new CompactBinaryReader<InputBuffer>(input);

			var des = deser.Deserialize<ByteArray64K>(reader);

**Comment by sapek** [comment]
You can achieve this by defining a [converter](http://microsoft.github.io/bond/manual/bond_cs.html#converter) between `ArraySegment<byte>` and `byte[]`:

    public static class BondTypeAliasConverter
    {
        public static byte[] Convert(ArraySegment<byte> value, byte[] unused)
        {
            var arr = new byte[value.Count];
            Buffer.BlockCopy(value.Array, value.Offset, arr, 0, value.Count);
            return arr;
        }

        public static ArraySegment<byte> Convert(byte[] value, ArraySegment<byte> unused)
        {
            return new ArraySegment<byte>(value);
        }
    }

BTW, we use `ArraySegment<byte>` to represent `blob` because this allows us to avoid BlockCopy during deserialization. It is potentially big performance win.

**Comment by xplicit** [comment]
If it does not copy the original source how does it prevent data from corruption? For example, this code, when we reuse writer and reader

			var output = new OutputBuffer();
			var writer = new CompactBinaryWriter<OutputBuffer>(output);

			var ser = new Serializer<CompactBinaryWriter<OutputBuffer>> (typeof(ArraySegment64K));
			var deser = new Deserializer<CompactBinaryReader<InputBuffer>>(typeof(ArraySegment64K));
			var arr = ArraySegment64K.Create(100); //Fill array with random data, seed=100
			var arr1 = ArraySegment64K.Create(200); //Fill array with random data, seed=200

			ser.Serialize (arr, writer);

			var input = new InputBuffer(output.Data);
			var reader = new CompactBinaryReader<InputBuffer>(input);

			input.Position = 0;
			des1 = deser.Deserialize<ArraySegment64K>(reader);

**Comment by xplicit** [comment]
I think the code you've provided (or something like that) should be included in the Bond library by default for `byte[]` type. It increases performace alot. And `byte[]` type should be serialized into blob by default (I mean not to change gbc behaviour or generating `byte[]` instead of ArraySegment<>, but just serialize into blob if someone marks `byte[]` property in the object with Bond.Id() property) Here the benchmarks I've done for arrays of bytes with length 4096 and 65536.

Look at the last one number it shows number of operations per second. (Other show time in ms).

With your conversion and serialization into blob.

      DeserializeByteArray4KStream => *********** Mean=286.62, Min=264.58, Max=333.70, StdDev=18.59, StdErr=2.05%, Ops=348897.44
     SerializeByteArray4KStream => *********** Mean=60.01, Min=56.40, Max=69.60, StdDev=4.34, StdErr=2.29%, Ops=1666422.26
     DeserializeByteArray64KStream => *********** Mean=807.96, Min=771.45, Max=837.25, StdDev=17.66, StdErr=0.69%, Ops=12376.86
     SerializeByteArray64KStream => *********** Mean=74.43, Min=67.62, Max=82.21, StdDev=5.95, StdErr=2.53%, Ops=134361.09

Without your conversion and default serialization into vector

      DeserializeByteArray4KStream => *********** Mean=7133.24, Min=6880.58, Max=7324.69, StdDev=133.23, StdErr=0.59%, Ops=14018.87
      SerializeByteArray4KStream => *********** Mean=5236.34, Min=5144.72, Max=5409.07, StdDev=77.71, StdErr=0.47%, Ops=19097.30
      DeserializeByteArray64KStream => *********** Mean=11564.93, Min=11447.92, Max=11699.22, StdDev=86.53, StdErr=0.24%, Ops=864.68
      SerializeByteArray64KStream => *********** Mean=8438.93, Min=8264.64, Max=8624.70, StdDev=92.87, StdErr=0.35%, Ops=1184.98

Difference in speed is more than 10 times for desirialization and 100 times for serialization.
I've tested it with mono 3.12 on linux machine, so .NET results may differ, but I think they should be similar.

The source code of benchmarks is available at http://github.com/xplicit/SerializersBenchmarks

example of serialization array of 64K
https://github.com/xplicit/SerializersBenchmarks/blob/master/BondBench/Templates/ArraysBench.cs#L83
 
Seriazlied type:
https://github.com/xplicit/SerializersBenchmarks/blob/master/SerializersBenchmarks/Objects/ByteArray64K.cs

**Comment by sapek** [comment]
Please take a look at #16. This commits optimizes handling of `byte[]` w/o any type annotation. It doesn't however treat `byte[]` as `blob`, it is still treated as BT_LIST of BT_UINT8 (see the commit message for more details).

**Comment by xplicit** [comment]
I've checked new version for  performance of Serializing/Deserializing byte arrays and can confirm: now performance is comparable to `blob` serialization using converter.

**Comment by sapek** [comment]
Thanks for verifying. I uploaded updated package to nuget.org.
