### ISSUE TITLE
More verbose python example documentation?

### ISSUE THREAD

**Issue by astewart-twist** [Microsoft/bond#156]
In reading https://microsoft.github.io/bond/manual/bond_py.html#basic-example, could you possibly provide a bit more detail for readers not familiar with writing python extensions?  In particular, what is supposed to happen between here....

> ```
> gbc c++ example.bond
> ```
> With the generated C++ code (example_reflection.h in this case) implementing the Python extension is as simple as specifying which structs we want to expose to Python:
> ```
> #include "example_reflection.h"
> #include <bond/python/struct.h>
> 
> BOOST_PYTHON_MODULE(example)
> {
>     bond::python::struct_<example::Record>()
>         .def();
> }
> ```

...and here?  What should the name of the file be for the above code block (containing the `BOOST_PYTHON_MODULE`)?  And what then is needed to be done so that the python module can actually be imported in the code block below? 

> Finally, we can import the extension as a module that can be used in a Python program:
> ```
>     import example
> 
>     src = example.Record()
> 
>     src.name = "test"
>     src.items = [3.14, 6.28]
> 
>     data = example.Serialize(src)
> 
>     dst = example.Record()
>     example.Deserialize(data, dst)
> ```

Thanks.

**Comment by sapek** [comment]
There is a simple Python extension [example project](https://github.com/Microsoft/bond/tree/master/examples/python/core/extension) that may help. You can also take a look at the Python [test projects](https://github.com/Microsoft/bond/tree/master/python/test).

**Comment by astewart-twist** [comment]
Thanks @sapek.  It's not the example code that is lacking but rather the command line processes for successfully compiling a python extension that can be imported into a python script.

**Comment by sapek** [comment]
That is platform specific. In Bond we use CMake to handle [building Python modules](https://github.com/Microsoft/bond/blob/ac76e546ae0a6753a8f8defb76280e3610eff4f3/cmake/Bond.cmake#L126). It does a decent job abstracting platform differences.

Bond Python modules are just Boost Python modules so [Boost documentation](http://www.boost.org/doc/libs/1_60_0/libs/python/doc/html/building.html) is fully applicable.

**Comment by chwarr** [comment]
I'm going to close this issue, as it's been sitting here for a month now. Please re-open it if there's more that is needed. Thank.
