### ISSUE TITLE
Resolving polymorphism is slow

### ISSUE THREAD

**Issue by felixhao28** [Microsoft/bond#157]
Suppose I have `struct A: B`, and I want to resolve instance of Xapbonded<A> to a B instace. I will call Xapbonded\<A\>.Cast\<B\>().Value. And that single call becomes the bottleneck of the performance.

After looking into the source, I found that you are using reflection. Though you wrote the reason in comments, I am sure we can come up a solution without involving the slow reflection. Yes?

**Comment by felixhao28** [comment]
In addition, I accidentally found out that you can use `struct K;` to define symbol K without implementing it. So that we can do a circular reference like this (just like in C):

```
struct K;

struct S
{
  0: K item;
}

struct K
{
  0: S item;
}
```

I think this kind of usage is worth mentioning somewhere in the document.

**Comment by sapek** [comment]
I don't understand what you are referring to in your first comment. Could you add [links](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#links) to Bond code you are talking about?

BTW, the example in your second comment is not legal (`gbc` should barf). To defined a [recursive schema](https://github.com/Microsoft/bond/blob/master/examples/cpp/core/generic_tree/generic_tree.bond) you have to use `nullable`.

**Comment by chwarr** [comment]
`gbc` accepts the mutually recursive schema and generates invalid C++ code. Opened #159 for this issue.

**Comment by felixhao28** [comment]
Sorry I was wrong about the reflection issue. It seems we are using an internal framework(XAP) which is offering wrappers for bonded data types (and I guess that's why they are using reflection to referencing generated bond class methods).

And thank you for providing the example. Let's follow that up in our internal SO.
