### ISSUE TITLE
UWP Support?

### ISSUE THREAD

**Issue by Redbolts** [Microsoft/bond#163]
Is Bond supported for UWP apps? If not, any plans to add support?

**Comment by chwarr** [comment]
@lalo is looking into this. Bond.dll doesn't use any APIs that aren't part of UWP (Windows 10+), but Compact Binary deserialization is throwing an exception. I can't remember the exact exception right now, but it had something to do with converting from `System.Int32` to `Bond.BondDataType&` when calling `ReadFieldBegin`.

@sapek _might_ have run into this issue before when he was debugging some .NET Native stuff.

**Comment by sapek** [comment]
It looks like dotnet/corefx#3007.

**Comment by lalo** [comment]
Still getting the exception with Microsoft.NetCore.UniversalWindowsPlatform 5.2.2 (latest version to this day)

**Comment by Redbolts** [comment]
Is this a question? I just tried the bond blob core example using 5.2.2 and got the same error at the line 
var dst = Deserialize<Example>.From(reader); 

ArgumentException: Object of type 'System.Int32' cannot be converted to type 'Bond.BondDataType&'.

So it would appear the issue remains?

**Comment by lalo** [comment]
Not a question, I was updating the status with the latest version of NetCore. Sorry for the confusion.

**Comment by chwarr** [comment]
When targeting Windows 10 Fall Creators Update (10.0; Build 16299), Bond now works. I tested with a C# XAML UWP application. None of the earlier target platforms that I tested worked.
