### ISSUE TITLE
Need CoreCLR compliant version

### ISSUE THREAD

**Issue by hrushib** [Microsoft/bond#165]
Is there CoreCLR compliant version of Microsoft.Bond ?  If not what are plans around making it available?

**Comment by sapek** [comment]
It is in the [Nuget](https://github.com/Microsoft/bond/blob/6a33bb85c1393e015a933f72980a9676afd43456/cs/nuget/bond.core.csharp.nuspec#L35-L40). Note that Bond.IO is not CoreCLR but it is an optional assembly that contains streams optimized slightly via unsafe code.

**Comment by chwarr** [comment]
I tested Bond against Core CLR a few months ago using the Bond.IO.Safe classes. All was well.

When Core CLR settles down some more, we'll figure out a way to get it into our automatic build matrix. Opened #166, "Add CoreCLR to build/test matrix", for this.

**Comment by chwarr** [comment]
See PR #264 for more complete .NET Core support

**Comment by chwarr** [comment]
The version just released, 5.1.0, includes .NET Core support via .NET Standard 1.0, 1.3, or 1.6.
