### ISSUE TITLE
Add CoreCLR to build/test matrix

### ISSUE THREAD

**Issue by chwarr** [Microsoft/bond#166]
Bond needs to support CoreCLR, so CoreCLR-based builds and tests need to be added to the Travis and AppVeyor build matrices.

Note that not all features of Bond need to work on CoreCLR (e.g., unsafe IO).

**Comment by jterry75** [comment]
Will this include updating the nupkg to support `dotnet5.4` or `netstandard1.3`? I would love to be able to use `dotnet build` for a `netcoreapp1.0` and have it not hate me for having a dependency on `Bond.CSharp`.

As FYI the reason I am doing this is for ASP.NET Core using bond schemas as the transport types.

**Comment by chwarr** [comment]
Maybe. Not all of the details have been figured out.

Later today or on Thursday we'll be publishing finer grained packages that split gbc out from Bond.CSharp, which might also solve your problem.

**Comment by jterry75** [comment]
Actually. I was wrong anyways. On second thought I forgot about how they changed PCL imports for project.json files (everything is still changing). This works for a cross compiled .NET 4.6 and NETCoreApp. 

```js
{
  "version": "1.0.0-*",
  "description": "",
  "dependencies": {
    "Bond.CSharp": "4.2.0"
  },
  "frameworks": {
    "net46": {
        "dependencies": {
            "System.Runtime": "4.0.20"
        }
    },
    "dotnet5.4": {
      "imports": [
        "portable-dnxcore50+net45+win8+wp8+wpa81"
      ],
      "dependencies": {
        "System.Diagnostics.Tools": "4.0.1-beta-23516",
        "System.Collections": "4.0.11-beta-23516",
        "System.Runtime": "4.0.21-beta-23516"
      }
    }
  }
}
```

**Comment by chwarr** [comment]
Good to hear.

**Comment by sqmgh** [comment]
You mention that not all features need to work with CoreCLR. Specifically stating unsafe i/o. However, currently OutputStream and InputStream only seem to exist in Bond.IO.Unsafe, and currently don't seem to be included when you try and pull things into a CoreCLR project.
Is this something that is going to change? Taking a very quick peek at the code doesn't reveal anything that _looks_ unsafe.

**Comment by chwarr** [comment]
I've gotten most of Unsafe IO to compile against CoreCLR when allowing unsafe code. However, we'd need to split out the [native methods in stream cloning](https://github.com/Microsoft/bond/blob/6a33bb85c1393e015a933f72980a9676afd43456/cs/src/io/unsafe/StreamCloning.cs#L116) in such a way that we can have different implementations for the various platforms. As currently written, stream cloning will only work on Windows.

**Comment by sqmgh** [comment]
Ahh, I had not dug that deep. As long as it's on the radar, and not something that is going to be dropped that's fine with me!

**Comment by stankovski** [comment]
@chwarr any updates on CoreCLR support?

**Comment by chwarr** [comment]
Nothing to report at the moment. .NET Core looks like it is settling down, so we'll want to revisit this.

**Comment by chwarr** [comment]
See PR #264 for more complete .NET Core support forthcoming.
