### ISSUE TITLE
How can we write c# Xml Documentation comments in Bond file

### ISSUE THREAD

**Issue by guotuofeng** [Microsoft/bond#168]
Hi, there 

is it possible to write the c# Xml Documentation in bond file? so that GBC can generate the xml document (start with "///") in the generated cs file?

Thanks,
-Mike Guo

**Comment by chwarr** [comment]
No, there's no way write documentation in .bond files that make it into the generated code currently.

[Version 0.4.0.2 of gbc](https://github.com/Microsoft/bond/blob/master/CHANGELOG.md#410-2016-04-22) emits `#pragma warning disable 1591'

Some related issues #82, #121, and #170.

**Comment by chwarr** [comment]
I'm going to close this issue now. Please feel free to re-open if there's anything more.

**Comment by YanlongLi** [comment]
It will be nice to have if the documentation can be included in generated code.
