### ISSUE TITLE
C++ Cant serialize Box of type defined in static library

### ISSUE THREAD

**Issue by acgull** [Microsoft/bond#169]
In the example given in "static_library" project, instead of trying to serialize `MyStruct` I serialize `Box<MyStruct>`.

```cpp
    MyStruct obj;

    // Initialize
    obj.items.resize(1);
    obj.items[0].numbers.push_back(13);

    Item item;

    item.numbers.push_back(11);
    obj.item = bond::bonded<Item>(item);
    bond::Box<MyStruct> box;
    box.value = obj;
    // Serialize
    bond::OutputBuffer buffer;
    bond::CompactBinaryWriter<bond::OutputBuffer> writer(buffer);
    bond::Serialize(box, writer);
```

Build fails - it looks like bond thinks that `MyStruct` is not a bond type.
If I do the same thing without the static library, but with reflection everything works fine.

What am I doing wrong?

**Comment by chadwalters** [comment]
Does including static_library_reflection.h resolve your issue?

**Comment by acgull** [comment]
Yes, including static_library_reflection.h works, but I would to use static_library_apply.h because I don't want compilation to take forever..

**Comment by chadwalters** [comment]
Apologies for the slow response. Using including the reflection header is required in this case for instantiating Box<T> -> Box<MyStruct> but shouldn't prevent you from getting compile time advantages from the apply header. Closing for now but please reopen if you are seeing significant compile time degradation.
