### ISSUE TITLE
Microsoft.Bond should support netstandard for the CoreCLR in the nuspec

### ISSUE THREAD

**Issue by jterry75** [Microsoft/bond#171]
Creating an issue so we can track the work here.

The nupkg should be enhanced to support the current PCL target as a `netstandard` TFM for `dotnet CLI` as a first-party so that we don't have to do the manual PCL includes from other target imports.

IE: A consumer of the project should be able to write a spec like:

``` js
{
  "version": "1.0.0-*",
  "description": "",
  "dependencies": {
    "Bond.CSharp": "4.2.0"
  },
  "frameworks": {
    "net46": {
        "dependencies": {
            "System.Runtime": "4.0.20"
        }
    },
    "netcoreapp1.0": {
      "dependencies": {
        "System.Diagnostics.Tools": "4.0.1-beta-23516",
        "System.Collections": "4.0.11-beta-23516",
        "System.Runtime": "4.0.21-beta-23516"
      }
    }
  }
}
```

Whereas today a consumer must directly import the PCL for netcore:

``` js
{
  "version": "1.0.0-*",
  "description": "",
  "dependencies": {
    "Bond.CSharp": "4.2.0"
  },
  "frameworks": {
    "net46": {
        "dependencies": {
            "System.Runtime": "4.0.20"
        }
    },
    "dotnet5.4": {
      "imports": [
        "portable-dnxcore50+net45+win8+wp8+wpa81"
      ],
      "dependencies": {
        "System.Diagnostics.Tools": "4.0.1-beta-23516",
        "System.Collections": "4.0.11-beta-23516",
        "System.Runtime": "4.0.21-beta-23516"
      }
    }
  }
}
```

**Comment by jterry75** [comment]
@chwarr - I will work on this and send up a PR (not sure if you can assign to me outside the repo or not)

**Comment by chwarr** [comment]
Nope. Can't assign it. Go for it though.

**Comment by csdahlberg** [comment]
Anything new with this? We would also be interested in NETStandard support for some upcoming work.

At first glance it looks like Profile78 is equivalent to NETStandard 1.0, and replacing `portable-net45+wp80+win8+wpa81+dnxcore50` with `netstandard1.0` in the .nuspec files might be all that is needed. If so, I could submit a quick PR with that change.

**Comment by chwarr** [comment]
No, I haven't had time to look into this yet myself. Please feel free to submit a PR if you have something working.

**Comment by chwarr** [comment]
See also PR #264  which adds more complete .NET Core support.
