### ISSUE TITLE
No programmatic access for default values specified in bond files from compiled C#

### ISSUE THREAD

**Issue by brphelps** [Microsoft/bond#173]
Generated C# classes have significant assumptions about how default values will be used (i.e. only needing to be filled in a constructor). Ideally, these values would be represented as a special attribute on the appropriate property in addition to whatever functionality exists today.

I don't mind getting a PR out for this issue as soon as the issue gets some measure of approval from owners :).

**Comment by sapek** [comment]
[Here's](https://github.com/Microsoft/bond/blob/2885cc3fe816105e07c9d45ef5939f2dea3e9c60/cs/src/core/Reflection.cs#L903) how Bond internally accesses the default values in a programmatic way.

**Comment by brphelps** [comment]
@sapek -- This seems a bit more convoluted than just having the information present in a declarative way. What I like about having an attribute declaration is specifically that I don't have to do something convoluted to get the value.

**Comment by sapek** [comment]
If you look at the function I linked you will notice that there already is support for `[Default(value)]` attribute. Currently it is only used for interfaces. This was to avoid mismatch between default value specified in the attribute and the actual default value set by ctor. That would lead to incorrect de/serialization behavior. But an alternative approach would be to always use `[Default]` attribute when present and for classes verify at runtime that the value is the same as the actual default set by ctor.

**Comment by brphelps** [comment]
@sapek  The generated C# should be sourcing the value for default from the same place, right? So the attribute and the constructor content should always match.

**Comment by chwarr** [comment]
Does the default value in the struct's StructDef provide the information you're looking for? ([SchemaDef to StructDef to FieldDef to Metadata](https://github.com/Microsoft/bond/blob/2885cc3fe816105e07c9d45ef5939f2dea3e9c60/cpp/inc/bond/core/bond.bond#L85-120))

Also, can you expand on how you'd use the field's default value if we were able to wave a magic wand and have such an API? That will help ground the discussion.

**Comment by sapek** [comment]
@brphelps, in generated code the attribute and the real default will of course match. But in hand written code, not necessarily.

**Comment by chwarr** [comment]
Having heard nothing more in a week, I'm closing this issue. Please re-open if there are more details. Thanks.
