### ISSUE TITLE
ghc 7.8.4 OS X Travis CI builds are failing

### ISSUE THREAD

**Issue by chwarr** [Microsoft/bond#176]
Our OS X builds using [ghc 7.8.4](https://github.com/Microsoft/bond/blob/dde93cb1621478949f2924761e22c73ee608de24/.travis.yml#L41) have been failing with [timeouts recently](https://travis-ci.org/Microsoft/bond/jobs/136315467). ghc 7.6.3 and 7.4.1 are passing, however.

**Comment by lalo** [comment]
https://travis-ci.org/Microsoft/bond/builds/137432412

Got a successful run by just increasing the timeout.

**Comment by chwarr** [comment]
Good to know that the build isn't stalled. It's a bit interesting that the different ghc versions have such different build times. 7.6.3 takes 4 minutes 23 seconds, but 7.8.4 takes 36 minutes 17 seconds.

I'm hesitant to just up the limit without understanding where the 700% increase in time comes from.

**Comment by lalo** [comment]
7.10.3 also timeouts
https://travis-ci.org/Microsoft/bond/builds/137610412

something fisghcy is going on
