### ISSUE TITLE
Any plan provide Visual Studio extension?

### ISSUE THREAD

**Issue by hcoona** [Microsoft/bond#178]
There are extensions for Visual Studio Code & Atom, but no one for Visual Studio.

**Comment by chwarr** [comment]
The core Bond team doesn't have a VS extension on our roadmap. All the previous editor extensions have been contributed by users of the various editors, so if you have something useful yourself, could you start a pull request to get it merged in?

**Comment by lalo** [comment]
Language integration sample in case anyone wants a lead on this task:

https://github.com/Microsoft/VSSDK-Extensibility-Samples/tree/master/Ook_Language_Integration

**Comment by chwarr** [comment]
I'm going to close this issue for now. Please re-open if there's more to this question.

If you want to implement an add-in, please create a new issue for the design of that specifically.
