### ISSUE TITLE
C# performance issues when targeting x64 instead of x86

### ISSUE THREAD

**Issue by NilsBarlaug** [Microsoft/bond#185]
I was hoping to see big improvements in performance by only deserializing a single bonded element in a collection, update this element and serialize the collection. Instead of deserializing the whole collection, update a single element and serialize the collection.

I have quite complex objects, so there should be big potential for speedup by skipping some of the serialization and deserialization. I get a significant speedup on deserialization, but not on the serialization - unless I target x86.

Running [this code](https://gist.github.com/NilsBarlaug/b9992d5d84eab883a176e0b3c408c871) takes **25 seconds** targeting **x86** and **75 seconds(!)** targeting **x64** on my local machine.

If I don't wrap the elements in the collection with Bonded there is no significant performance difference between x64 and x86 (x64 is a bit faster).

Here is the hot path from CPU sampling if it's any help. (x64 on the left and x86 on the right)
![Profiling screenshot](https://cloud.githubusercontent.com/assets/6547094/16231851/58977cec-37c8-11e6-8449-0a173d8ef19a.PNG)

Any idea of why this is?

**Comment by NilsBarlaug** [comment]
Quick update:

@lalo thought there might be some optimization problems and pointed out that the byte array access [on line 86 in Bond.IO.Safe.InputBuffer](https://github.com/Microsoft/bond/blob/master/cs/src/core/io/safe/InputBuffer.cs#L86) is much slower on x64.
Since the IL are the same for x86 and x64 there must be something going on when JIT-compiling to native code. So I had a look at the native code produced for the ReadUInt8() method.
![readuint8_net45](https://cloud.githubusercontent.com/assets/6547094/16305870/f696fac8-395b-11e6-9392-79aa5b9335b0.PNG)
(x86 on the left and x64 on the right)

It seems like the x86 native code for the byte array access (see the last block) are better optimized than the x64 native code, which have unnecessary jumps and moves.

I'm targeting .NET 4.5. Trying .NET 4.6.1 (with the same code) reduces the difference between x86 and x64.
![stats](https://cloud.githubusercontent.com/assets/6547094/16306543/5a46ea72-395e-11e6-91cc-40c8fea38d10.PNG)
(Iterations on the x-axis and time in milliseconds on the y-axis).

Clearly better startup cost and smaller constant factor away from x86. Checking out the native code again verifies that the optimizer does a better job.
![readuint8_net461](https://cloud.githubusercontent.com/assets/6547094/16306632/9ff48b60-395e-11e6-94c0-841b9692f6c6.PNG)

So it could be the case that x64 doesn't optimize the code as well as x86, but that it's getting better.

**Comment by lalo** [comment]
Closing this issue since there was a drastic improvement on the later version of .NET 4.6.1
