### ISSUE TITLE
Runtime serializer can't handle Bonded<> types

### ISSUE THREAD

**Issue by mserd** [Microsoft/bond#188]
If you have a type defined as:

```
class A
{
    Bonded<int> x;
}
```

The x cannot be serialized. I traced it in the code and found in `Reflection.IsBonded()`:

```
return definition == typeof(IBonded<>) || definition == typeof(Tag.bonded<>);
```

That test for `typeof(IBonded<>)` will always fail since definition is going to be the instantiation of an object. Instead it should do:

```return definition.GetInterfaces().Contains(typeof(IBonded))```

I'm unsure of what the test for `typeof(Tag.bonded<>)` is for. `Tag.bonded<>` is an abstract class that does not hold the underlying type being bonded. Classes that override `Tag.bonded<>` will also fail that test (`definition == typeof(Tag.bonded<>`).

**Comment by sapek** [comment]
Bond type `bonded<T>` in C# maps to `Bond.IBonded<T>`. `Bond.Bonded<T>` is a implementation. Also `T` can be only a type representing a Bond schema (i.e. `int` is not valid).

BTW, if you are manually writing C# classes to use with Bond and something doesn't seem to work then a good way to diagnose is to run Bond codegen and review the generated classes.

**Comment by chwarr** [comment]
Additionally, [`Bonded<T>`](https://github.com/Microsoft/bond/blob/0b71900e2f57b9894e1c8671f8f24e4b878ecdf8/cs/src/core/Bonded.cs#L52) is just _one_ of the implementations. There's also [`Bonded<T, R>`](https://github.com/Microsoft/bond/blob/0b71900e2f57b9894e1c8671f8f24e4b878ecdf8/cs/src/core/Bonded.cs#L97). `Bonded<T, R>` is the implementation that get used during deserialization.

So, a type like
```
class A
{
    [Id(...)]
    public Bonded<SomeOtherBondStruct> x;
}
```
wouldn't be able to be deserialized, as `Bonded<SomeOtherBondStruct, R>` isn't assignable to a field of type `Bonded<SomeOtherBondStruct>`. We need `IBonded<T>` here.

(I'm ignoring customizations of Bonded at the moment.)

**Comment by chwarr** [comment]
Also, gbc rejects the following:

```
struct foo
{
    0: bonded<int> bar;
}
```
with ".\foo.bond(5,18) : error B0000: unexpected ">", expecting user defined struct, Unknown symbol: int"

**Comment by mserd** [comment]
I think I get what you're saying. I can have a `Bonded<SomeStruct>` as long as I'm writing it to an `IBonded<SomeStruct>` in the C# class definition. I'll test this out and close this issue if it works.

**Comment by mserd** [comment]
I verified that this wasn't the cause of my issue. Thanks!
