### ISSUE TITLE
Bond python should support type alias with custom type

### ISSUE THREAD

**Issue by acgull** [Microsoft/bond#192]
e.g. In the static_array example, one of the fields is a `std::array`, bond python considers this a regular container and tries to expose it using regular container methods like `insert`, `erase`, `push_back`, and this fails because these methods do not exist in `std::array`.

It is not hard to write an array_indexing suite and add it to bond python, but a better approach is probably to allow the user to specify their own custom `schema_fields_visitor` class which will be a template parameter of `struct_` with a default to the given `schema_fields_visitor`.

This way the user can add any custom type, and expose it to python.

**Comment by sapek** [comment]
What is the scenario for exposing custom C++ types to Python?

**Comment by acgull** [comment]
In my scenario my struct has a `std::array`, which I accomplish by following the directions in the example static_array.
I don't know of another scenario that will have a different struct, but I think that bond should allow for it.

**Comment by sapek** [comment]
Why are you mapping `std::array` when generating C++ code to be used to build a Python module? You can use a .bond file with type aliases w/o doing custom type mapping. In that case the generated code will have the aliased type (`std::vector` in your case). 

Mapping a custom C++ type is obviously useful when you are using the generated code in a C++ program. However when your business logic is written in Python, not C++, why do you even care if the C++ type used to provide the Python mapping was `std::vector`?

**Comment by acgull** [comment]
I am using type alias, but if I try to export it to python it   exports the `std::array` not the underlying `std::vector`, which fails because it is not supported (as I wrote in the original post).

I am using a static array because I want bit to be clear in the interface exactly how many elements there should be.

The business logic is written in C++ but is exposed to python.

**Comment by sapek** [comment]
So you would like the size limit enforced by `std::array` to apply to Python mappings?

It would be possible, I guess, although I'm not sure if it would be very Pythonic. Python doesn't have fixed size arrays, does it?

Note also that Bond type system doesn't have fixed size arrays. Mapping an alias of `vector<T>` to `std::array` doesn't change the fact that from the schema/wire format perspective it is still a variable length list. Thus Bond itself won't enforce the size limit.

**Comment by acgull** [comment]
Yes, I would like the size limit to apply to the Python bindings, if I am not mistaken this is the same thing that happens in numpy arrays, so I don't think it would be too unPythonic.
I am aware that the wire format does not support a fixed size array, but that is fine because the exposed struct does enforce it..

**Comment by grisharav** [comment]
This is relevant for our use case as well, any updates on allowing this?

**Comment by chwarr** [comment]
No work has been done in this area lately, and none is planned by the core Bond team.

**Comment by acgull** [comment]
In the end I specialized `boost::python::container_utils::extend_container` and `boost::python::vector_indexing_suite` for `std::array`
Not the nicest solution (because it assumes that the array will be exported using the `vector_indexing_suite` and this can change in a later release), but it allows to export `std::array` without modifying the existing python export code.
