### ISSUE TITLE
Make the compiler error messages nicer

### ISSUE THREAD

**Issue by ramon-garcia** [microsoft/bond#199]
Hello,

I want to notice that I am developing a fork of this repository to improve the bond compiler. The current compiler shows error  messages quite uninformative. I have lost some time trying to figure out. So I am trying to solve this with an improved parser.

So far, I have changed the engine from Parsec to Megaparsec, which supports error recovery. But I did not implement the improvements. The code passes successfully the compiler test suite.

You can look at my code in https://github.com/ramon-garcia/bond

I will make a pull request when I have something finished.

Best regards.

(If there is a better way of communicating rather than filling an issue, please let me know).

**Comment by chwarr** [comment]
Somewhat related: https://github.com/Microsoft/bond/issues/136, "gbc should output more structured error messages"

Someone from the team will need to take a look. I'll try to find someone and get you some feedback this week.

**Comment by chwarr** [comment]
We've been considering switching parsers to get better error messages, and megaparsec is one that we've looked at. We've also looked a bit at trifecta too.

I'd be very interested to see how you are able to improve the errors.

**Comment by ramon-garcia** [comment]
Thank you. I hope to have at least basic error recovery.

**Comment by chwarr** [comment]
I don't know if you've seen it, but in commit https://github.com/microsoft/bond/commit/5f82bc68b13d92692c0b761864f3cfdccc5882a3 in 2017 we switched to Megaparsec. You originally opened this issue in 2016, which was before the switch.

**Comment by ramon-garcia** [comment]
Thanks. That is why I closed this issue.
