### ISSUE TITLE
gbc cpp generates ambiguous references when a struct and enum val share a name

### ISSUE THREAD

**Issue by tstein** [Microsoft/bond#202]
When compiling a bond file containing a struct and an enum value with the same name, gbc generates C++ that makes unqualified references to that name.

For example, this bond file:

    namespace conflict;
    struct Foo {};
    enum E { Foo; };

builds with the latest master. Trying to compile the resulting conflict_apply.cpp with clang causes a number of errors like this:

```
./conflict_apply.h:28:31: error: reference to 'Foo' is ambiguous
    bool Apply(const bond::To<Foo>& transform,
                              ^
./conflict_types.h:35:12: note: candidate found by name lookup is 'conflict::Foo'
    struct Foo
           ^
./conflict_types.h:97:13: note: candidate found by name lookup is 'conflict::_bond_enumerators::E::E::Foo'
            Foo
            ^
```

**Comment by chwarr** [comment]
Bond version 4.3.0 is now live on NuGet.org. These changes are included in that version.
