### ISSUE TITLE
Support for XML Serialization in C++

### ISSUE THREAD

**Issue by NareshPS** [Microsoft/bond#211]
I am working on a C++ project which uses bond. It should generate an XML which is consumed by a pipeline. I haven't been able to find out any example that serializes Bond into XML. At the moment, I am investigating alternative ways to represent the data. Is there a plan to support XML serialization for bond?

**Comment by chwarr** [comment]
XML in C++ isn't on our roadmap at the moment. Not opposed to it, just not something the Bond team itself is prioritizing.

If you want to [implement an XML protocol for C++](https://github.com/Microsoft/bond/blob/master/CONTRIBUTING.md), take a look at the [C# implementation first](https://microsoft.github.io/bond/manual/bond_cs.html#xml). The two should be compatible with each other.

Also, keep in mind that Bond's goal is to efficiently serialize and deserialize data across languishes and formats. So, there's no need to build a completely flexible XML protocol to support reading and writing arbitrarily shaped XML representations. It needs to output valid XML that other XML readers can understand, but it doesn't need to be able to consume anything other than Bond-flavored XML.
