### ISSUE TITLE
Newtonsoft JSON version 9.0.1

### ISSUE THREAD

**Issue by yagilofir** [Microsoft/bond#212]
Hi, is there a chance you'll upgrade to the latest version of Netonsoft.Json ? (v9.0.1)
We are having some troubles using your json serializer in a .NET project that uses json 9.0.1 (and it seems that Bond currently works with Newtonsoft.Json v7.0.1 which is a bit obsolete.)
Thanks.

**Comment by chwarr** [comment]
We'll need to look at what sort of breaking changes came in version Newtonsoft.Json versions 8 and 9. If it "just" works, we can relax the upper bound, otherwise, some more work will need to be done to make Bond work with 7, 8, and 9.

**Comment by lalo** [comment]
@yagilofir Bond 4.3.0 supports Netonsoft.Json v9.0.1

**Comment by chwarr** [comment]
Re-reading the nuspec verisioning documentation, I think what we [had before commit e2be0bf][1] was the correct thing. It specified a lower bound of 7.0.1 but no upper bound.

Looking through [the history of NuGet's update behavior][2], the default is to install the _lowest_ version that satisfied the constraints. If you'd like to use Newtonsoft JSON 9.0.1, you can install/upgrade to that version of Newtonsoft.Json explicitly, and Bond will still work. You can also use `Install-Package -DependencyVersion Highest`:

```
PM> install-package bond.csharp -DependencyVersion Highest -WhatIf

Attempting to gather dependency information for package 'bond.csharp.4.3.0' with respect to project 'Playground', targeting '.NETFramework,Version=v4.6.1'
Gathering dependency information took 584.53 ms
Attempting to resolve dependencies for package 'bond.csharp.4.3.0' with DependencyBehavior 'Highest'
Resolving dependency information took 0 ms
Resolving actions to install package 'bond.csharp.4.3.0'
Resolved actions to install package 'bond.csharp.4.3.0'
Install Bond.Core.CSharp.4.3.0
Install Newtonsoft.Json.9.0.1
Install Bond.Runtime.CSharp.4.3.0 : Bond.Core.CSharp [4.3.0, 4.3.0], Newtonsoft.Json [7.0.1, 10.0.0)
Install Bond.CSharp.4.3.0 : Bond.Core.CSharp [4.3.0, 4.3.0], Bond.Runtime.CSharp [4.3.0, 4.3.0]
Time Elapsed: 00:00:01.2734569
```

I'm preparing a PR to relax the upper bound in the .nuspec back to what we had before.

[1]: https://github.com/Microsoft/bond/commit/e2be0bf3ec12e97555cf6204dc56cb8b6a4985f4#diff-b8c68298b1d6a5fcaf062039e6d92cbfL25
[2]: http://blog.nuget.org/20131216/update-all-experience-explained.html

**Comment by chwarr** [comment]
As part of adding .NET Core support, we've bumped the minimum Newtonsoft.JSON version to 9.0.1. See commits 2deb1864dfdeac5aaa4aa42d2ecd76530b4bf49c and 6829035e0cb2c940f1f261e15090bf91e7dbb148.
