### ISSUE TITLE
Deserializing 'A' to 'IBonded<A>'?

### ISSUE THREAD

**Issue by jterry75** [Microsoft/bond#217]
I have been looking at the code and samples to try to figure out how this is done but to no avail. I want to deserialize from a stream WITHOUT a container object to an IBonded<T>. IE:

```bond
struct A
{
  0: required string Type;
}

struct B : A
{
  0: string BStuff;
}

struct C : A
{
  0: string CStuff;
}
```

```C#
var rdr = new SimpleJsonReader(stream);
var a = Deserialize<IBonded<A>>.From(rdr);
if (a.Deserialize().Type == "BType")
{
  var b = a.Deserialize<B>();
}
```
etc...

But I don't want to have to make another object such as:
```bond
struct Wrapper
{
  0: IBonded<A> PolymorphicData;
}
```

I have also tried telling the base type directly to be (typeof(Bonded<A>) and typeof(A). It seems like no matter what the "Cache" fails to know how to realize the type. I have even gone so far as to write a `CustomBonded<T>` much like the tests that seek/reset the underlying stream so I can effectively deserialize it again without a mem copy but this seems crazy.

Any guidance / updates to the Polymorphic examples would be awesome! Thanks.

**Comment by chwarr** [comment]
What you want to do with bonded types won't work with the current `SimpleJsonReader` implementation in C#, as it doesn't support lazy deserialization. There's an existing issue, [#96 JSON doesn't support lazy deserialization][1] open for this.

If you use an encoding protocol that does support lazy deserialization, like Compact Binary, this would work, with code that looks like the following. Notice that we're not deserializing to a `IBonded<A>`; we're just creating an `IBonded<A>` backed by a reader.

```
static void DeserializeAndPrint(ArraySegment<byte> data)
{
    var reader = new CompactBinaryReader<InputBuffer>(new InputBuffer(data));
    IBonded<A> bondedA = new Bonded<A, CompactBinaryReader<InputBuffer>>(reader);
    var a = bondedA.Deserialize<A>();

    switch (a.Type)
    {
        case "BType":
            {
                var b = bondedA.Deserialize<B>();
                Console.WriteLine($"Got a B: {b.BStuff}");
                break;
            }

        case "CType":
            {
                var c = bondedA.Deserialize<C>();
                Console.WriteLine($"Got a C: {c.CStuff}");
                break;
            }

        default:
            Console.WriteLine($"Unknown derived type {a.Type}");
            break;
    }
}
```

[1]: https://github.com/Microsoft/bond/issues/96

**Comment by jterry75** [comment]
@chwarr - Thank you for the link to the other issue! That now makes total sense why this wasn't working. I can likely just switch to the CompactBinary protocol in my case.
