### ISSUE TITLE
macOS py-clang tests are failing

### ISSUE THREAD

**Issue by chwarr** [Microsoft/bond#238]
In the [Travis CI run](https://travis-ci.org/Microsoft/bond/builds/167267956) for pull request #237, which changes only the way we generate documentation, some of the Python unit tests have started to fail:

From the [macOS py-clang variant](https://travis-ci.org/Microsoft/bond/jobs/167267964):

```
======================================================================
ERROR: test_Bonded (__main__.BondTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/travis/build/Microsoft/bond/python/test/core/unit_test.py", line 371, in test_Bonded
    obj = self.randomSimpleStruct()
  File "/Users/travis/build/Microsoft/bond/python/test/core/unit_test.py", line 97, in randomSimpleStruct
    obj = test.SimpleStruct()
TypeError: __init__() should return None, not 'NoneType'
```

**Comment by lalo** [comment]
Possibly related: http://stackoverflow.com/questions/20437769/boost-python-init-should-return-none-not-nonetype#21052641

**Comment by lalo** [comment]
echo /usr/local/Cellar/python/2.7.12*/Frameworks/Python.framework/Versions/2.7/lib/libpython2.7.dylib

**Comment by lalo** [comment]
Test pass, nothing broke during the dark times
https://travis-ci.org/Microsoft/bond/jobs/171522072

**Comment by lalo** [comment]
Closed with PR https://github.com/Microsoft/bond/pull/249
