### ISSUE TITLE
Syntax highlighting for Notepad++

### ISSUE THREAD

**Issue by jdom** [Microsoft/bond#24]
Now that there is syntax highlighting for Sublime, maybe someone could contribute highlighting for Notepad++ based on it.
If nobody picks this task up, I'll try to submit a PR myself at some point if I can, but can't promise anything... just thought it's an easy task that someone might want to pick up before I can get to it.

**Comment by ardanew** [comment]
https://github.com/ardanew/misc/blob/master/Bond.xml

**Comment by ramb0x** [comment]
Also sent a PR for my version.

**Comment by sapek** [comment]
Resolved with @4bea59d783.
