### ISSUE TITLE
Compile Bond code at runtime

### ISSUE THREAD

**Issue by yagilofir** [Microsoft/bond#253]
Hi.
I would like to create a function that checks if a given string can compile using the Bond compiler.
This will be a boolean function which gets a Bond scheme as a string parameter (the parameter is actually a Bond code that can successfully compile using the gbc.)
This function will return true iff the parameter is a correct Bond scheme.

Do you have a mechanism that compiles some Bond code at runtime ? (I need it for C# and CPP)
Another option is to just write a code that stores this string into a file, runs your gbc process and checks the result code, but that's a last resort option.

Thanks.

**Comment by sapek** [comment]
Bond compiler is available as [Haskell library](https://hackage.haskell.org/package/bond). In particular the [parseBond](https://hackage.haskell.org/package/bond-0.6.0.0/docs/Language-Bond-Parser.html#g:1) function does what you want. To call it from C++/C# you would need to wrap the library using Haskell FFI or use a package like [hs-dotnet](https://hackage.haskell.org/package/hs-dotnet).

**Comment by chwarr** [comment]
You may also be interesting in the code that resolves import path is in [IO.hs](https://github.com/Microsoft/bond/blob/939c298ff6d619dbc0bc9f5ca25c2088de86d83b/compiler/IO.hs#L50-L58). Perhaps this makes sense for your runtime code generation, but perhaps not, and you'll need to customize it.

hs-dotnet isn't building anymore: it appears abandoned. The Haskell FFI route probably makes more sense.

No one has done a FFI type integration yet, so if you decide to use Haskell FFI, please let us know how it works out.

**Comment by chwarr** [comment]
Having heard nothing in the past couple of months, I'm going to close this issue. Please re-open if there's something else on this topic.
