### ISSUE TITLE
C++ Bond Comm

### ISSUE THREAD

**Issue by shazqadeer** [Microsoft/bond#266]
The website says that C++ version of Bond Comm will be available in a few days.  Do you have a more precise update on when it will be available?

**Comment by lalo** [comment]
It's already available 

https://microsoft.github.io/bond/manual/bond_cs.html#bond-comm

https://microsoft.github.io/bond/manual/bond_cs.html#comm-nuget-packages

**Comment by chwarr** [comment]
We pushed the alpha version of the code for the C++ Comm framework  in  commit 7a837b4b9696cd20915b07100d9859acee20e6a2 (it's big so make take a while to load) but we have been working through some issues turned up in the unit tests across various platforms and compilers (see https://github.com/Microsoft/bond/pull/255) before making an announcement around it.
