### ISSUE TITLE
Failed to build c++ examples at release mode

### ISSUE THREAD

**Issue by jacobwpeng** [Microsoft/bond#284]
OS: linux x86_64
Kernel version: 3.10.0
Compiler: clang-3.9.0
Source version: bond-5.0.0 release
Failed files:
examples/cpp/comm/generic/generic.cpp
examples/cpp/comm/passthrough/passthrough.cpp

Both files contain a variable "result" which only used in the next assert, but assert is not working at release mode.
Since release mode use -Wall -Werror, maybe it's better to define a macro to fix these compile errors;
eg:
#define BOND_UNUSED(var) (void)var
BOND_UNUSED(result);

**Comment by chwarr** [comment]
Actually, it would be better to either always enable asserts in the examples or switch to something that isn't specific to the `NDEBUG` macro. The examples are run as part of the check target, and we do want to validate the results, even for a release build.

If you are just trying to _consume_ a release build of Bond, you can get everything you need by building the default target.
