### ISSUE TITLE
Bond.Comm & Microsoft.Orleans

### ISSUE THREAD

**Issue by ronMilne** [Microsoft/bond#289]
Does anyone have a step by step guide in how one would integrate these two technologies. The documentation on both of these projects is a little thin?

Regards,
Ron.

**Comment by chwarr** [comment]
There are [tests][bond-tests] in the Orleans repository that use Bond for serialization/deserialization. It appears that a serialization provider needs to be registered with the `SerializationManager`. There's also the NuGet package [Microsoft.Orleans.Serialization.Bond][mosb], that appears to [modify a config file][install] to configure the Orelans Bond serializer.

Hope this helps.

[bond-tests]: https://github.com/dotnet/orleans/blob/e2462e111c9936b71eb29f0f7d0c4148dcc4e22b/test/Tester/SerializationTests/BondSerializationTests.cs
[install]: https://github.com/dotnet/orleans/blob/8d6153f46763a3ec97db483142ce17b9d90dc9c9/src/NuGet/BondSerializerInstall.ps1
[mosb]: http://www.nuget.org/packages/Microsoft.Orleans.Serialization.Bond/

**Comment by chwarr** [comment]
I misread the original question. I didn't realize that you were asking about Bond.Comm; I assume you were asking about using Bond for serialization within Orleans, which is addressed in [my first reply][for-ser].

Can you add some more details about how in particular you'd like to integrate Bond.Comm and Orleans? What problems would you like to solve with one and with the other? Any details about attempts you have taken so far?

[for-ser]: https://github.com/Microsoft/bond/issues/289#issuecomment-270556822

**Comment by chwarr** [comment]
Having heard nothing in over two weeks, I'm going to close this issue. Feel free to re-open if there's more help that you need.
