### ISSUE TITLE
No good way to generate a DateTime property in C# that serializes to wstring

### ISSUE THREAD

**Issue by DmitryTsygankov** [Microsoft/bond#300]
On Bond 5.1.0, I have a .bond file which basically looks like this: 
```
struct Sample
{
    80: optional wstring StartDateTime;
}
```

It is generating a C# file with the below property:
```
[global::Bond.Id(80), global::Bond.Type(typeof(global::Bond.Tag.wstring))]
public string StartDateTime { get; set; }

protected Sample (string fullName, string name)
{
    StartDateTime = "";
}
```

For obvious reasons, I would like it to generate a DateTime property in C#, but I would like to do it without changing the network protocol parts. When I try to do the following type alias trick, the runtime schema generation fails:
```
using DateTime = wstring;
struct Sample
{
    80: optional DateTime StartDateTime;
}

    public static class BondTypeAliasConverter
    {
        public static string Convert(DateTime value, string unused)
        {
            return value == default(DateTime) ? "" : value.ToString("o", CultureInfo.InvariantCulture);
        }

        public static DateTime Convert(string value, DateTime unused)
        {
            return value == "" ? default(DateTime) : DateTime.Parse(value);
        }
    }

    <BondCodegen Include="Sample.bond">
      <Options>--using="DateTime=System.DateTime"</Options>
    </BondCodegen>
```

The failure is happening inside of the Schema<Sample>.RuntimeSchema, namely:
```
System.InvalidCastException: Unable to cast object of type 'System.DateTime' to type 'System.String'.
    at Bond.Schema`1.Cache.GetDefaultValue(ISchemaField schemaField) in S:\bondlab\nuget\bond\cs\src\core\Schema.cs: line 224
```
For whatever reason, that code is trying to cast the default DateTime value to string, even though I am providing the BondTypeAliasConverter: variant.wstring_value = (string) defaultValue;
I think this is an issue that is significantly limiting the flexibility and usefulness of type aliases.

So I have to abandon that attempt, and try it the other way, by making the DateTime property nullable:
```
      <Options>--using="DateTime=System.Nullable&lt;System.DateTime&gt;"</Options>

    public static class BondTypeAliasConverter
    {
        public static string Convert(DateTime value, string unused)
        {
            return value == default(DateTime) ? "" : value.ToString("o", CultureInfo.InvariantCulture);
        }

        public static DateTime Convert(string value, DateTime unused)
        {
            return value == "" ? default(DateTime) : DateTime.Parse(value);
        }

        public static string Convert(DateTime? value, string unused)
        {
            return value?.ToString("o", CultureInfo.InvariantCulture) ?? "";
        }

        public static DateTime? Convert(string value, DateTime? unused)
        {
            return value == "" ? (DateTime?)null : DateTime.Parse(value);
        }
    }
```
That code compiles, and is able to generate the runtime schema. However, the breakpoint in BondTypeAliasConverter.Convert(DateTime? value, string unused) is never getting hit.
When I leave the StartDateTime property as null, Bond decides on some value internally, without ever calling any of the BondTypeAliasConverter methods, and I am not sure what it is passing into the network. Even if it happens to be doing the right thing for me by some accident, I still think it would make sense to call the Convert(DateTime? value, string unused) method when it is available.
When I do assign StartDateTime to some value, it is hitting the Convert(DateTime value, string unused) method, not the Convert(DateTime? value, string unused) method.

**Comment by sapek** [comment]
This is indeed a (trivial) bug: default value for `wstring` aliases is not handled properly [here](https://github.com/Microsoft/bond/blob/master/cs/src/core/Schema.cs#L219-L225).

**Comment by chwarr** [comment]
There's a similar bug for bool fields. PR #301 has a proposed fix.
