### ISSUE TITLE
Support for fixed-size / inline arrays

### ISSUE THREAD

**Issue by jack-pappas** [Microsoft/bond#303]
Please consider implementing support for fixed-size, "inline" arrays in struct definitions, as in C/C++, or in C#'s [Fixed Size Buffers](https://msdn.microsoft.com/en-us/library/zycewsya.aspx). In the wire formats, the encoding could be exactly the same so there'd be no difference in size; for applications with structs containing an array-typed field known to have a fixed length (e.g., [ISBN](https://en.wikipedia.org/wiki/International_Standard_Book_Number) could be represented by ``byte[13]``), this may improve performance by eliminating lots of small array/string heap allocations.

**Comment by sapek** [comment]
You can achieve this with type aliases, e.g.: https://github.com/Microsoft/bond/tree/master/examples/cpp/core/static_array

**Comment by jack-pappas** [comment]
@sapek Seems like that'll only work for C++? What about C# support?

**Comment by sapek** [comment]
[You can use array](https://github.com/Microsoft/bond/blob/master/cs/test/core/Core.csproj#L59) as type alias of a vector/list/blob in C#. I've never tried with fixed size array though. Give it a try. If it works, it would be a great example to contribute. If you find a problem we should see if it can be fixed.

**Comment by chwarr** [comment]
Type aliases won't work for C# fixed arrays for two reasons:

1. there's no way to "name" the generated type for the fixed array, so none of the converter method match; and
1. the converter method isn't given access to the source/destination object, just the value to convert, so there no where to put the data.

```
[Schema]
unsafe struct Foo
{
    [Id(0)]
    [Type(typeof(Bond.Tag.blob))]
    public fixed byte inlineFixedArray[10];
}

    public unsafe static class BondTypeAliasConverter
    {
        // BROKEN!!!
        public static byte* Convert(ArraySegment<byte> value, byte* unused)
        {
            fixed (byte* inputPtr = value.Array)
            {
                // This will fail, as unsued isn't actually a pointer into the object. It will be 0.
                Buffer.MemoryCopy(inputPtr + value.Offset, unused, 10, 10);
            }

            return default(byte*);
        }

        // BROKEN!!!
        public static ArraySegment<byte> Convert(byte* value, ArraySegment<byte> unused)
        {
            var copy = new byte[10];
            fixed (byte* copyPtr = copy)
            {
                // Who knows if this will work. Will value point to the right thing?
                Buffer.MemoryCopy(value, copyPtr, copy.Length, copy.Length);
            }

            return new ArraySegment<byte>(copy);
        }
    }
```

If you want to use fixed arrays, a custom transform is going to be needed.
