### ISSUE TITLE
Add schema evolution documentation

### ISSUE THREAD

**Issue by chwarr** [Microsoft/bond#316]
There should be explicit documentation about what kinds of schema changes are backward/forward compatible. Things to discuss include:

* addition/removal of fields
    * how `optional`, `required`, and `required_optional` come into play
* addition/removal of bases
* type changes, particularly for numeric types (numeric promotions)
* renaming fields and different encoding protocols

See also: issue #115, "Refactor languange-independent topics out from C++ documentation".

**Comment by chadwalters** [comment]
Closed by https://github.com/Microsoft/bond/pull/326

https://github.com/Microsoft/bond/issues/115 is waiting for Pandoc transclusion support.
