### ISSUE TITLE
Request for custom map implementation example (c++)

### ISSUE THREAD

**Issue by ardanew** [Microsoft/bond#33]
It must be possible to define a custom non-stl map container. For custom list and custom string there is an examples and it was easy to write some code based on them. But for map it seems more complex to do this.

**Comment by sapek** [comment]
We will add an example but for now you can take a look at the [test of a custom map type](https://github.com/Microsoft/bond/blob/72fa67e0f7165eba4d476c12a55860f3cddbd903/cpp/test/core/associative_container_extensibility.cpp#L72-L135) and the interface [documentation](https://microsoft.github.io/bond/manual/bond_cpp.html#container-concept). You can of course define a [type alias](https://microsoft.github.io/bond/manual/bond_cpp.html#type-aliases) for map in your schema and then [map it during codegen](https://microsoft.github.io/bond/manual/bond_cpp.html#codegen-parameters) to your custom map type.

**Comment by ardanew** [comment]
Thanks, it works!
