### ISSUE TITLE
gbc fails to run on mono under linux

### ISSUE THREAD

**Issue by pdylanross** [Microsoft/bond#335]
Using Bond.CSharp.5.2.0 fails to run GBC when compiling under Ubuntu 16.04 / Mono 4.6.2. The project is a VS 14 sln, and bond is installed via nuget. The first issue I had was permission denied for gbc.exe, which was an easy fix by adding execute permissions to gbc.exe. Unsure if that's an issue with the package or nuget it's self, but it's an easy fix. Now it's failing with the error message `run-detectors: unable to find an interpreter for {{path}}/gbc.exe`. I believe I should be able to build gbc locally and replace gbc in the package cache to get it to work, but I'm not a fan of that as I'll have to re-run that every time I upgrade bond or restore packages on a fresh environment. Any thoughts?

**Comment by chwarr** [comment]
The NuGet package contains a Windows x64 executable. At the moment, you will need to build gbc from source, as we don't provide a pre-compiled version of gbc for any other platform. (Maybe Wine will work. Not sure.)

**Comment by chwarr** [comment]
And, after building gbc, you don't have to modify the NuGet package. Put the gbc somewhere accessible and in your csproj, before importing the Bond.CSharp.props file, set the property [`BOND_COMPILER_PATH`](https://github.com/Microsoft/bond/blob/708c9ded049c42676ce892a3f05c225f0c26e6c3/cs/build/nuget/Common.props#L19) to point to the directory containing gbc. Then, the codegen targets will [invoke that gbc](https://github.com/Microsoft/bond/blob/708c9ded049c42676ce892a3f05c225f0c26e6c3/cs/build/nuget/Common.targets#L64-L66). (If `BOND_COMPILER_PATH` is unset, it defaults to the location inside the package, which works for most of the consumers of C# Bond, who are on Windows.)

**Comment by chwarr** [comment]
Did you get a chance to try setting `BOND_COMPILER_PATH`?

**Comment by chwarr** [comment]
Having heard nothing more, closing this issue. Feel free to re-open.
