### ISSUE TITLE
Incorrect Bond Type Tag when using Alias

### ISSUE THREAD

**Issue by aschmahmann** [Microsoft/bond#336]
```bond
namespace Example
using testAlias = blob

struct testStruct
{
    0: testAlias data = nothing;
}
```

This results in C# generated code:
```c#
    [global::Bond.Schema]
    [System.CodeDom.Compiler.GeneratedCode("gbc", "0.8.0.0")]
    public partial class testStruct
    {
        [global::Bond.Id(0), global::Bond.Type(typeof(global::Bond.Tag.blob))]
        public MyLib.importedAlias data { get; set; }

        public testStruct() : this("Example.testStruct", "testStruct"){}

        protected testStruct(string fullName, string name){}
    }
```

Notice that the `data` field is annotated with `global::Bond.Type(typeof(global::Bond.Tag.blob))` instead of `global::Bond.Type(typeof(MyLib.importedAlias))`.

On a related note, is there a better default then blob I can be using as a placeholder for the alias?

**Comment by sapek** [comment]
The tag is correct. It tells Bond runtime that the type `MyLib.importedAlias`, which otherwise Bond knows nothing about, should be treated as an alias of `blob`.

**Comment by chwarr** [comment]
I'm going to close this issue, as everything is working as expected. Please re-open if there's more.
