### ISSUE TITLE
Check for Visual C++ 2017 compability

### ISSUE THREAD

**Issue by chwarr** [Microsoft/bond#340]
Visual C++ 2017 is nearing its release. Check that Bond builds and the tests pass with it. Open issues for any conformance issues found.

**Comment by jdubrule** [comment]
You should also check with "/permissive-" enabled, which makes VS2017
stricter about C++ conformance.

**Comment by chwarr** [comment]
Agreed about `/permissive-`

**Comment by chwarr** [comment]
Haven't yet checked `/permissive-` yet, but everything builds fine with Boost 1.62. I found a [crashing bug in MSBuild](https://github.com/Microsoft/msbuild/issues/1796) when it tries to build gbc-tests, so I'm working around that. Once that's resolved, I can run the tests.

**Comment by chwarr** [comment]
Everything builds fine with `/permissive- /std:c++14`. I can't get things to link, but that's due to my hacked Boost 1.62 VC15 build that isn't quite complete, so I can't run tests. I'll re-do my Boost build to try to resolve this.
