### ISSUE TITLE
VS 2013 with Update5 And Boost 1_61_0

### ISSUE THREAD

**Issue by zhenqinshang** [Microsoft/bond#347]
1.在编译方案后,Pingpong并不能正常编译通过,需要自行加入Boost的System相关的lib,希望提高这方面的易用性,你们包好,无需使用者关心包含关系

**Comment by chwarr** [comment]
我不说中文. 你说不说英文?

**Comment by chwarr** [comment]
Here's a translation:
> After I try to compile the program, Pingpong cannot pass the compiling unless I add a System library file from Boost. Hope you can improve the usability of your tool to completely take care of the issue like this so user does not need to worry about the dependency.

**Comment by chwarr** [comment]
For Bond.Comm, you will have to link with some of the Boost libraries. We're using functionality that isn't available in just the Boost headers.

If you are defining `BOOST_ALL_NO_LIB` in your build rules, consider undefining it. This will enable [Boost's auto-linking feature](http://www.boost.org/doc/libs/1_60_0/more/getting_started/windows.html#link-your-program-to-a-boost-library). If that doesn't work for you, you'll need to configure each target to link with the required libraries. (`BOOST_ALL_NO_LIB` [is defined](https://github.com/Microsoft/bond/blob/1426db8e9a1fa4cfcfa9c4c86b12e9dd123623de/cmake/Config.cmake#L96-L97) when we build Bond itself, but that shouldn't make it into your own projects.)

If you need more help with this, please let us know how you're building your projects, and we'll try to find you some more pointers for your particular environment.

We cannot ship a version of Boost with Bond: that prevents you from using the version most suitable for your environment.

**Comment by zhenqinshang** [comment]
My problem is solved, but Thank you very much. I love you for answer.
