### ISSUE TITLE
Bond Importing From Parent or Sibling Directories

### ISSUE THREAD

**Issue by aschmahmann** [Microsoft/bond#361]
I have two libraries `baseLib` and `extrasLib` where `extrasLib` has a dependency on `baseLib`. Both libraries use Bond structs, and `extrasLib` has Bond structs that contain or derive from structs declared in `baseLib`. When I try and get the `extrasLib` .bond files to reference the ones in `baseLib` I get Unknown Symbol errors. I reference the `baseLib` structs using something like import `..\baseLibFolder`.

I thought maybe I just messed up my configurations so I tried using the import example and moving one of the files up in the folder hierarchy and the issues persisted. Is there something I'm doing wrong or is this a bug? If it's a bug are there any suggestions for dealing with this issue?

**Comment by chwarr** [comment]
Importing from a relative directory works, but you have to import a .bond file, not a directory.

```
import "../parent.bond" // backslashes work too: import "..\parent.bond"

namespace child;

struct firstBorn
{
    0: parent.mother motherStructField;
}
```

You also say that you get "Unknown Symbol" errors. Importing makes the names available in the current .bond file so you can refer to the types in the other .bond file. It _does not_ cause the generated code to contain copies of the imported types. You still need to run codegen on the .bond files that you are importing, compile that code, and link with the compiled outputs. This allows multiple files to import from a common file without duplication of symbols, and the common code only has to be compiled once.

Here's an edited and annotated version of the C++ generated for the example above. Notice that there's neither a declaration nor a definition of `::parent::mother` in this file.

```
//   Tool : Bond Compiler 0.8.0.0
//   File : child_types.h

#pragma once

...

// A relative #include was generated from the relative import statement
//
// If you'd prefer #include "parent_types.h", then change to import "parent.bond" and
// add .. as an import-dir when calling gbc
#include "../parent_types.h"

...

namespace child
{
    
    struct firstBorn
    {
        // This member field relies on the complete type definition of ::parent::mother from parent_types.h
        ::parent::mother motherStructField;

        ...        
    };

...
} // namespace child
```

**Comment by aschmahmann** [comment]
Thanks for the help. It turns out I was handling the parent folder issue as you described, but that I was having namespace scoping issues. If I'm correct then the following is invalid:

<pre>
//first.bond
namespace First
struct FirstStruct {
0: int32 number;
}

//first.second.bond
namespace First.Second
struct SecondStruct {
0: <b>FirstStruct</b> data;
}
</pre>

instead `FirstStruct` must be `First.FirstStruct`.

Is there anyway to include namespaces (e.g. c# using)?

**Comment by chwarr** [comment]
Yes, you need to use the fully qualified name when importing. Nothing like using.

**Comment by jdubrule** [comment]
I would like a feature where the generated files follow the tree.
Currently, they all end up in one big directory, which kind of ruins the
point of organizing them in the first place, and has caused issues with
duplicate names.

**Comment by chwarr** [comment]
@jdubrule: there were some problems the last time we tried to make mirroring the directory hierarchy. I don't recall what they were offhand. I'll have to dig through my notes. Though, this seems different enough from the current issue to warrant its own issue. Can you open one mirroring specifically so I don't forget about it?

**Comment by chwarr** [comment]
I'm going to close this issue, as it seems resolved. Please re-open if there's more.
