### ISSUE TITLE
Moving Bond.Reflection into a new assembly broke backwards compatibility

### ISSUE THREAD

**Issue by mwstark** [Microsoft/bond#369]
Referencing this Pull Request:
https://github.com/Microsoft/bond/pull/252

Moving the types related to Bond.Reflection into a new assembly has broken backwards compatibility when taking the minor version upgrade from version 5.0.0 to 5.2.0.  Shouldn't the major version number have been incremented for this change?

**Comment by chwarr** [comment]
Are you experiencing a compatibility problem (e.g., failure to build, assembly load failure)?

Source-level compatibility shouldn't have been broken, so if you need a quick fix, try re-compiling against the new version.

It's possible that I broke drop-in binary compatibility inadvertently. My analysis may have missed something, and any details you have will help.

**Comment by mwstark** [comment]
I have another dependency that references type Bond.Reflection in assembly Bond.  When it tried to load the type using the 5.2.0 version of the assembly it failed with a TypeLoadException -- saying the type didn't exist in Bond.dll (which is doesn't).  If it had been my source that was directly referencing the change it wouldn't have been an issue since the compiler would have taken care of it; however, because it was consumed indirectly there wasn't much that I could do.  From the little that I have read, you could resolve the issue by adding a TypeForward declaration to Bond.dll.  I didn't see such a declaration in the skimming of the pull request.
https://msdn.microsoft.com/en-us/library/ms404275(v=vs.110).aspx

I've since downgraded back to version 5.0.0 and that has resolved the issue for me -- I can get you the exact exception message on Monday if you still want it.

**Comment by chwarr** [comment]
Ah. I think I see this mistake I made. I actually did break source level compat too. Sorry about that.

There way a type called `Bond.Reflection` in Bond.dll with public members. I [renamed this to `Bond.BondReflection`](https://github.com/chwarr/bond/commit/9753e3be3de6c4e2991dba0ae6ebcc29bbb9823e#diff-9cca6853a985418e4247bb69a4695dbbR16), still in Bond.dll.

If you can get the full error details, that will help me validate my assumptions and produce a regression test, and then a fix.

**Comment by mwstark** [comment]
Here is the exception -- I can provide the stack trace as well, but as it doesn't have any code from Bond I didn't think it would be helpful.

Could not load type 'Bond.Reflection' from assembly 'Bond, Version=1.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. 
  Description: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code. 

 Exception Details: System.TypeLoadException: Could not load type 'Bond.Reflection' from assembly 'Bond, Version=1.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'.

Source Error: 


 An unhandled exception was generated during the execution of the current web request. Information regarding the origin and location of the exception can be identified using the exception stack trace below.
