### ISSUE TITLE
bonded<> recursive usage question

### ISSUE THREAD

**Issue by codespare** [Microsoft/bond#38]
Hello, I am trying to get a combination of the generic_tree and polymorphic_container samples to obtain a polymorphic tree. But I cannot figure out how to serialize nested bonded<> fields, and I was wondering if that is supported?

**Comment by sapek** [comment]
You could define polymorphic tree like this:

    struct Data
    {}

    struct Node;
    struct Node
    {
        0: nullable<Node> left;
        1: nullable<Node> right;
        2: bonded<Base> data;
    }

You will need to serialize each node data to initialize the `data` field, like in the `polymorphic_container` example. You can also use generic `Node<T>`, either defining the `data` field as `2: bonded<T> data;` or as `2: T data;`. In the latter case you would use `Node<bonded<Data>>` instance.

**Comment by codespare** [comment]
Thank you, that got me unstuck. Ironically, that is much closer to the structure I am experimenting with([GumboParser](https://github.com/google/gumbo-parser/blob/master/src/gumbo.h)) as opposed to the inheritance based model I was trying initially (conventional OO bias probably).
I have also tried the approach briefly mentioned in the 'Why Bond' article to emulate `union` with `nullable<>` and that works too. I still need to dig further to figure out the trade-offs in each approach.
Also, I am curious to understand when a mapping between a C and Bond model such as this one mandates the use of `bonded<>` and an interim serialization, versus when it can be made blittable, possibly using transforms, but no intermediate copy.
