### ISSUE TITLE
Bond don't build on Windows 10 (v.15063) GHC 8.0.2

### ISSUE THREAD

**Issue by niclar** [Microsoft/bond#399]
Seems to be a problem with GHC and at least the latest window insider ring windows releases (v.15063 and the one prior).  The GHC process bails.  There's a fix merged to GHC 8.2 branch but no release yet.

https://git.haskell.org/ghc.git/commitdiff/018ac7f4b2f7345e28d21fb1f99b44dbc79f6e85

Is the best way to get bond to build to try and get a GHC 8.2 frankenbuild working with the 8.0.2 platform or what's the proposed solution?

Thanks   /Niclas

   Microsoft (R) Build Engine version 15.1.548.43366
  Copyright (C) Microsoft Corporation. All rights reserved.
  
    Building Custom Rule C:/packages/bond/compiler/CMakeLists.txt
    CMake does not need to re-run because C:\Users\USER\AppData\Local\CMakeBuild\e9f20f28-8de9-2138-8ba4-c3fdbb38aac3\build\x64-Debug\compiler\CMakeFiles\generate.stamp is up-to-date.
    Generating build/gbc/gbc.exe
C:\Users\USER\AppData\Local\CMakeBuild\e9f20f28-8de9-2138-8ba4-c3fdbb38aac3\build\x64-Debug\compiler\CUSTOMBUILD : warning : cannot determine version of C:/Program Files/Haskell 
    
    Platform/8.0.2\mingw\bin\gcc.exe :
    
    ""
    
    `gcc.exe' failed in phase `C Compiler'. (Exit code: -1073741502)
    
    CMake Error at cabal_build.cmake:33 (message):
    
    
c:\program files (x86)\microsoft visual studio\2017\community\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(171,5): error MSB6006: "cmd.exe" exited with code 1. 

Build failed.

**Comment by chwarr** [comment]
Yeah, we ran into this bug as well. I reported it to the Windows team, and its currently working its way though the Windows bug process. I do not have more details to share.

If you just need a copy of gbc.exe, there are two ways to get a copy:

1. from the [Releases](https://github.com/Microsoft/bond/releases) feed and
1. from the [Bond.Compiler](http://www.nuget.org/packages/Bond.Compiler/) NuGet package.

If you set the CMake variable [`BOND_GBC_PATH`](https://github.com/Microsoft/bond/blob/748db2f37f7036abacad9e3f2a24a5764b8f031b/cmake/Config.cmake#L3-L19) to point at a pre-compiled gbc.exe, then the CMake-based build will use that version, skipping all the Haskell build. There are two common ways to set this variable:

1. by explicitly passing it on the CMake command line like `cmake c:\bond -DBOND_GBC_PATH=c:/temp/gbc-5.2.0.exe -G "Visual Studio 14 2015 Win64"` or
1. by setting the environment variable `BOND_GBC_PATH` to the directory containing `gbc.exe`.

I've been doing my development work on the most recently released version of Windows, _not_ on an Insider Preview build, to avoid this problem.

**Comment by Dessix** [comment]
[This Stack comment](https://github.com/commercialhaskell/stack/issues/2998#issuecomment-291186156) mentions that `[GHC] 8.2.1 is supposed to come out in a couple weeks [...]`, so that's good news, but has anyone had success in building with the workarounds noted in that thread?

**Comment by chwarr** [comment]
Since this is an upstream issue with Windows and GHC that we cannot work around in Bond, I'm going to close this issue.

**Comment by chwarr** [comment]
There are new builds of the Haskell Platform with a fix for this live now at https://www.haskell.org/platform/windows.html. Make sure you get the 8.0.2-a version of the installers instead of just 8.0.2.

More details in [the announcement](https://mail.haskell.org/pipermail/haskell-cafe/2017-May/127048.html) to the Haskell Cafe mailing list.
