### ISSUE TITLE
Use IProtocolWriter methods directly

### ISSUE THREAD

**Issue by grant-d** [Microsoft/bond#432]
We have a scenario where we need a rectangle of data, but the shape is only known at runtime.
By way of comparison, think of a `Bond` version of `System.Data.DataTable` (or, perhaps, `Avro`)

Looking at implementation alternatives, we could either:
* Come up with some `IDL` model that would generate an appropriate set of classes (maybe `vector<vector<blob>>`), along with runtime methods that blit the source data into the `blob`s (thereby losing the benefit of VarInt, etc).
* And/or use runtime codegen (say, `T4`) to create concrete `Bond` decorated `C#` classes 
* Or use `IProtocolWriter` methods (on, say, `CompactBinaryWriter`) to read/write directly to a `stream`.

Is the **latter** a supported model for using `Bond` - any obvious challenges?
In our scenario we'd likely need to use a tagged protocol.
Versioning is not likely to be an issue - the data travels on the wire only (no persistence)

Are there any examples of doing this?

**Comment by chwarr** [comment]
`IProtocolReader` is a supported, public API. Albeit, a low-level one.

The challenges you'll experience are managing the schema. I have an idea for how you may be able to model this in IDL. I'll edit this to include that later.

**Comment by grant-d** [comment]
Thanks Chris.
I'd prefer to not have to use `blob` or `variant` for 'boxing' the individual cell values.
But not sure how we do this otherwise (in IDL)
At this stage the low-level API seems to be the best fit.

**Comment by chwarr** [comment]
You'd have to use a variant type to box the cell values to make this work from IDL.

Closing this for now. Feel free to post again if there's more.
