### ISSUE TITLE
Travis C# build is failing

### ISSUE THREAD

**Issue by chwarr** [Microsoft/bond#447]
A recent commit that just added a text file at the root has revealed that the Travis CI C# build is broken.

Build [1452.2 is broken](https://travis-ci.org/Microsoft/bond/jobs/231729590):

> Copying file from '/home/travis/build/Microsoft/bond/cs/src/reflection/bin/debug/net45/Bond.Reflection.dll' to '/home/travis/build/Microsoft/bond/cs/bin/debug/net45/Bond.Reflection.dll'
/home/travis/build/Microsoft/bond/cs/build/internal/Common.Internal.targets: error : Cannot copy /home/travis/build/Microsoft/bond/cs/src/reflection/bin/debug/net45/Bond.Reflection.dll.mdb to /home/travis/build/Microsoft/bond/cs/bin/debug/net45/Bond.Reflection.dll.mdb, as the source file doesn't exist.

This build used XBuild Engine Version 14.0 and Mono, Version 5.0.0.0. Instead of mdb files, pdb files are being produced with debug information.

Previous good build was [1450.1](https://travis-ci.org/Microsoft/bond/jobs/230998719) which used XBuild Engine Version 14.0 and Mono, Version 4.8.1.0.

This fix appears to be to update the condition in [Common.Internal.targets](https://github.com/Microsoft/bond/blob/46660fc21775a025e12cf356c6df87196e5cc324/cs/build/internal/Common.Internal.targets#L15) to specify a pdb file when using the newer version of Mono.

Related issue: [Convert .NET Core build to use MSBuild-based project](https://github.com/Microsoft/bond/issues/383)

**Comment by chwarr** [comment]
This has been fixed in commit https://github.com/Microsoft/bond/commit/107e3facd0b66c97967f99e05265233ddaa74441, which in in the grpc++ branch. We'll be merging that branch in a few days, so this will get fixed then.

**Comment by lalo** [comment]
Closed with merge 4b960966686b9c220e5a15e8d5e69510d6ffcb84 and more specifically commit 107e3facd0b66c97967f99e05265233ddaa74441
