### ISSUE TITLE
The documentation should state that structs cannot be default to nothing

### ISSUE THREAD

**Issue by ramon-garcia** [Microsoft/bond#464]
I was confused when I learned that Bond structure fields cannot be default to nothing.

While I think that this should be allowed (issue #226 ) , meanwhile the documentation should match the behavior.

In the "A Young Person's Guide to C++ Bond", /doc/src/bond_cpp.md , the documentation says:

> Since a nullable type must represent the additional value of null, its serialized representation necessarily incurs some overhead compared to the base type. Often it is more efficient to avoid using nullable type and instead designate one of normal values to handle the special case that otherwise would be represented by null. For example empty is usually a good choice for string and container types and 0 for arithmetic types. Another option that may sometimes be appropriate is setting default value of a field to nothing.
> 
> The canonical scenario where a nullable type is the right choice is recursive structures. For example here's how Bond TypeDef struct is defined:

The sense of the text and the example indicate that default nothing should be preferred to nullable, except for special cases like recursive structures. Therefore, non recursive structure fields, for instance should be default noting.

This text should say that for structure fields, default of nothing is not posible and nullable must be chosen.

(In the c# guide, /doc/src/bond_cs.md , I could not find any reference to the choice between default nothing and nullable)

**Comment by chwarr** [comment]
You're understanding of how the type system works is correct. Take a look at the refinements in https://github.com/Microsoft/bond/pull/469. I think it reads better now.

(As an aside, there's rendered documentation ([C++](https://microsoft.github.io/bond/manual/bond_cpp.html) and [C#](https://microsoft.github.io/bond/manual/bond_cs.html)) that I find easier to read.)

See also https://github.com/Microsoft/bond/issues/115

**Comment by ramon-garcia** [comment]
The documentation is still confusing, because it seems to intend to say that nullabe types are not essential for optional structure fields:

"The canonical scenario where a nullable type is the right choice is recursive structures. For example here's how Bond `TypeDef` struct is defined"


>  struct TypeDef
>   {
>         ...
>         2: nullable<TypeDef> element;
>         ...
>   }

with this example, the choice of nullable does not have anything to do with recursion. It has to do with the element being a structure field, and being optional.

This is what I find confusing.

**Comment by chwarr** [comment]
It looks like the documentation generation didn't correctly publish the HTML pages (#478). Until we fix that, the [documentation source code](https://github.com/Microsoft/bond/blob/f9f2250356ba494a08f14ec7b75898012218252c/doc/src/bond_cpp.md#default-values) will need to be consulted to see the latest changes.

In Bond, `optional` and `nullable` are not the same thing. In fact, they can be combined:

```
struct HasOptNullableField {
    0: optional nullable<int32> oni32;
}
```

`optional` means that the field does not need to be in the payload (e.g., do not fail deserialization if an older producer didn't know about and produce this field, potentially omit the field when serializing if it is set to its default value). Struct fields cannot be omitted, nor can they have a default of `nothing`.

`nullable` means that `null` is also a legal value for the field.

If you're data model is such that sometimes you don't have anything useful to put into a field of a struct type, `nullable` is a good choice--perhaps the only choice--for that field.

The `TypeDef` struct must use a `nullable<TypeDef>` field to refer to itself. If it didn't there would be no way to instantiate a `TypeDef` instance: when initializing the `element` field, it would need to initialize a default `TypeDef` instance which would then need to initialize its own `element` field, which would need to initialize a default `TypeDef` instance, and so on, recurring without a base case. The `nullable<TypeDef>` provides the base case that terminates this recursion.

Hope this helps. Let me know if you have more questions.

**Comment by ramon-garcia** [comment]
Thank you for the clarification. I understand it
