### ISSUE TITLE
Documentation build not publishing to gh-pages correctly

### ISSUE THREAD

**Issue by chwarr** [Microsoft/bond#478]
In commit f9f2250356ba494a08f14ec7b some of the Markdown-based documentation was updated. The [doc build](https://ci.appveyor.com/project/MicrosoftBond/bond/build/1.0.133/job/cbv8gmkbwba4rkta) for that commit ran successfully, but it did not update the gh-pages branch correctly, so the static documentation pages are stale.

**Comment by lalo** [comment]
The issue was solved by giving the right permissions to the account that publishes the pages on the Microsoft/Bond repo.
