### ISSUE TITLE
Copying symbols fails in visual studio build lab due to pdb in nuget package

### ISSUE THREAD

**Issue by kellyanng** [Microsoft/bond#492]
After integrating  Bond.Core.CSharp v5.3.1, Bond.CSharp v5.3.1, and Bond.Runtime.CSharp v5.3.1 into our project, our build lab builds began failing while trying to publish symbols. They were failing with:
"Indexed source information could not be retrieved from '<path>\Bond.Attributes.pdb'. Symbol indexes could not be retrieved."
From other instances of this error I've found on GitHub and stackoverflow, it looks like it's caused because the pdb file is inline with the dll.  
The recommendation on nuget is to package pdb files separately: (https://docs.microsoft.com/en-us/nuget/create-packages/symbol-packages)

Can this nuget package be updated to move the pdb files out into their own symbols package?

**Comment by chwarr** [comment]
Are you building with TFS by chance? If so, it looks like [this issue](https://github.com/dotnet/core/issues/185). The [fix there](https://github.com/JoshClose/CsvHelper/commit/fae2c9746588f28291fd312621d514fd7b99250d) was to use `"debugType": "full"` for "net40" and "net45" frameworks. Something similar could likely be done here as well.

At the moment, since SymbolSource.org is having difficulties, I'd like to err on the side of keeping the PDBs inline with the assemblies so that they actually are stored somewhere that people can get to them.

**Comment by kellyanng** [comment]
Our build system is TFS or VSTS. (I'm not precisely sure which though I expect for this case it doesn't matter. Let me know if that assumption is incorrect.)

**Comment by chwarr** [comment]
A potential mitigation would be to add a step in your build that deletes the affected PDBs. Clunky, but it will get your builds passing again, and you can still manually grab the PDBs for debugging later if needed.

The concerns about changing the debug type are well founded. It feels like the "correct" fix is to teach TFS/VSTS to understand these PDB files. Let me check with some more knowledgeable people and see if there's something else to be done.

**Comment by chwarr** [comment]
A follow up question? How are you building your .NET project and what framework are you targeting? The net40 and net45 copies of Bond.Attributes are built with MSBuild 14 and use [`/debug:pdbonly` (and not portable) for release builds](https://github.com/Microsoft/bond/blob/236009e1bec7a09e8add88cc8722ba7352674452/cs/build/internal/Common.Internal.props#L41). If you're not targeting one of the `netstandard` frameworks, I wonder whether it's trying to index *all* the PDBs, not just the ones for assemblies consumed...

**Comment by kellyanng** [comment]
I'll play around with deleting my PDBs before TFS tries to copy them fixes it.

**Comment by kellyanng** [comment]
Deleting the files works for me.   
If anyone else is wondering how to solve this in their build:  
I added a Delete File command (documented here: https://www.visualstudio.com/en-us/docs/build/steps/utility/delete-files) with the "Contents" values of:
**\Bond.Attributes.pdb
**\Bond.IO.pdb
**\Bond.Reflection.pdb
**\Bond.pdb
**\Bond.JSON.pdb

**Comment by chwarr** [comment]
This appears to be due missing support for portable PDBs in VSTS's build tasks.
https://github.com/Microsoft/vsts-tasks/issues/4567

**Comment by mjsabby** [comment]
The fix has been deployed to VSTS agents, so this should be fixed.

**Comment by chwarr** [comment]
@kellyanng: can you check and make sure that this works for you with the newly deployed VSTS agents?

**Comment by chwarr** [comment]
Having heard nothing in months, closing this issue. Please re-open if needed.
