### ISSUE TITLE
Bond.IO.Unsafe.InputStream cannot handle an underlying stream that doesn't support Seek

### ISSUE THREAD

**Issue by chwarr** [Microsoft/bond#498]
A private bug report came to us:

> I’m facing a problem in which I’m trying to deserialize a bond enumerable object directly from a GZip stream.
> If I first decompress the stream into a memory stream, it all works great. But if I try to deserialize directly from the GZipStream I get an InvalidOperationException since GZipStream doesn’t support Seek method.
>
> This exception is thrown from \[[`Bond.IO.Unsafe.InputStream.EndOfStream()`](https://github.com/Microsoft/bond/blob/7b4b5f8821bee3a8577bfd3003379452f4b72a62/cs/src/io/unsafe/InputStream.cs#L102)\].
>
> NOTES:
> -	I believe Seek is not really required here and you can call ‘Read’ instead with the positive offset.
> -	That’s the only Seek I found in Bond sources.

**Comment by gerlas** [comment]
This looks like it may also be an issue for me, as I look to move existing code to use Bond.
All (de)serialization I do - is done within a compressed stream.

Example usage...
```
// Writing data as compressed stream to file (with progress notification)
using (var fileStream = new FileStream(filename, FileMode.Create, FileAccess.Write, FileShare.None))
{
   using (var progressStream = new ReadProgressStream(fileStream)) 
   {
      progressStream.ProgressChanged += progressStream_ProgressChanged;
      using (var deflateStream = new DeflateStream(progressStream, CompressionMode.Decompress, true))
      {
         // WRITE data...  using deflateStream
      }
   }
}

// Reading data from compressed stream in file (with progress notification).
// Buffering required for de-compression to avoid memory bloat.
using (var fileStream = new FileStream(filename, FileMode.Open, FileAccess.Read, FileShare.Read))
{
   using (var progressStream = new ReadProgressStream(fileStream)) 
   {
      progressStream.ProgressChanged += progressStream_ProgressChanged;
      using (var bufferedStream = new BufferedStream(progressStream, bufferSize))
      {
         using (var deflateStream = new DeflateStream(bufferedStream, CompressionMode.Compress, true)
         {
            // READ data...  using deflateStream
         }
      }
   }
}
```
