### ISSUE TITLE
Does BondSeralizer supports Json seralization and Deseralization of datatable and dataset?

### ISSUE THREAD

**Issue by vijay8059** [Microsoft/bond#500]
Does BondSeralizer supports Json seralization and Deseralization of datatable and dataset?

**Comment by chwarr** [comment]
If by datatable, you are referring to the [`System.Data.DataTable` type](https://msdn.microsoft.com/en-us/library/system.data.datatable(v=vs.110).aspx), no, Bond does not know how to serialize this class.

Bond can serialize objects that have a schema known to Bond. This is typically done by using the [.bond definition language and then running the Bond codegen tool to create C# classes](https://microsoft.github.io/bond/manual/bond_cs.html#basic-example). You can [annotate existing C# classes *that you control*](https://microsoft.github.io/bond/manual/bond_cs.html#attributes) to define their Bond schema. There's currently no way to give a Bond schema to a class that you do not control. See also issue #285, which is about possibly coming up with an alternate API for imbuing a type with a Bond schema. (Designing the API mentioned in #285 is not something that anyone is working on at the moment, AFAIK.)

**Comment by chwarr** [comment]
Let me know if you need more info.
