### ISSUE TITLE
Travis CI builds have stopped working: cabal and ghc versions appear not to be compatible

### ISSUE THREAD

**Issue by chwarr** [Microsoft/bond#508]
Travis CI builds have stopped working. gbc cannot be successfully built. From [a recent PR build that only changed some C# code](https://travis-ci.org/Microsoft/bond/jobs/245990932#L2614):

> on the commandline: warning:
>     -this-package-key is deprecated: Use -this-unit-id instead
> In-place registering bond-0.9.0.0...
> cabal: '/opt/ghc/bin/ghc-pkg' exited with an error:
> bond-0.9.0.0: Warning: haddock-interfaces:
> /home/travis/build/Microsoft/bond/build/compiler/doc/html/bond/bond.haddock
> doesn't exist or isn't a file
> bond-0.9.0.0: Warning: haddock-html:
> /home/travis/build/Microsoft/bond/build/compiler/doc/html/bond doesn't exist
> or isn't a directory
> bond-0.9.0.0: installed package info from too old version of Cabal (key field
> does not match id field)
> CMake Error at cabal_build.cmake:60 (message):

The Travis build is now using ghc 8.0.2 with cabal 1.22.9.0.

It may be that this combination [is not compatible](https://github.com/haskell/cabal/issues/3811).

**Comment by lalo** [comment]
Non-issue after commit 52dbdb0ba882748b1d5857e7c60791c346a8e889
