### ISSUE TITLE
C++ generated code: provide option for not generating apply function overloads

### ISSUE THREAD

**Issue by daniel-j-h** [Microsoft/bond#51]
Suppose I have a schema definition file M.bond.

    gbc c++ M.bond

in addition to

    M_reflection.h
    M_types.h
    M_types.cpp

bond automatically generates

    M_apply.h
    M_apply.cpp

Those two files are optional and not required. The "--apply" flag only let's me specify more protocols to create apply function overloads for. But there is currently no way to disable the generation of apply function overloads (except for removing them after each gbc invocation).

Thanks,
Daniel

**Comment by sapek** [comment]
Why do you need to remove the generated _apply.h/.cpp files rather than simply ignoring them?
