### ISSUE TITLE
Bond-Over-GRPC C++ release

### ISSUE THREAD

**Issue by eharshosh** [Microsoft/bond#510]
Hi,

Do you have an estimation on when a version that includes the Bond-Over-Grpc for C++ features will be released?

Thanks in advance,
Eitan.

**Comment by chadwalters** [comment]
The code for the C++ integration is in master now (https://github.com/Microsoft/bond/commit/4b960966686b9c220e5a15e8d5e69510d6ffcb84). We are working on a few things on the C# side before we make the 6.0 release. I estimate that should happen some time this week or early next week.

**Comment by chwarr** [comment]
The 6.0.0 release is live now. NuGet packages with the new .NET code and the new version of gbc are live. The GitHub release page for [6.0.0](https://github.com/Microsoft/bond/releases/tag/6.0.0) also has a pre-compiled Windows x64 of gbc.
