### ISSUE TITLE
Reason for public/protected constructor combination in c# generated code

### ISSUE THREAD

**Issue by Danie-Brink** [Microsoft/bond#519]
Is there a reason why the codegen creates a public paramerterless constructor that then calls a protected one with parameters?

Seems a bit redundant as the parameters passed to the protected constructor (fullname & name) aren't used and the default field values could just be set in the parameterless public constructor.

**Comment by chwarr** [comment]
You're seeing scaffolding for the deprecated `bond_meta::full_name` and `bond_meta::name` features. These constructor overloads are always generated, regardless of whether there are any `bond_meta` fields.

When `bond_meta` fields are present, [the `fullName` and `name` parameters are used](https://github.com/Microsoft/bond/blob/0236301fe809802ecd754d5d047288ef397f9c79/compiler/src/Language/Bond/Codegen/Cs/Types_cs.hs#L127-L134). It's implemented this way to handle inheritance properly. A `bond_meta` field in a base struct needs to be initialized with the name for the most derived struct being constructed, not just the name for the base.

Generation could be suppressed if two conditions are met:

1. the struct does not inherit from another struct and
    * the fields of the base struct may not be known at the time of code generation
1. the struct does not contain and `bond_meta` fields.

However, such a change would be a breaking change in the generated code (removal of a public/protected member).

A different approach, which is also a breaking change, that I like better would be to place the `bond_meta` functionality behind an opt-in gbc switch. The computation of the meta name values could then be moved to code in the Bond assembly (today, the generated code only depends on the Bond.Attributes assembly, and we'd like to keep it that way for the vast majority of cases).

Related issue: https://github.com/Microsoft/bond/issues/140

Hope this answers your questions.

**Comment by chwarr** [comment]
Please let us know if you have follow up questions. Closing for now.
