### ISSUE TITLE
[appveyor] Master branch passes but log shows error

### ISSUE THREAD

**Issue by lalo** [Microsoft/bond#526]
https://ci.appveyor.com/project/MicrosoftBond/bond/build/1.0.305/job/4y5w8nmtrhvcr2ma#L393

  Time Elapsed 00:02:21.58
          1 file(s) copied.
  '"gbc"' is not recognized as an internal or external command,
  operable program or batch file.
C:\projects\bond\cs\build\nuget\Common.targets(100,5): error MSB3073: The command ""gbc" c# --import-dir="C:\projects\bond\cs\build\internal\..\..\..\idl"  --jobs=-2 --namespace=bond=Bond --output-dir="obj\debug\net45\\."  @"obj\debug\net45\\bonddefaultcodegen.in"" exited with code 9009. [C:\projects\bond\cs\src\core\Bond.csproj]

**Comment by chwarr** [comment]
After [line 201 in appveyor.yml](https://github.com/Microsoft/bond/blob/d80983ac3f8c361f7befe741d23e5feb41e0131e/appveyor.yml#L201) we need to check the result of invoking msbuild by inspecting `$?`. There are other examples of doing this in the file, like on [line 285](https://github.com/Microsoft/bond/blob/d80983ac3f8c361f7befe741d23e5feb41e0131e/appveyor.yml#L285) after we do the "real" build for the flavor.
