### ISSUE TITLE
Compile error with GCC 

### ISSUE THREAD

**Issue by ramon-garcia** [Microsoft/bond#538]
While building the master version with GCC, the following error appeared:
`In file included from /devel/bond/cpp/inc/bond/core/parser.h:8:0,
                 from /devel/bond/cpp/inc/bond/core/apply.h:9,
                 from /devel/bond/cpp/inc/bond/core/bond.h:7,
                 from /devel/bond/build/cpp/bond/core/bond_apply.h:16,
                 from /devel/bond/build/cpp/bond/core/bond_apply.cpp:13:
/devel/bond/cpp/inc/bond/core/value.h: In member function ‘void bond::DeserializeElement(X&, const I&, const T&)::Deserialize::operator()(typename bond::element_type<T>::type&)’:
/devel/bond/cpp/inc/bond/core/value.h:644:57: error: non-template type ‘Deserialize’ used as a template
             this->element.template Deserialize<Protocols>(e);
                                                         ^
`

This looks like a limitation of GCC, though I tested it with GCC 4.9, 6.3.0 and 7.1

Attached a workaround.

[fix_gcc_core_value.diff.txt](https://github.com/Microsoft/bond/files/1168381/fix_gcc_core_value.diff.txt)

**Comment by ramon-garcia** [comment]
I confirm that this is a bug in GCC.

A testcase fails with GCC and succeeds with Clang (checked by testing in https://gcc.godbolt.org/ )

**Comment by chwarr** [comment]
Thanks for the heads up.
@ara-ayvazyan, you're C++ standards knowledge if better than mine. Do you have time to come up with a cross-compiler, cross-version fix, even if there's a bug in GCC here?

(GCC *may* be following the standard, and Clang and MSVC are missing this one. Or, it may very well be a bug in GCC...)

**Comment by ara-ayvazyan** [comment]
Sure, I'll take a look.

**Comment by ara-ayvazyan** [comment]
Here is a shorter repro:
``` C++
template <typename T>
void foo()
{
    struct X
    {
        void bar()
        {
            this->var.template X<T>();
        }

        T var;
    };
}
```
I'm not sure which compiler is correct (will need to contact some C++ language lawyer 😃), but this can be resolved by adding `X::` just before the `template` keyword:
``` C++
this->var.X::template X<T>();
```
Renaming the `struct X` is probably safer.

**Comment by ramon-garcia** [comment]
@chwarr Yes, I posted the bug in GCC bug tracker.

I couldn't figure out that the name clash between Deserialize struct and Deserialize method is the cause. In this case, renaming the struct is safe solution. Please consider this fix. Even if GCC is wrong, it is the mainstream compiler in Linux. It would take years until new releases include GCC 8 with this bug fixed.

**Comment by chwarr** [comment]
@ramon-garcia, agreed. Let me put together a PR.
