### ISSUE TITLE
Deserialize objects with incomplete or inexisting type information

### ISSUE THREAD

**Issue by ramon-garcia** [microsoft/bond#585]
This is to request a feature to be able to deserialize an object with no type information.

The result should be a handle, and a RuntimeSchema that describes the type information, as found in the stream.

Of course, this does make sense only with serialization formats that include tagging.

Once one obtains an deserialized object, one should be allowed to:
1) serialize again, with no loss of data
2) cast it to a class, and the cast should be valid if the serialized data is actually an instance of this class. In order words, the layout of a deserialized object with no type information should be compatible with the layout of a class generated with the bond compiler.
3) dynamically query a field, using the RuntimeSchema.

I have some code that does more or less this.

There are some challenges. Should we use system containers (list, map) of not? There is no way in C++ to manage containers without knowning at compile time the type of the contained objects. One cannot, in a portable way, navigate a std::map without compiling for a particular type of keys and values. Of course, one can write code that navigates a std::map, if one knows the layout. But that means writting specific code for each compiler/platform.

I solved this writting a custom map. That that means that one must pass special flags to the bond compiler, if one wishes to enjoy compatibility between compiled objects and runtime deserialized objects.

In spite of the difficulties, I think that this would be a great enhacement to bond. It would make it safe to extend types, without the risk of losing data in intermediate object handlers.

**Comment by chwarr** [comment]
There's a lot here to unpack, and I don't have time right now to go into much depth, so a few quick comments.

> It would make it safe to extend types, without the risk of losing data in intermediate object handlers.

This sounds like what the [Merge APIs](https://microsoft.github.io/bond/manual/bond_cpp.html#merge) are designed to do. Have you tried them? What worked and didn't work?

> There is no way in C++ to manage containers without knowning at compile time the type of the contained objects.

Did you consider containers of variants? The static type would always be known, but not the runtime type.

> cast it to a class, and the cast should be valid if the serialized data is actually an instance of this class. In order words, the layout of a deserialized object with no type information should be compatible with the layout of a class generated with the bond compiler.

What kind of cast? A `dynamic_cast<>`? `reinterpret_cast`? I'm not sure how to implement something like this in C++. Can you sketch an implementation?

**Comment by ramon-garcia** [comment]
1) The Merge API requires having a copy of the serialized representation along with a partial deserialized object. And other problems remain unsolved, such as the ability of finding or setting a field by name  (in case a partial or complete RuntimeType of the object is available).
2) Storing a container of pointers would be a solution. But anyway, the problem still happens: bond source would be compiled with special flags so that the containers are aliased to an implementation that is actually a container of pointers.
3) A normal static_cast. Note that the result of the deserialization would be a void* and a RuntimeSchema, The RuntimeSchema contains the runtime information. One can check it before casting to another object.

**Comment by jnm2** [comment]
Coming from a C# perspective, I want to be able to deserialize in an assembly that has no reference to the type used in a separate assembly to serialize the data.

That is to say, I want to be able to examine the data similarly to this strawman:

```cs
IDynamicBonded root = Deserialize.From(new CompactBinaryReader<InputStream>(inputStream));

// Ability to fully examine without having to serialize to a known type
Console.WriteLine($"Root ({root.TypeDef}):");
foreach (var field in root.Fields)
{
    Console.WriteLine($"{field.Name}: {field.Value} ({field.TypeDef})");
}

// Maybe APIs like this, too
int fieldValue = (int)untyped["fieldName"];
IDynamicBonded nestedStruct = untyped["nestedStruct"]["doubleNested"];
```

Newtonsoft.JSON has a very similar concept with their JObject API. The .NET BCL also has this in the XNode API.

**Comment by ramon-garcia** [comment]
@jnm2 Bond serialized data does not contain field names. Fields are just numbered with tags.
(And with the SimpleBinary, not even that).

**Comment by jnm2** [comment]
Oh, I see. I was thinking the tagged format would include that.

Are the names are included if the schema is sent over the wire manually? I see the struct name itself:

https://github.com/Microsoft/bond/blob/bd4b46e78a82dd3a38b52b00233a1a22047014d2/examples/cs/core/runtime_schema/program.cs#L16-L30

Looks like something I'd have to write myself: first deserialize the schema, then use that and a SimpleBinaryReader to construct a document object model.

Sorry for interrupting!

**Comment by chwarr** [comment]
Yes, a SchemaDef contains the field names as well as the struct names.

When serializaing SchemaDef instances, be sure to use a tagged protocol--and *not* Simple Binary--so that you can handle any changes to SchemaDef itself.

**Comment by chwarr** [comment]
This enhancement is not something that we need for our use of Bond at Microsoft, and we have no plans to implement it.

Anyone is welcome to [contribute](https://github.com/microsoft/bond/blob/master/CONTRIBUTING.md) this feature. Should you want to do that, please create an issue with your proposed design.

Thus, I'm going to close this as won't fix. It can be re-opened if a design materializes.

**Comment by ramon-garcia** [comment]
Looks fair to me.
