### ISSUE TITLE
question:  how to rename struct in bond schema

### ISSUE THREAD

**Issue by dbykat** [Microsoft/bond#595]
We're contemplating renaming a custom struct in our *.bond schema.   We use Bond's CompactBinary protocol.  I see the Schema Evolution rules documented here, but it doesn't address renaming a custom struct:  https://microsoft.github.io/bond/manual/bond_cs.html#schema-evolution

We looked into using an alias at the top of the file, but we're encountering compile time errors when aliasing a custom struct.  Do aliases only support builtin Bond types such as int64 ?   If so, what strategy would you recommend for renaming a custom struct?

Thanks!

**Comment by chwarr** [comment]
The name of the struct is not encoded when using Compact Binary, Simple Binary, Fast Binary, or Simple JSON. Changing the struct name will not invalidate any serialized data, but you'll need to fix up any references to it in code.

One thing to watch out for is any use of `bond.SchemaDef`: the name and qualified name of the struct in SchemaDef instances will change. Depending on how you are using SchemaDef instances, this may or may not be a problem. (If you are using SchemaDef to deserialize Simple Binary, this will still work, as, again, the name isn't encoded in Simple Binary.)

Also, if you are using the deprecated `bond_meta::name` and `bond_meta::full_name` fields, this will cause these fields' values to change. The code on the reading side will likely need to be edited to handle both the old name and the new name.

The struct name is encoded in Simple XML, but the reader doesn't actually check the name for structs, so existing data deserializes fine. Other non-Bond consumers of this XML will likely be broken.

Hope this helps.

**Comment by chadwalters** [comment]
To answer the question about aliases and type converters, you can only convert scalars, blobs, and strings.

**Comment by chwarr** [comment]
I'm going to close this issue. Please re-open it if something hasn't been addressed.
