### ISSUE TITLE
Question: random access to elements

### ISSUE THREAD

**Issue by DanielFabian** [Microsoft/bond#599]
I am trying to write some sort of header where I may have a list of offsets. E.g. 1 offset per record. 

How could I implement a schema that is conceptually a `vector<int64>` or at least `blob` in such a way, that I can address individual elements without reading the lot?

The reason is, I am trying to write a big data stream that may be, say, 3-4TB and may consist of, say, 10 billion records. For this stream, just the header would be some 80GB. We really need to avoid deserializing the lot.

**Comment by chadwalters** [comment]
Bond expects to deserialize entire objects and that is fairly deeply baked in. I think it would be best to build your index header outside of Bond. Each record can be serialized/deserialized individually using Bond, but the index and the collection of records would not be Bond objects themselves. Does that make sense?

**Comment by DanielFabian** [comment]
Yes, it does. That was my current design, actually. Just wanted to make sure that I am not missing anything. Thanks
