### ISSUE TITLE
Does bond support platforms with different endianness?

### ISSUE THREAD

**Issue by AlphardWang** [Microsoft/bond#610]
I am working with C++, and didn't find much description about endianness in user manual.
After search in code, I found it seems bond will assert endianness as little-endian in C#. But in C++, there is no such assertion.

So is bond only be able to used across platforms with same endianness?

**Comment by chadwalters** [comment]
Bond is currently only tested on little-endian systems. The changes to make it work on a big-endian system are believed to be small but without compelling use cases and a good way to include big-endian systems in our CI mechanism, we haven't done that work at this time.

**Comment by AlphardWang** [comment]
Thanks. It seems to be fine in my current scenario.

**Comment by chadwalters** [comment]
I imagine that if you are sharing between only big-endian systems, it will work although the encoding won't technical adhere to the Bond specification and will not be compatible with serialization done on little-endian systems. What big-endian platforms are you working with? Are there any public CI servicesfor them?

**Comment by AlphardWang** [comment]
Sorry for late response. I am not working on big-endian systems (actually I am not sure if my program will run on big-endian systems). I just want to understand if I need to check the endian to avoid unexpected errors.
