### ISSUE TITLE
Any plans for C++11 version without boost dependencies

### ISSUE THREAD

**Issue by alexezh** [Microsoft/bond#62]
Is there any plans to implement subj? Boost dependencies seems small and should be covered in C++11?

**Comment by sapek** [comment]
Not currently. The dependency on Boost goes beyond things that got included in the standard in C++11. In particular Bond uses [`mpl`](http://www.boost.org/doc/libs/1_58_0/libs/mpl/doc/index.html) and [`variant`](http://www.boost.org/doc/libs/1_58_0/doc/html/variant.html).
