### ISSUE TITLE
Could not load file or assembly Bond.IO, Version=1.0.0.0...

### ISSUE THREAD

**Issue by mrctito** [Microsoft/bond#622]
Dear sirs,

I´am trying to use Bing Speech library service to translate speech to text in my ChatBot, but this error happens in method "RecognizeAsync" of class "SpeechClient". 

Could not load file or assembly Bond.IO, Version=1.0.0.0, ... or one of its dependencies. The located assembly manifest definition does not match the assembly reference.

All nuget packages are up to date, as is my Visual Studio 2017 Enterprise.

Thank you for any help.

**Comment by chwarr** [comment]
Since this issue has been closed, I assume you were able to resolve it on your own. Please re-open if not.
