### ISSUE TITLE
Grpc generated file in c# does not add using System.Collections.Generic

### ISSUE THREAD

**Issue by acgull** [Microsoft/bond#623]
When using a generic method in a service if the generic parameter is a collection the generated code fails to compile because gbc doesn't add using System.Collections.Generic; to generated file.

To reproduce - compile the following file [generic_service.txt](https://github.com/Microsoft/bond/files/1327138/generic_service.txt) with the follwing command:
`gbc.exe c# --grpc generic_service.txt` (renamed to txt so I can upload here)

**Comment by chwarr** [comment]
Thanks for the report. I see the problem. I'm working on a fix and regression tests.
