### ISSUE TITLE
Visual Studio 2017 .NET Core

### ISSUE THREAD

**Issue by niesmo** [Microsoft/bond#634]
I'm trying to use Bond with .NET Core and Visual Studio 2017 but I cannot get the codegen to appear as a build action.
here are the installed packages:
![image](https://user-images.githubusercontent.com/5835438/31280524-98f72672-aa7a-11e7-9a31-28a3dec5c8d3.png)
There is no "BondCodegen" option under build action in properties for the .bond files 😢 
Is there something that I've missed during setup or is there no support for VS 2017 or .NET Core?
![bitmoji](https://render.bitstrips.com/v2/cpanel/9954519-356990515_1-s4-v1.png?transparent=1&palette=1&width=146)
Thanks

**Comment by chwarr** [comment]
Try to unload and reload the solution. That would often fix this problem when using Visual Studio 2013 and 2015.

If that still doesn't work, I think we're hitting an [unimplemented feature in the new .NET Core project system](https://github.com/dotnet/project-system/issues/113). Until that is implemented, you'll need to edit the .csproj file manually to add the items:

```
<ItemGroup>
    <BondCodegen Include="foo.bond" />
</ItemGroup>
```

It _may_ be possible to make this work using `ProjectSchemaDefinitions`. I opened [an issue to capture the details](https://github.com/Microsoft/bond/issues/636). Not sure whether it will work, or whether we need to wait for https://github.com/dotnet/project-system/issues/113 to be implemented.

**Comment by niesmo** [comment]
Thanks for your quick response!

Adding <BondCodegen Include="file.bond" /> for every .bond file worked ✔️
I also had to exclude the location where the compiled classes were located (maybe that's obvious, but I didnt know).

My .csproj looks like this now 
```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <BondOptions>--using="decimal=decimal"</BondOptions>
    <BondOutputDirectory>CompiledBondClasses</BondOutputDirectory>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="CompiledBondClasses\**" />
    <EmbeddedResource Remove="CompiledBondClasses\**" />
    <None Remove="CompiledBondClasses\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Bond.Core.CSharp" Version="6.0.0" />
    <PackageReference Include="Bond.CSharp" Version="6.0.0" />
    <PackageReference Include="Bond.Runtime.CSharp" Version="6.0.0" />
  </ItemGroup>

  <ItemGroup>
    <BondCodegen Include="Schemas\bond.bond" />
    <BondCodegen Include="Schemas\bond_const.bond" />
    <BondCodegen Include="Schemas\type_1.bond" />
    <BondCodegen Include="Schemas\type_2.bond" />
  </ItemGroup>
</Project>
```

![bitmoji](https://render.bitstrips.com/v2/cpanel/9941638-356990515_2-s4-v1.png?transparent=1&palette=1&width=106)
