### ISSUE TITLE
Build Haskell with customized proj file instead of vcxproj file

### ISSUE THREAD

**Issue by hcoona** [Microsoft/bond#641]
Use `vcxproj` file compile Haskell codes lead to a hard dependency to Visual C++ which is not available on other platform now. I suggest to use a customized `proj` file instead to eliminate this unnecessary dependency.

Related PR #633

**Comment by hcoona** [comment]
I didn't know the impact to developer. Dropped vcxproj, the developer cannot list the Haskell files in Visual Studio. If I use `csproj`, they can list them but without "Virtual Folder" function.

**Comment by chwarr** [comment]
It's fine if the .hs files don't show up in Visual Studio when using the cs.sln.

**Comment by chwarr** [comment]
Fixed in commit 0822d27.
