### ISSUE TITLE
Is there way to compile bond without boost?

### ISSUE THREAD

**Issue by usvoyager** [Microsoft/bond#643]
Anyway we can build bon sources without boost?

**Comment by chwarr** [comment]
No: we rely on Boost to abstract compiler, platform, and C++ standard differences. We also use things like `boost:mpl`, `boost::variant`, and `boost::optional`.

Only Boost headers are needed, however, for using Bond serialization/deserialization. If you want to build and run the tests, you'll need some of the Boost libraries as well. On Windows, by default, when Boost is compiled it automatically tried to link with its libraries. This can be suppressed by defining [BOOST_ALL_NO_LIB when compiling](https://github.com/Microsoft/bond/blob/65ce77380099ab9bff400b78043302dab8a1e1b0/cmake/Config.cmake#L140-L141).

Some more details: https://github.com/Microsoft/bond/issues/62

**Comment by TPSResearch** [comment]
sounds like if you got bond up-to-date with the latest Microsoft compiler you could be on the road to ridding yourself of the massive boost dependency.

**Comment by chwarr** [comment]
Possibly. Bond already works with MSVC 2017. It's less about Bond working with the latest and greatest and more about what the consumers of Bond are ready and able to use. For now, that includes older C++11 only compilers like MSVC 2013, Clang 3.x, and GCC 4.x.

For my additional information, can you list/point to the problems you're having with Boost? This will help us make a more informed decision when we're in a position to re-evaluate (likely in a year or two).

**Comment by TPSResearch** [comment]
@chwarr We don't have a problem with Boost, per se. A number of years ago we examined our use of it and found that we only used a few features which were pretty easy to work around. Given that boost is half a Gig in size it was decided to remove our dependency upon it. Today we make the standard library the first place to go before using features from open source libraries.

**Comment by chwarr** [comment]
Thanks, @TPSResearch.
@usvoyager: if your question has been answered, can we close this issue?

**Comment by chwarr** [comment]
Having heard nothing more, closing.
