### ISSUE TITLE
Why are all protocol writers not implemented as classes?

### ISSUE THREAD

**Issue by fedora1980** [Microsoft/bond#67]
Looking at the Bond code I see all implementations of IProtocolWriter as struct implementations. Is there a reasoning for this?

And then in the ProtocolWriter.cs there is a comment stating something about inlining .. are you stating that if the implementation of an IProtocolWriter is made a class this optimization goes away?

https://github.com/Microsoft/bond/blob/556ce21603a10759a6f2678b2ea14e4d0f659ef2/cs/src/core/expressions/ProtocolWriter.cs#L59

**Comment by sapek** [comment]
Yes.
