### ISSUE TITLE
Generate partial classes for GRPC clients

### ISSUE THREAD

**Issue by FDUdannychen** [microsoft/bond#672]
I suggest bond_over_grpc generates partial classes for clients (like protocol buffers), which allows adding properties/methods/interfaces to the clients.

`public (partial) class FooClient : global::Grpc.Core.ClientBase<FooClient>`

Currently a workaround is inheritance

`public class MyFooClient : FooClient`

The name of `MyFooClient` and its namespace are quite tricky.

**Comment by chwarr** [comment]
No real concerns from me. If we start to generate a name that clashes with a name used in a partial class, that will cause the customer code to fail to compile, but there's no good way around that, and inheritance has a similar problem. (Types already work this way, but they're less likely to churn.)

Is this something you want to contribute?

* [ ] Update templates in Haskell
* [ ] Re-generated golden files
* [ ] Add unit test demonstrating & testing new behavior
* [ ] Update changelog

**Comment by chwarr** [comment]
Given that Bond-over-gRPC [is being deprecated and removed](https://github.com/microsoft/bond/issues/1131), I'm going to close this as "Won't Fix"
