### ISSUE TITLE
Bond build failed with error MSB6006: "cmd.exe" exited with code 9009

### ISSUE THREAD

**Issue by shanshan0309** [Microsoft/bond#691]
I build Bond with Visual studio 2017 compiler on Windows Server 2016, but it failed with error MSB6006: "cmd.exe" exited with code 9009. This issue can be reproduced from master revision [d157d75](https://github.com/Microsoft/bond/commit/d157d7598c2bb9c1d0a91e9d5c71f9508041916b). Could you help have a look about this issue? Thanks in advance!

**Failures:**
CustomBuild:
  Building Custom Rule D:/Bond/src/java/gradle-plugin/CMakeLists.txt
  CMake does not need to re-run because D:/Bond/build_x64/java/gradle-plugin/CMakeFiles/generate.stamp is up-to-date.
  Generating build/java/gradle-plugin
  'GRADLE_EXECUTABLE-NOTFOUND' is not recognized as an internal or external command,
  operable program or batch file.
C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(171,5): error MSB6006: "cmd.exe" exited with code 9009. [D:\Bond\build_x64\java\gradle-plugin\gradle-plugin.vcxproj]

**Repro steps:**
1. Open VS2017 x64 Native tools command tool
2. git clone --recursive https://github.com/Microsoft/bond.git D:\Bond\src
3. cd D:\Bond
4. mkdir build_x64 && pushd build_x64
5. cmake -G "Visual Studio 15 Win64" -DCMAKE_SYSTEM_VERSION=10.0.15063.0 ..\src
6. msbuild bond.sln /p:Configuration=Release;Platform=x64 /t:Rebuild

**Comment by ara-ayvazyan** [comment]
Looks like the readme is missing instructions on how to setup for building Java (#692). If you do not need Java, then can you try to unload related projects from the solution (#693)?

**Comment by tstein** [comment]
With the above change, Java targets won't be created unless you explicitly ask for them when you run the `cmake` configure step (with `-G`). It may be enough to re-run `cmake -G` to fix the issue in your existing build, but I recommend that you remove your entire `D:\Bond\build_x64` and start fresh. Please let us know if the problem isn't resolved.

**Comment by shanshan0309** [comment]
@tstein, thank you so much for fixing this issue. I've verified your fix works well.
