### ISSUE TITLE
SimpleJsonParser should check the FloatHandling setting

### ISSUE THREAD

**Issue by mburbea** [Microsoft/bond#7]
In SimpleJsonParser::
```csharp
            else if (scalarTokenType == JsonToken.Float)
            {
                convertedValue = Expression.Convert(Reader.Value, typeof(double));
            }
```
If a user changes floathandling to decimal this will throw an invalid cast exception as you tried to unbox a decimal to a double. You are not safe by not taking a JsonSettings option as a user may simply override the default settings for Json.net. 

Json.net does offer on the JsonReader some (very very few unfortunately) helpers which can be used as an optimization as they will avoid boxing. They will produce a `Nullable<T>` but that's still cheaper than boxing and unboxing.

**Comment by sapek** [comment]
I couldn't find a way to modify default settings for `JsonTextReader`. It seems like this feature is only supported for `JsonConvert`, and even then the default is still opt in. So looks like Bond is not affected by this. Am I missing something?

**Comment by mburbea** [comment]
You actually can change them on `JsonTextReader`. I thought they were copied from the DefaultSettings but I guess that only affects things like JsonSerializer and JsonConvert.

However, there is no requirement that I use your SimpleJsonReader, I presumably could implement IJsonReader which is a pretty easy interface to implement, if I want to add my own converters or whatever. It's not a big change::

```csharp
string json = @"0.0";
using(var StringReader = new StringReader(json)){
     using (var jsonReader = new JsonTextReader(stringReader)){
        jsonReader.FloatParseHandling = FloatParseHandling.Decimal;
        jsonReader.Read();
        Console.WriteLine(jsonReader.Value.GetType()); // prints Decimal
}
}
```

**Comment by sapek** [comment]
Well, but then you would be doing The Wrong Thing (TM) and you deserve an exception :-). Since the floating point values are represented by `double` in Bond generated types setting `FloatParseHandling.Decimal` doesn't serve any purpose. No reason to add performance penalty for everyone to prevent that.
