### ISSUE TITLE
Please add examples for netstandard2.0 library

### ISSUE THREAD

**Issue by hanabi1224** [Microsoft/bond#704]
Thanks!

**Comment by chwarr** [comment]
At the moment, the MSBuild projects used for the examples haven't been migrated to the new MSBuild 15 syntax that is used with .NET Core projects. Issue https://github.com/Microsoft/bond/issues/383 is open to track this migration work.

The existing NuGet packages and targets work, but they don't automatically run codegen on the .bond files in the same directory, like .cs files are automatically compiled. Issue https://github.com/Microsoft/bond/issues/636 is open to investigate whether this integration can be done.

A minimal .NET Core 1.1 App .csproj ends up looking like the following. This should be adaptable to a .NET Standard 2.0 library, but I haven't tried. Please report back if this doesn't work for .NET Standard 2.0.

```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netcoreapp1.1</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <!-- Must manually add files to the BondCodegen item -->
    <BondCodegen Include="foo.bond" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Bond.CSharp" Version="7.0.1" />
  </ItemGroup>

</Project>
```

Note that the NuGet packages don't have an explicit netstandard20 target framework. I expect netstandard16 to just work. If not, please let us know.

**Comment by chwarr** [comment]
I'm going to close this. Please re-open if there's anything more.

**Comment by cfogg6** [comment]
In case anyone else tries to use this suggestion and runs into a "Duplicate BondCodegen items were included" error, note that including the most recent Bond.CSharp versions automatically runs bondgen on bond files in the project, so don't include the BondCodegen ItemGroup in this thread's example or you'll add it twice and run into this error.

(Remove this)
<ItemGroup>
    
    <BondCodegen Include="foo.bond" />
  </ItemGroup>

**Comment by chwarr** [comment]
Thanks, @cfogg6! I've updated the example above to reflect this.
