### ISSUE TITLE
grpc++ can't be linked

### ISSUE THREAD

**Issue by FDUdannychen** [Microsoft/bond#734]
With the steps in README, I successfully set it up on Ubuntu 16.04. However my program fails to compile at the last step:
```
/usr/bin/ld: cannot find -lgrpc++
/usr/bin/ld: cannot find -lgrpc
```
The CMake script of this step:
```
file(GLOB HOST_SOURCES ${PROJECT_SRC_DIR}/host/*)
add_executable(server ${HOST_SOURCES})
target_link_libraries(server PRIVATE mylib grpc++ grpc ${CMAKE_THREAD_LIBS_INIT} ${Boost_LIBRARIES})
```
I can see directories named bond/grpc/grpc++ in `/usr/local/include`, and `gbc` (even `protoc`) command is available. I can't find any libgrpc.so or libgrpc++.so (or .a files), I think it should be copied? 

**P.S** My workaround is going to `myproj/thirdparty/bond/thirdparty/grpc` and follow the [grpc install steps](https://github.com/grpc/grpc/blob/master/INSTALL.md), now `/usr/local/lib` has corresponding `.so` files and my project compiles.

**Comment by FDUdannychen** [comment]
By the way, I want to add `bond` as a third-party component (as a git submodule) of my project. Since my project is also built by `CMake/Make`, I want a `click-once` build. However, my program fails to compile because `gbc` and bond includes are not available, which means my project can only be built after bond's `CMake` and `sudo make install` finishes. Currently my workaround is adding a `init.sh` script, where bond is built and installed. Then I can CMake/Make my own project. I don't know if it's the correct way, it's very appreciate if you guys can give an advice.

**Comment by tstein** [comment]
We haven't done the work to make it possible to consume bond the way you're trying to. You have to make your build process aware of bond as a separate step (which you have, through your `init.sh`).

**Comment by chwarr** [comment]
Would you be able to contribute the needed changes to the Bond CMake files so that it can be included in another CMake-based project without needing installation?

**Comment by FDUdannychen** [comment]
@chwarr I'm afraid I can't. I'm pretty new to both C++ and CMake. Still learning...
