### ISSUE TITLE
Generate runtime schema from .bond file

### ISSUE THREAD

**Issue by sapek** [Microsoft/bond#75]
The compiler command line utility and compiler library should allow generating marshaled [runtime schema(s)](https://microsoft.github.io/bond/manual/bond_cs.html#runtime-schema) from a .bond file. This would be useful for building tools that consume `.bond` file schema descriptions and use runtime schema to obtain schema metadata, e.g. to perform transcoding from binary to JSON.

**Comment by jasonwilliams200OK** [comment]
:+1:
Does this mean at some point we will be able to create an extension-only, name-less files in Windows File Explorer at some point in future? Without opening a notepad via `run` (`notepad .bond`) and without getting:

![image](https://cloud.githubusercontent.com/assets/2031765/9493863/5071a0a0-4c0b-11e5-8342-d71c414ed288.png)

**Comment by jack-pappas** [comment]
@jasonwilliams200OK You can already create extension-only filenames in Windows explorer. Create the file and add a trailing ``.`` to the filename (e.g., if you want ``.gitignore`` type ``.gitignore.``). Windows will remove the trailing ``.`` from the filename once the rename operation is applied (when you hit Enter or click the mouse somewhere else on the screen).

Anyway, I think @sapek meant ``.bond`` as in "filenames ending with ``.bond``", e.g., ``foo.bond``.
