### ISSUE TITLE
Remove usages of sprintf from C++ implementation

### ISSUE THREAD

**Issue by Porges** [Microsoft/bond#78]
This causes warnings when building:

    warning C4996: 'sprintf': This function or variable may be unsafe. Consider using sprintf_s instead.

In particular, `sprintf` is [a banned function in SDL](https://msdn.microsoft.com/en-us/library/bb288454.aspx).

**Comment by sapek** [comment]
`sprintf_s` is not a standard function. `std::snprintf` is only available in C++11 and for example VC12 doesn't support it.

**Comment by Porges** [comment]
I think even `snprintf` is banned by SDL. Could we conditionally upgrade to using `sprintf_s` if MSVC is detected?

**Comment by Porges** [comment]
Potential fix: https://github.com/Porges/bond/commit/9c29ed6c7c2b041231d0cab33341903f4b457630

**Comment by sapek** [comment]
I don't want to add conditional code with proprietary extensions. A better solution is to get rid of sprintf altogether. It is an overkill anyways since we only depend on it to convert integers to string.

**Comment by jasonzio** [comment]
Always the better choice for simple conversions. For complex conversions, that’s what std::ostringstream is for.

**Comment by Porges** [comment]
Would it be sane to just replace the custom `basic_string_stream` class with the std one? Then this could be avoided entirely - assuming there's not a strong reason to keep it. Does it exist for performance concerns/compatibility?

**Comment by sapek** [comment]
Performance.

**Comment by Porges** [comment]
OK. I guess I can just switch on `_CRT_SECURE_CPP_OVERLOAD_STANDARD_NAMES` anyway ☺
