### ISSUE TITLE
Compilation error in macOS 10.13.3: std::bad_alloc not defined

### ISSUE THREAD

**Issue by SoyYoRafa** [Microsoft/bond#786]
Hi,

cpp/src/bond/core/value.cpp wouldn't compile because it can't find bad_alloc in namespace std due to include cpp/inc/bond/protocol/detail/simple_array.h. Simply add 
`#include <new>` to simple_array.h to fix compilation issue.

If you care about my compiler:
g++ --version
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 8.1.0 (clang-802.0.38)
Target: x86_64-apple-darwin17.4.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

**Comment by tstein** [comment]
Thanks for the heads-up. :) I've opened a PR to resolve this.
