### ISSUE TITLE
Pass "object" in the struct - Interesting problem

### ISSUE THREAD

**Issue by NYProgrammer** [Microsoft/bond#794]
I have a structure in .bond file...

```
struct RemoteObject <T>
{
0: uint32 MessageId;
1: T InnerObject
}
```

I serialize `RemoteObject<>` objects and then I send this object on a socket .... on the other side, I want to deserialize this RemoteObject.

However, the problem I face is that on the receiving side I don't know the Type of the InnerObject because I wrote a framework code that simply wants to un-pack this RemoteObject and then based on the MessageId, I want to forward this to a handler object that will know the type of InnerObject.
On Sending Side, I can use a specific type like `RemoteObject<MyObject>` but on the receiving side, on the framework,I don't want to know about the "MyObject" I want to unpack this object and then forward it to another handler that actually does know the type.
If I use `RemoteObject<object>` and then stuff my MyObject type in the RemoteObject, I get an error on the "Serialize" method below...I get Key not found like error..

Any help would be appreciated.

Here is my code for serializing and deserializing... When I call the Serialize with "object" as the template for RemoteObject, I get an error.

```
  public class BondSerializerDeserializer : ISerializerDeserializer
    {
        public static BondSerializerDeserializer Instance => new BondSerializerDeserializer();
        public byte[] Serialize(object objectToSerialize) => Serialize<object>(objectToSerialize);
        public T DeSerialize<T>(byte[] bytesReceived)
        {
            InputBuffer inputBuffer = new InputBuffer(bytesReceived);
            SimpleBinaryReader<InputBuffer> reader = new SimpleBinaryReader<InputBuffer>(inputBuffer);
            Deserializer<SimpleBinaryReader<InputBuffer>> deserializer =
                new Deserializer<SimpleBinaryReader<InputBuffer>>(typeof(T));
            T receviedObject = deserializer.Deserialize<T>(reader);
            return receviedObject;
        }
        public byte[] Serialize<T>(T objectToSerialize)
        {
            OutputBuffer outputBuffer = new OutputBuffer();
            SimpleBinaryWriter<OutputBuffer> writer = new SimpleBinaryWriter<OutputBuffer>(outputBuffer);
            Serializer<SimpleBinaryWriter<OutputBuffer>> serializer =
                new Serializer<SimpleBinaryWriter<OutputBuffer>>(typeof(T));
            serializer.Serialize(objectToSerialize, writer);
            byte[] data = new byte[1000];
            ArraySegment<byte> dataBytes = new ArraySegment<byte>(data);
            writer.WriteBytes(dataBytes);
            Console.WriteLine(outputBuffer.Data.Count);
            return outputBuffer.Data.ToArray();
        }
    }
```

**Comment by lalo** [comment]
Here is some help.

First of all this is a great situation to use Bonded. Here is the documentation https://microsoft.github.io/bond/manual/bond_cs.html#understanding-bondedt

In your example you would end up with something like this:

bondFile.bond
```
struct RemoteObject
{
    0: uint32 MessageId;
    1: bonded<bond.Void> InnerObject
}

struct ExampleFoo
{
    0: uint32 A;
    1: uint32 B;
    2: uint32 C;
    ...
}
```

bond.Void is an empty struct https://github.com/Microsoft/bond/blob/master/idl/bond/core/bond.bond#L12 which in combination with bonded will be able to serialize and deserialize correctly depending on which deserializer you use.

In your code you would end up with something like this (pseudo-code)

```
HandleRemoteObject(byte[] payload)
{
    RemoteObject ro = Deserialize(payload);
    switch(ro.MessageId)
    {
        case MESSAGE_ID_FOO:
            fooHandler(ro.InnerObject.Convert<ExampleFoo>())
            break;
        case ...:
            ...
    }
}
```
Convert is part of IBonded https://github.com/Microsoft/bond/blob/master/cs/src/core/Bonded.cs#L32

In fooHandler you will have to deserialize as ExampleFoo. See this example for a similar problem with a sort of similar solution. https://github.com/Microsoft/bond/blob/master/examples/cs/core/polymorphic_container/program.cs

Other suggestions:
- SimpleBinary is not recommended if there is network communication since a change in schema would be breaking or if you plan on persisting data (to files or to databases) since if the schema changes it will not be backwards compatible. You can still use SimpleBinary and solve those situations if they apply to you by keeping track of the SchemaDef when serializing.
- We recommend the usage of ArraySegment instead of byte[] to avoid a performance hit by the implicit copying of the byte arrays.
- We offer Bond-over-gRPC which provides a solution for network message passing. More about it here: https://microsoft.github.io/bond/manual/bond_over_grpc.html

Thanks and I'll keep this open in case you follow up with more questions.

**Comment by lalo** [comment]
You can either import the file bond.bond in your bond file `import "bond/core/bond.bond"` or define your own empty void struct and replace bond.Void with Void. This is the definition you want:
```
// Empty schema with no fields
struct Void
{
}
```

Ok, in the example I proposed fooHandler would be expecting an `IBonded<ExampleFoo>` and that is why we need a convert before sending it. fooHandler can be a method in the same class or any other class. If I understand correctly what you propose, fooHandler would receive a` IBonded<Void>` and inside that fooHandler you can call `Convert<ExampleFoo>` and then deserialize. Both are correct approaches.

For serializing set InnerObject to any a Bonded of your target object for example a Bonded<ExampleFoo> which is constructed like

```
ExampleFoo foo ...
var bondedFoo = new Bonded<ExampleFoo>(foo);

//or

var bondedFoo = new Bonded<ExampleFoo>(new ExampleFoo {A = ..., ...));

//then
ro.InnerObject = bondedFoo;
```

you can then serialize as normal ro. The information of ExampleFoo will not be lost and will be 'recovered' when you do the Convert<ExampleFoo>.

I recommend you to understand this example (in particular the struct Example which contains a vector of Shapes, yet it is used by Circle and Rectangles), https://github.com/Microsoft/bond/blob/master/examples/cs/core/polymorphic_container/program.cs

and understand the bond file of that project:
https://github.com/Microsoft/bond/blob/master/examples/cs/core/polymorphic_container/schema.bond

You can actually play around with that example, remove the inheritance and try to recreate the situation you want in your project by introducing a Void a struct and copying the RemoteObject I proposed and using it with Circle and Rectangle (without the inheritance) . You can download the code and compile and run that particular example.

**Comment by NYProgrammer** [comment]
Before reading your response I did exactly what you recommended.... I used following - 
struct BaseObject
{
}
struct RemoteObject
{
    0: uint32 MessageId;
    1: bonded<BaseObject> InnerObject
}

struct OtherObject
{
    0: string Data;
    1: int32 Identifier
}

However, when I tried to Convert<OtherObject> on the IBonded<InneerObject>...
I will post my one class that I did all this on tomorrow...
I am really now curious what am I missing....

Meanwhile, I got my example working by using following - 



struct RemoteObject
{
    0: uint32 MessageId;
    1: vector<uint8>  InnerObject
}
I don't really like this...Not elegant.
Would like to get the other example working

**Comment by lalo** [comment]
Ok, I ran it myself. I had a misunderstanding with the Bonded API, which I'll check on with the team about the details. For now you have two options:

this one is the first: (this code I compiled and ran, it should work)
```
            var ro = new RemoteObject();
            ro.MessageId = 1;
            var ob = new OtherObject {Data = "Hello", Identifier = 1};

            var outputOb = new OutputBuffer();
            var writerOb = new CompactBinaryWriter<OutputBuffer>(outputOb);

            //we have to serialize the OtherObject to construct a Bonded backed with a payload
            Serialize.To(writerOb, ob);
            var readerOb = new CompactBinaryReader<InputBuffer>(new InputBuffer(outputOb.Data));

            //create and set the Bonded object
            ro.InnerObject = new Bonded<Void, CompactBinaryReader<InputBuffer>>(readerOb);

            //serialize the RemoteObject
            var output = new OutputBuffer();
            var writer = new CompactBinaryWriter<OutputBuffer>(output);

            Serialize.To(writer, ro);

            //this is on the other side of the server
            var input = new InputBuffer(output.Data);
            var reader = new CompactBinaryReader<InputBuffer>(input);

            var dst = Deserialize<RemoteObject>.From(reader);

            // you can either convert and deserialize or deserialize directly if you specify T

            //var temp = dst.InnerObject.Convert<OtherObject>();
            //var oobb = temp.Deserialize();

            // oobb has all the data that is expected, "Hello" and 1 you can verify this with the debugger or buy outputting
            var oobb = dst.InnerObject.Deserialize<OtherObject>();
```

and the second option involves all your Objects inheriting from Bond.Void or from BaseObject (empty struct). This in c# will buy you the convenience of not having to serialize individual objects before constructing the bonded as demonstrated in the example of Circle and Rectangle and in the way I thought it was supposed to work. Both work. I'll get back to you if I find anything else interested.

**Comment by NYProgrammer** [comment]
Thanks...I got it working by deriving my objects from empty BaseObject..

On a related note, I am not able to use SimpleJsonReader/writer in this situation. It seems the Deserialize is failing...
Do bonded<> work for JSON?

**Comment by lalo** [comment]
Good. 

JSON and Xml don't support bonded<T>. For more info check this issue https://github.com/Microsoft/bond/issues/96

**Comment by chwarr** [comment]
I believe this can been resolve, so closing out this issue. Feel free to re-open if needed.
