### ISSUE TITLE
Does C++ Bond-over-gRPC work in a Win32 configuration?

### ISSUE THREAD

**Issue by NYProgrammer** [Microsoft/bond#802]
SOmeone told me this - 
"...that Bond & gRPC are built in Win32 configuration. It can’t be built in x64 configuration. ?"

**Comment by chwarr** [comment]
Both 32- and 64-bit platforms work for both Bond and gRPC. If you encounter an issue around this, that's a bug, so please report it, and we'll figure out how to fix that.

The Windows test matrix can be found in the [appveyor.yml file](https://github.com/Microsoft/bond/blob/4f4b9b1d900ad523839806224b3f3c6b1ba0f5cf/appveyor.yml#L40-L96). There are 32- and 64-bit configurations there. There isn't an explicit 32-bit test of Bond-over-gRPC, so there's the possibility that something in that configuration doesn't work.

The Bond C# assemblies are built as AnyCPU. They work on both 32- and 64-bit platforms. The gRPC assemblies require a platform-specific DLL, and both 32- and 64-bit versions are included. (Here, I'm talking specifically about the [Grpc.Core package](https://www.nuget.org/packages/Grpc.Core/).)

**Comment by NYProgrammer** [comment]
I am talking about gRPC and bond for C++ not C#

**Comment by chwarr** [comment]
All of this applies to both C++ and C#. I've updated my original comment to clarify.

Also, I just successfully ran a C++ x32 Bond-over-gRPC test pass of the master branch (4f4b9b1d900ad523839806224b3f3c6b) on my local machine. (Boost 1.65, MSVC 14 x64 to x86 cross-compiler)

**Comment by NYProgrammer** [comment]
I am able to build 32 bit C++ bond over gRPC; 
I need to know what needs to be done for 64-bit. 
Do I need to change any configuration in CMake or just change configuration in Visual studio or anything else?

**Comment by chwarr** [comment]
Looking at the CMake documentation for the [`CMAKE_GENERATOR_PLATFORM`](https://cmake.org/cmake/help/v3.11/variable/CMAKE_GENERATOR_PLATFORM.html#variable:CMAKE_GENERATOR_PLATFORM), I *believe* you need to generate different build trees (i.e., different .sln files in independent directories) for each target platform.

From [the CMake 3.11 documentation for the Visual C++ 14 2015 generator](https://cmake.org/cmake/help/v3.11/generator/Visual%20Studio%2014%202015.html), there are two different ways to specify the target platform when generating a build tree.

> The [`CMAKE_GENERATOR_PLATFORM`](https://cmake.org/cmake/help/v3.11/variable/CMAKE_GENERATOR_PLATFORM.html#variable:CMAKE_GENERATOR_PLATFORM) variable may be set to specify a target platform name (architecture).
> 
> For compatibility with CMake versions prior to 3.1, one may specify a target platform name optionally at the end of this generator name:
> 
> * `Visual Studio 14 2015 Win64`
>     * Specify target platform x64.
> * `Visual Studio 14 2015 ARM`
>     * Specify target platform ARM.
> 

In [our CI build script](https://github.com/Microsoft/bond/blob/4f4b9b1d900ad523839806224b3f3c6b1ba0f5cf/appveyor.yml#L173-L175), we append the target platform to the CMake generator for the 64-bit builds:

        if ($env:BOND_ARCH -eq 64) {
            $cmakeGenerator += " Win64"
        }

Possibly worth looking at to help with dependencies is [Vcpkg](https://github.com/Microsoft/vcpkg), the VC++ Packaging Tool that "helps you get C and C++ libraries on Windows." Both Bond and gRPC are in its collection of ports. (I haven't tried using Bond and gRPC from Vcpkg at the same time.)

**Comment by chwarr** [comment]
I believe this has been answered, so I'm going to close this issue. Please re-open if needed.
