### ISSUE TITLE
Are there plans to upgrade grpc?

### ISSUE THREAD

**Issue by grisharav** [Microsoft/bond#810]
We are using bond with GRPC, and we have encountered an issue described in https://github.com/grpc/grpc/issues/11718. It's claimed to have been resolved in version 1.8.1 of GRPC.
I see the latest available release is 1.10.0, any plans for bond upgrade?

**Comment by ara-ayvazyan** [comment]
We don't have a concrete schedule for that work right now. If you need it urgently and are willing to try making the upgrade yourself, we would be very happy to review and merge a pull request.

**Comment by grisharav** [comment]
I have created a pull request #811 for this, hope I made it OK, not experienced with git yet...

**Comment by grisharav** [comment]
Thanks @chwarr, any plans to release a formal bond version anytime soon?

**Comment by chwarr** [comment]
We've got a few more changes planned before the 8.x release. No solid ETA.
