### ISSUE TITLE
Generator does not suppress or propagate doc comments

### ISSUE THREAD

**Issue by kylemc** [Microsoft/bond#82]
When I use IDL codegen in a project that's building XML docs, I get the following error.

> My_types.cs(201,16,201,26): error CS1591: Warning as Error: Missing XML comment for publicly visible type or member 'My()'

I'd prefer one of the following options

1) Comments in the IDL get propagated to the generated output
2) "#pragma warning disable 1591" gets added to the generated files

I'd prefer not to resort to the "project-global" suppression. If there's another option I don't know about, I'm happy to use that instead.

**Comment by chwarr** [comment]
I have a [working fix](https://github.com/Microsoft/bond/tree/chwarr/suppress-cs1591), but we're having some problems with the CI builds due to Haskell packages that are blocking me from pushing. @sapek is helping to fix the CI breaks.

**Comment by chwarr** [comment]
Opened #170 for the overall feature request.
