### ISSUE TITLE
[c++] Consider adding features to our Vcpkg port

### ISSUE THREAD

**Issue by chwarr** [microsoft/bond#820]
Vcpkg now [has support for optional features](https://blogs.msdn.microsoft.com/vcblog/2018/02/06/vcpkg-introducing-installation-options-with-feature-packages/) that affect how a port is built. This could be used to, say, enable Bond-over-gRPC in the Vcpkg port when requested or other similar things.

**Comment by eitanhs** [comment]
Just saw this issue after opening: https://github.com/microsoft/vcpkg/issues/10316
Any plans to add support for Bond-over-gRPC in Vcpkg?

**Comment by chwarr** [comment]
No one is currently working on this. If you want to start working on this, please feel free to go ahead. We'll be happy to review PRs in this area.

**Comment by chwarr** [comment]
Done in https://github.com/microsoft/vcpkg/commit/a41c53c14794bb32cb03269069cdd3b66fedda5f
