### ISSUE TITLE
Bond failed to build due to the Cmake error

### ISSUE THREAD

**Issue by shanshan0309** [Microsoft/bond#828]
I build Bond with VS2017 Update 5  on Windows Server 2016, but it failed with Cmake error. This issue is caused by master revision [b8e40d8](https://github.com/Microsoft/bond/commit/b8e40d8e7fad8cfd19368a1bac7b998e1a784051). Could you please help have a look about this issue? Thanks in advance!

**Repro steps:**
1. Open VS2017 x64 Native tools command tool
2. git clone --recursive https://github.com/Microsoft/bond.git D:\Bond\src
3. cd D:\Bond
4. mkdir build_x64 && pushd build_x64
5. cmake -G "Visual Studio 15 Win64 2017" -DCMAKE_SYSTEM_VERSION=10.0.15063.0 ..\src
6. msbuild bond.sln /p:Configuration=Release;Platform=x64 /t:Rebuild

**Failures:**
CustomBuild:
         CMake Error at stack_build.cmake:30 (message):
           build failed - scroll up for its output  
C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(171,5): error MSB6006: "cmd.exe" exited with code 1. [D:\Bond\build_x64\compiler\gbc.vcxproj]

**Comment by ara-ayvazyan** [comment]
Can you verify that you are using [Haskell Stack](https://docs.haskellstack.org/en/stable/README/#how-to-install) 1.5.1+?

**Comment by shanshan0309** [comment]
Thanks for looking into this issue,@ara-ayvazyan. When I tried using  Haskell Stack 1.5.1 but it still hit this issue.

**Comment by chwarr** [comment]
Can you include more of the error details? We'll need to know why stack is failing. If you cannot get these details from a CMake-based build, try the following:

```cmd
pushd d:\bond\src\compiler
stack build
REM or use whatever path is needed to execute stack, if it isn't on %PATH%
```

**Comment by shanshan0309** [comment]
Hi @chwarr, The whole log file please see attachment.
[log_x64_build.log](https://github.com/Microsoft/bond/files/1827614/log_x64_build.log)

**Comment by ara-ayvazyan** [comment]
> Invalid option `--executable-stripping'

Can you verify which version of stack you are actually running (`$ stack --version`)?

**Comment by chwarr** [comment]
It looks like `--strip-executable` was [added in stack 1.4](https://docs.haskellstack.org/en/stable/ChangeLog/#140). It may be useful to look in the CMakeCache.txt to see where CMake has found stack.exe to ensure its using the 1.5.1+ version you expect.

If CMake has found an old version, you may need to delete and recreate the *build tree* to fix this, as some paths can be very sticky.

**Comment by shanshan0309** [comment]
Hi @chwarr and @ara-ayvazyan, Thanks all for your help. Yeah, because Cmake has found an old version, I delete it and use the 1.5.1 version. After that, It works well.  
Thank you very much!

**Comment by chwarr** [comment]
Excellent. Glad we got this working.
