### ISSUE TITLE
[c++] Drop support for MSVC 2013

### ISSUE THREAD

**Issue by ara-ayvazyan** [microsoft/bond#851]
The MSVC 2013 is a 4+ years old compiler with many bugs that cause a lot of trouble supporting it.
The library and generated code can be simplified and cleaned up after we drop it.

**Comment by bhardwajs** [comment]
Now that #1007 is closed, can we take on deprecating MSVC 2013 support and pick up MSVC 2019?

**Comment by chwarr** [comment]
MSVC 2013 support has been removed. Thanks to @bhardwajs for contributing these changes!

Related commits:

* [C++ codegen removal](https://github.com/microsoft/bond/commit/f89c8241a526c111116a5a8b5893df47cc5f668d)
* [C++ library code removal](https://github.com/microsoft/bond/commit/dd9fbde9eec78a540aa18fc585eaf15f9cc141a8)
* [AppVeyor CI build removal](https://github.com/microsoft/bond/commit/90931a3e0f8c076a98b51fa9a3f58833ad173441)
