### ISSUE TITLE
Visual studio 2017 and Bond schema

### ISSUE THREAD

**Issue by mhatreabhay** [Microsoft/bond#867]
Flaky behavior, 

I added bond schema in my csproj., everything worked great, till I called git clean -xfd.
next rebuild. solution is able to build but all bond schema are now red. no intellisence. 

I tried unload and reloading csproj several times, no effect. 
then while playing around. I commented and saved csproj, then uncomment and saved. 
on reload, Visual Studio 2017 loaded Bond schema. 

Is this a bug ?

**Comment by chwarr** [comment]
I have a change I'm trying right now for a different issue that may fix this. If not, we'll need to get some help from the Visual Studio team, as I don't know the right MSBuild magic incantations to tell the IntelliSense engine about generated files that are created after project load.

Some follow up questions for you:

* Which version of the Bond NuGet package are you using?
* What kind of .csproj are you using, the classic or the simplified?
    * Classic has `<Project ... xmlns="http://...>` as the root element.
    * Simplified has `<Project Sdk="...">`

**Comment by mhatreabhay** [comment]
Bond NuGget and version

<package id="Bond.Core.CSharp" version="7.0.1" targetFramework="net452" />
  <package id="Bond.CSharp" version="7.0.1" targetFramework="net452" />
  <package id="Bond.Runtime.CSharp" version="7.0.1" targetFramework="net452" />

CSProj structure. 
classic 
<PropertyGroup>
        <BondOptions>--using="DateTime=System.DateTime"</BondOptions>
  </PropertyGroup>
<ItemGroup>
    <None Include="App.config" />
    <BondCodegen Include="Entities\schema.bond" />
    <Compile Include="$(IntermediateOutputPath)\schema_types.cs" Condition="False" />
    <None Include="packages.config" />
  </ItemGroup>

**Comment by chwarr** [comment]
I cannot reproduce the issue that you're having. For me, after a `git clean -dxn`, IntelliSense reports errors, but after the next build/rebuild they go away. It takes a moment after the build is finished.

**Comment by chwarr** [comment]
I talked with some people from the Visual Studio team. The venue for these sort of IntelliSense questions is https://github.com/dotnet/project-system/issues. Can you open an issue there with these details? They can help debug in more depth.
