### ISSUE TITLE
gbc cannot handle import with mixed/other slashes

### ISSUE THREAD

**Issue by chwarr** [Microsoft/bond#869]
On Linux, gbc cannot handle import statements with mixed or backslashes.

Given ./inc/one/two/a.bond:

```
namespace a;
struct foo { }
```

And ./b.bond:

```
import "one/two\a.bond"
namespace b;
struct bar {
    0: a.foo myFoo;
}
```

Run codegen as:

```
gbc c# -i ./inc/ b.bond
```

Expected results:

b_types.cs is created with references to `a.foo`

Actual results:

> gbc: user error (Can't find import file one\two/a.bond)

Import statements with mixed or backslashes are going to be common if the .bond files were originally authored on Windows. (gbc on Windows can handle mixed slashes just fine.)

**Comment by amrmahdi** [comment]
@chwarr when will the change be merged ? Also, are you going to create a release for this change ?

**Comment by chwarr** [comment]
Should be merged by end-of-day, Pacific time, on Wednesday, May 9, 2018.
We're planning the Bond 8.0 release some time around May 15, 2018.

**Comment by amrmahdi** [comment]
@chwarr what is the current target date for 8.0 release ?

**Comment by chwarr** [comment]
Tuesday, May 29, 2018
