### ISSUE TITLE
rapidjson_helper no return statement in function compiler error

### ISSUE THREAD

**Issue by JohnMorman** [Microsoft/bond#88]
Hey,

I get the following compiler error when compiling bond using the android NDK. 
bond/protocol/detail/rapidjson_helper.h:123:5:error: no return statement in function returning non-void

Looks like the issue is

120     size_t PutEnd(char* begin) 
121     { 
122         BOOST_ASSERT(begin == 0); 
123     } 

I'm not sure what the expected return value here is otherwise I'd submit a pull request, so can someone advise on this?

Thanks,
John

**Comment by sapek** [comment]
The `PutEnd` function is [not used for write-only streams](https://github.com/miloyip/rapidjson/blob/1c76070520cb9de5b73a92ef5bd20cec56414745/include/rapidjson/rapidjson.h#L507). Fixed with ef83b48.
