### ISSUE TITLE
cannot compile on macos

### ISSUE THREAD

**Issue by xqian** [Microsoft/bond#89]
my machine
==================
$ brew search  boost
boost (installed)	  boost-bcp		    boost-build		      boost-python (installed)
homebrew/science/boost-compute	       homebrew/versions/boost150	      Caskroom/cask/iboostup		     Caskroom/cask/turbo-boost-switcher
homebrew/versions/boost149	       homebrew/versions/boost155	      Caskroom/cask/pivotalbooster

$ cmake --version
cmake version 3.3.2

CMake suite maintained and supported by Kitware (kitware.com/cmake).
$ gcc --version
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 7.0.0 (clang-700.0.72)
Target: x86_64-apple-darwin14.5.0
Thread model: posix

error message
=============
In file included from /Users/xinqian/work/bond.github/cpp/inc/bond/core/protocol.h:15:
In file included from /Users/xinqian/work/bond.github/cpp/inc/bond/protocol/simple_binary.h:6:
/Users/xinqian/work/bond.github/cpp/inc/bond/protocol/encoding.h:30:5: error: unused typedef 'boost_static_assert_typedef_30'
      [-Werror,-Wunused-local-typedef]
    BOOST_STATIC_ASSERT(is_unsigned<T>::value);
    ^
/usr/local/include/boost/static_assert.hpp:170:16: note: expanded from macro 'BOOST_STATIC_ASSERT'
               BOOST_JOIN(boost_static_assert_typedef_, __LINE__) BOOST_STATIC_ASSERT_UNUSED_ATTRIBUTE
               ^
/usr/local/include/boost/config/suffix.hpp:544:28: note: expanded from macro 'BOOST_JOIN'
#define BOOST_JOIN( X, Y ) BOOST_DO_JOIN( X, Y )
                           ^
/usr/local/include/boost/config/suffix.hpp:545:31: note: expanded from macro 'BOOST_DO_JOIN'
#define BOOST_DO_JOIN( X, Y ) BOOST_DO_JOIN2(X,Y)
                              ^
/usr/local/include/boost/config/suffix.hpp:546:32: note: expanded from macro 'BOOST_DO_JOIN2'
#define BOOST_DO_JOIN2( X, Y ) X##Y
                               ^
<scratch space>:42:1: note: expanded from here
boost_static_assert_typedef_30
^
In file included from /Users/xinqian/work/bond.github/cpp/generated/bond/core/bond_types.cpp:13:
In file included from /Users/xinqian/work/bond.github/cpp/generated/bond/core/bond_reflection.h:16:
In file included from /Users/xinqian/work/bond.github/cpp/inc/bond/core/reflection.h:17:
In file included from /Users/xinqian/work/bond.github/cpp/inc/bond/core/bonded.h:7:
In file included from /Users/xinqian/work/bond.github/cpp/inc/bond/core/protocol.h:15:
In file included from /Users/xinqian/work/bond.github/cpp/inc/bond/protocol/simple_binary.h:6:
/Users/xinqian/work/bond.github/cpp/inc/bond/protocol/encoding.h:42:5: error: unused typedef 'boost_static_assert_typedef_42'

**Comment by sapek** [comment]
Looks like a new warning in Boost with compiler that comes with XCode 7. Could you check if adding `-Wno-unused-local-typedefs` [here](https://github.com/Microsoft/bond/blob/master/cmake/Config.cmake#L47-L48) is sufficient to work around this?

**Comment by sapek** [comment]
Fixed with 8d64c0e. Thanks for reporting.

**Comment by xqian** [comment]
Yes, it solved the issues.
