### ISSUE TITLE
[c#] About the c# example projects

### ISSUE THREAD

**Issue by zongbingwang** [Microsoft/bond#894]
Hi,

Recently, I need to use the microsoft bond in some c# projcet. I found some issues in the c# example project, fox example, the project (https://github.com/Microsoft/bond/blob/master/examples/cs/core/date_time/date_time.csproj) build failed firstly when I clone it, then I was confused with the path in csproj: BOND_BINARY_PATH, BOND_PATH. what are they? dind't find any document about it, do you have?
Then I take some time to download the nuget, refactor the whole project. It build successed finally.

so, I want to know why not use packages.config, instead of BOND_PATH, ETC? I can send a PR to fix if need.

Best Regards
Zongbing

**Comment by lalo** [comment]
It works as it should when built via the cs/cs.sln. I'm guessing you used the date_time.csproj directly.

You would not hit this problem when consuming directly from the Bond NuGet package.

A valid contribution would be to change the direct Reference to ProjectReference.

**Comment by chwarr** [comment]
This appears to have been answered. I'm going to close this issue. Please feel free to re-open if needed.
