### ISSUE TITLE
bond::is_writer does not work for derived types if they don't implement WriteStructBegin

### ISSUE THREAD

**Issue by biocomp** [Microsoft/bond#896]
Repro (I copied `check_method` and `is_writer` from bond's headers): https://godbolt.org/g/2F76N9

The way `is_writer` works - it tries to assign member function pointer from `T::WriteStructBegin`. When derived class relies on base's `WriteStructBegin`, this fails because it tries to assign base's pointer to member function to derived one.

I'm also guessing is_writer is not the only problem.

Copy of repro above:
```cpp
#include <type_traits>
#include <boost/type_traits.hpp>

struct Metadata
{};

struct Base
{
    void WriteStructBegin(const Metadata&, bool) {}
};

struct Derived : Base {};

template <typename T, T> struct 
check_method
    : std::true_type {};

template <typename T, typename Enable = void> struct
is_writer
    : std::false_type {};

template <typename T> struct
is_writer<T, typename boost::enable_if<check_method<void (T::*)(const Metadata&, bool), &T::WriteStructBegin>>::type>
     : std::true_type {};

int main()
{
    static_assert(is_writer<Base>::value, "!Base is writer");
    static_assert(is_writer<Derived>::value, "!Derived is writer"); // Fails
}
```

**Comment by chwarr** [comment]
Is there a deeper problem that this is causing? We need to know that to make sure that the fix addresses the core problem too.

Are you, for example, hitting the [static assert in the Serialization](https://github.com/Microsoft/bond/blob/92b2bfe9285adda5fe7d5bd38b30a287b8e82f27/cpp/inc/bond/core/transforms.h#L52) transform?

As a work around, try adding an explicit specialization of `is_writer` for your derived type:

```cpp
template <> struct
is_writer<Derived> : std::true_type {};
```

**Comment by biocomp** [comment]
Yes, this was exaclty the issue - I hit that assert. And yes, I did figure out this workaround, or I can just implement the method in derived class too. I just filed the issue that future users won't have to suffer :)

**Comment by chwarr** [comment]
Thanks for confirming it was the static assert. We'll make sure the fix actually fixes that case.
