### ISSUE TITLE
C# Bond, how to compile the schema definition to a value type (struct) instead of reference type (class)?

### ISSUE THREAD

**Issue by qzhou** [Microsoft/bond#91]
I like the bond framework very much.  The following schema definiton is codegen as reference type (class) in C# by default.  Is there a way to codegen it as a value type (struct) instead?

struct Record
{
    0: string Name;
    1: int32 Age
}

**Comment by sapek** [comment]
Bond compiler currently doesn't support generating C# structs, although you can [annotate your own structs with Bond attributes](https://github.com/Microsoft/bond/blob/a4201850a6c120fdcfdf6bb91221626b9974eba2/cs/test/core/Structs.cs#L78-L79) and Bond runtime does support de/serializing them.
