### ISSUE TITLE
Support for unsafe pointer based InputBuffer and OutputBuffer

### ISSUE THREAD

**Issue by redknightlois** [Microsoft/bond#92]
Currently Bond is missing a facility to deal with unmanaged memory as source and/or destination of the data. From what I see on the code implementing an InputPtrBuffer and OutputPtrBuffer would be straightforward. Is that the proper approach?

Would you accept such a contribution if possible? (I have a CoreCLR CLA already signed).

**Comment by sapek** [comment]
Yes, that would be a good contribution.
