### ISSUE TITLE
How to set CLSComplaint false to Bond file

### ISSUE THREAD

**Issue by yuchaozh** [Microsoft/bond#927]
Hi,

I created a bond file as following
```
import "Ifx.bond"

namespace GrepFromIfx

struct SayIt:Ifx.PartASchema
{
    10: required int32 Act;
    20: required int32 Scene;
    30: required int32 LineNumber;
    40: required wstring Character;
    50: required wstring Words;
};
```
ifx is a third-party nuget package.
When I trying to compile my project, it pops an error "`base type 'PartASchema' is not CLS-compliant`"
Does anyone know how to resolve the error?
Thanks in advance.

**Comment by yuchaozh** [comment]
I know how to disable the CLS-Complaint check in C# file. Since this is a bond file, I cannot use `[CLSCompliant(false)]` in the bond file. I am new to bond, so just want to ask question here to check if there is a way to stop CLSCompliant check for bond file. 

Thanks.

**Comment by ara-ayvazyan** [comment]
The generated types are marked as `partial`, so you can add that attribute in your code.

**Comment by lalo** [comment]
@yuchaozh to add on what @ara-ayvazyan mentions: you should not add the `[CLSCompliant(false)]` on the outputted generated file since that will be rewritten everytime the codegen occurs. So by extending the partial class would be the correct approach. If you need more assistance, I'm happy to help.

**Comment by cfogg6** [comment]
@lalo I'm running into this issue, could you clarify what you mean? How can you extend the generated class?
