### ISSUE TITLE
[C#] Project Bond - issues with Depedencies

### ISSUE THREAD

**Issue by dowang** [microsoft/bond#929]
Environment: Windows 10, Visual Studio 2017
After cloning opened cs.sln in VS 2017. I noticed "Dependencies" in Bond project has yellow warning for all its 3 sub-items: .NETFramework4.5, .NETStandard1.0/1.6. The Attributes and reflection project have the same Dependencies but all are good. Other projects having same issues are grpc/IO/JSON. Tried the Project Properties --> Application --> Target framework, it is grayed out.

**Comment by chwarr** [comment]
I don't know what would be causing those warnings. Are there more detailed logs you can shared, perhaps?

If you can figure out a change to the project/solution structure to make the warnings go away, please create a PR.

**Comment by chwarr** [comment]
Haven't heard anything about this in a while, so I'm going to close this issue. Please re-open it if you have more details or need more help.
