### ISSUE TITLE
Question: is there a reason bond::blob doesn't have a move assignment operator defined?

### ISSUE THREAD

**Issue by volka** [Microsoft/bond#934]
Hi! I was wondering why there is no move assignment operator defined for the bond::blob type. The implementation could be quite simple:

`
blob& operator=(blob&& that)
{
    swap(that);
    return *this;
}
`
Is this just an omission or is there a technical reason not to do this? (I would like to create a pull request with the implementation / a test if not)

**Comment by ara-ayvazyan** [comment]
It was missed I guess.
I think the implementation can be as simple as `blob& operator=(blob&& that) = default;`, except for VC12.

**Comment by lalo** [comment]
You can go ahead and submit a PR :+1:
