### ISSUE TITLE
Visual Studio removed newly added .bond files from BodeCodegen

### ISSUE THREAD

**Issue by ibdulx** [Microsoft/bond#936]
In the new csproj, VS automatically adds <BondCodegen Remove="myfile.bond" /> to the csproj if you add a new file with the .bond extension. It is therefore not included in the Bond code generation target by default.

I need to explicitly set the build action for the file to "Bond code generation" to resolve this and have it included as expected. Is there some msbuild magic that can be done to resolve this?

**Comment by lalo** [comment]
Is this VS2017?

**Comment by chwarr** [comment]
The Bond.CSharp package [as of version 8.0.0](https://github.com/Microsoft/bond/blob/master/CHANGELOG.md#800-2018-05-30) has the functionality you're looking for. You must be using one of the new SDK-style projects. Further, [this support is controlled by the MSBuild property `$(EnableDefaultItems)`](https://github.com/Microsoft/bond/blob/f78a4185c1396dcf85cb4d7c703749aea882c66b/cs/build/nuget/Common.props#L25-L39), which defaults to `true` for SDK-style projects, but can be overridden.

As an example, take a look at the [simple_json example](https://github.com/Microsoft/bond/blob/f78a4185c1396dcf85cb4d7c703749aea882c66b/examples/cs/core/simple_json/simple_json.csproj). It doesn't list any .bond files, but codegen is performed.

Hope this helps.

**Comment by ibdulx** [comment]
@lalo, yes I'm in VS2017 (15.7.4).

@chwarr the simple_json project seems to behave as expected when I add new `.bond` files to the project using "Add -> New Item..." in Visual Studio. It adds the following:
```xml
<ItemGroup>
    <None Remove="my.bond" />
</ItemGroup>
```
This is correct, as it removes the default `None` action so the `.bond` is caught by the `**\*.bond` pattern.

However if I create a new SDK-style project, add the `Bond.CSharp` package and do the same, I'm getting:
```xml
<ItemGroup>
    <BondCodegen Remove="my.bond" />
</ItemGroup>
```
Which essentially removes the "Bond code generation" association, reverting the item type to `None`.

**Comment by chwarr** [comment]
Hrm... My guess is that the something [isn't wired up correctly in the CPS settings](https://github.com/Microsoft/bond/tree/master/cs/build/nuget/cps) to tell Visual Studio how to add new .bond files.

I no longer work directly on Bond, so it's unlikely I'll have time to fix this. The CPS system isn't the best documented. I have some contacts inside of Microsoft if whoever looks into this can pin-point the problem.

**Comment by ibdulx** [comment]
I'll try and diff the NuGet vs. the simple_json msbuild assets to see if there's any differences there. Otherwise maybe the import order be an issue?

Not an expert in msbuild, but I'm thinking the import points might be different when props/targets are imported through NuGet contra defined directly in the `.csproj` as with simple_json.

Just a thought, I'll try and dive into it or move the issue to the CPS repo to see if I can clear this up.

**Comment by chwarr** [comment]
Just to confirm, you're adding the Bond.CSharp package to your project like this, yes?

```xml
<ItemGroup>
  <PackageReference Include="Bond.CSharp" Version="8.0.0" />
</ItemGroup>
```

**Comment by ibdulx** [comment]
Yeah, I'm testing with a newly created .NET Standard classlib, so the full csproj looks like this after adding a .bond file:
```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <BondCodegen Remove="test.bond" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Bond.CSharp" Version="8.0.0" />
  </ItemGroup>
</Project>
```

**Comment by ibdulx** [comment]
Right, so I think the issue boils down to the fact that `$(EnableDefaultItems)` does not seem to be defined when working with .props/.targets coming from NuGet, so these definitions are not processed:

```xml
<ItemGroup Condition=" '$(EnableDefaultItems)' == 'true' ">
  <BondCodegen Include="**/*.bond" />
</ItemGroup>
<PropertyGroup Condition=" '$(EnableDefaultItems)' == 'true' ">
  <DefaultItemExcludes>$(DefaultItemExcludes);**/*.bond</DefaultItemExcludes>
</PropertyGroup>
```

Removing those two conditions resolves the issue from a NuGet perspective (and removes .bond files from being toggled by this property).

I'm guessing the issue has something to do with the order in which .props/.targets are processed when imported through a NuGet package. That order would be different for the simple_json project where the Bond.CSharp.props/.targets are imported directly in the .csproj and therefore has `$(EnableDefaultItems)`  defined.

I found `$(EnableDefaultItems)` defined in `Microsoft.NET.Sdk.DefaultItems.targets` in the SDK:
```xml
<EnableDefaultItems Condition=" '$(EnableDefaultItems)' == '' ">true</EnableDefaultItems>
```

So the processor seems to get to our NuGet .props/.target before it hits that line. As to why this behavior is as such, I'm still unsure.

**Comment by ibdulx** [comment]
A better solution for now is to simply redefine `$(EnableDefaultItems)` using the same definition as in `Microsoft.NET.Sdk.DefaultItems.targets` while using a condition to protect non-SDK projects such as the old style csproj.

So the resulting `Common.props` can be changed to:

```xml
<!-- in Common.props -->
<PropertyGroup Condition=" '$(UsingMicrosoftNETSdk)' == 'true' ">
	<EnableDefaultItems Condition=" '$(EnableDefaultItems)' == '' ">true</EnableDefaultItems>
</PropertyGroup>

<ItemGroup Condition=" '$(EnableDefaultItems)' == 'true' ">
  <BondCodegen Include="**/*.bond" />
</ItemGroup>

<PropertyGroup Condition=" '$(EnableDefaultItems)' == 'true' ">
  <DefaultItemExcludes>$(DefaultItemExcludes);**/*.bond</DefaultItemExcludes>
</PropertyGroup>
```

**Comment by chwarr** [comment]
The import order hypothesis seems a good one to dig into.

[`msbuild  /preprocess`](https://docs.microsoft.com/en-us/dotnet/core/tools/csproj#how-to-see-the-whole-project-as-msbuild-sees-it) can be used to have MSBuild process all imports and show the order in which things are imported to see whether the difference is due to ordering or something else.

**Comment by chwarr** [comment]
This has been open for over 6 months without any further activity. I'm going to close this issue. Please feel free to re-open if needed.
