### ISSUE TITLE
How do I specify a constant in bond schema?

### ISSUE THREAD

**Issue by emmanueldlg83** [Microsoft/bond#943]
I see that for default value I would do something like this:
int32 someField = 123;

And I see documentation that I think is for constants parsed as json:

{
  "type": "constant",
  "value": 0
}

But I'm not sure how this is specified in a .bond file, any idea how?

Thanks

**Comment by lalo** [comment]
That documentation is regarding enum's and how they are represented in json. Bond IDL does not have a constant type, although you could simulate it with default value (or maybe enum) but you would still need a struct defined.

**Comment by chwarr** [comment]
This appears to have been answered. I'm going to close this issue. Please feel free to re-open if needed.
