### ISSUE TITLE
Json & Dependencies should be packed in a different package.

### ISSUE THREAD

**Issue by redknightlois** [Microsoft/bond#95]
Json requires to use add as a dependency Json.Net. While it is a very standard library, there are some projects that can have potential issues. 

For example, if you are using other Json version (previous or newer) which cannot be expected to work (they can but there is nothing that ensures it -- compatibility between major versions in semantic versioning is not guaranteed). In fact, issuing a different package with nuget versions introduced in Nuget 3.0 you can even release one for each compatible major json version. Other projects just doesnt need json at all, introduce such a dependency (and deal with it) when it is only used in Json Transcoders, Readers and Writers if you are not using them.

**Comment by Redbolts** [comment]
agree with this. Would be great if the Json.net wasn't a core dependency
