### ISSUE TITLE
How do I deserialzie a top level array?

### ISSUE THREAD

**Issue by andrejohansson** [Microsoft/bond#957]
Is it possible to deserialize a top level array?

I have the bond model:

```
struct Error
{
	[JsonName("errorCode")]
	0:  nullable<string> ErrorCode;

	[JsonName("errorMessage")]
	1:  nullable<string> ErrorMessage;

	[JsonName("additionalInformation")]
	2:  nullable<string> AdditionalInformation;
}
``` 

And I want to deserialize an input json string containing an array like this:

```csharp
public static T FromJson<T>(this string o)
{
    var reader = new SimpleJsonReader(new StringReader(o));
    var deserializer = new Deserializer<SimpleJsonReader>(typeof(T));
    return deserializer.Deserialize<T>(reader);
}

// Given
var json = "[{ \"errorCode\":\"BE18\",\"errorMessage\":\"In this case incorrect MSISDN\",\"additionalInformation\":null}]";

// When
var result = json.FromJson<Error[]>();

// Then
result.Length.Should().Be(1);
```

This gives me an exception since the serializer do not recognize the array:

```
System.ArgumentException: Type 'Rduce.PaymentProviders.Contracts.Swish.Error[]' does not have a default constructor
Parameter name: type
   at System.Linq.Expressions.Expression.New(Type type)
   at Bond.Expressions.DeserializerTransform`1.Struct(IParser parser, Expression var, Type schemaType, Boolean initialize) in D:\a\1\s\cs\src\core\expressions\DeserializerTransform.cs:line 201
```

Can I use a type alias or other thing?

**Comment by chwarr** [comment]
No, Bond requires a top-level struct to perform serialization/deserialization.

If only one value needs to be passed/returned, the type `bond.Box<T>` can be used to quickly wrap a value in a Bond struct. (There's nothing special about `bond.Box<T>`, except that it ships with Bond.)

So give this a shot:

```cs
// Given
var json = "{ \"value\": [{ \"errorCode\":\"BE18\",\"errorMessage\":\"In this case incorrect MSISDN\",\"additionalInformation\":null}]}";

// When
var result = json.FromJson<Bond.Box<Error[]>>();

// Then
result.value.Length.Should().Be(1);
```

A note: Bond is not designed to be a general purpose JSON library. The Simple JSON protocol that ships with Bond is opinionated about how it serializes to/from JSON. The JSON it produces/consumes is valid, but isn't always considered idiomatic. You cannot expect Bond to successfully deserialize the output of, say, Newtonsoft’s JSON.NET run on an arbitrary C# type.

**Comment by andrejohansson** [comment]
Ok, thank you for the reply! 

Since this is a response from an external system I do not have the possibility to modify the json in any way. I will go with Json.NET or other library for that then. Just wanted to confirm!
