### ISSUE TITLE
ID collision when distribuited extensions are added

### ISSUE THREAD

**Issue by DonutHolestien** [Microsoft/bond#958]
I'd like to let multiple parties extend the base protocol without advanced knowledge of each other.  Ideally we could make the id field larger and defined by some hash on the string name of the added fields.  Any support for distributed extension that I missed?

**Comment by sapek** [comment]
[Inheritance](https://microsoft.github.io/bond/manual/compiler.html#struct-definition) is one mechanism since base and derived struct have separate field id space.

**Comment by chwarr** [comment]
This appears to have been answered. I'm going to close this issue. Please feel free to re-open if needed.
