### ISSUE TITLE
C# OutputBuffer().Position = 0; Does not reset the buffer and you are unable to re-use it

### ISSUE THREAD

**Issue by markhotchkiss** [Microsoft/bond#960]
Hi All,

I am using BOND De/Serialization and I have created an OutputBuffer() for re-use.  After each use of the OutputBuffer, i set it's position back to 0 (as per the documentation).  However, on the next use of the OutputBuffer, it seems to serialize the previous record again.

Therefore, If I loop over the serialization 100's times, I get the same serialized record over and over again.

I have looked for other ways to re-use this but to no avail.  Is this an issue or can anyone help resolve this as the issue is causing us massive issues with GC as well as Serialization time.

If a code sample is required, please let me know!

**Comment by chwarr** [comment]
Yes, sample code would help here. I wasn't able to reproduce the problem that you're having. Here's my test code:

```cs
namespace Test
{
    using System.Diagnostics;
    using Bond.IO.Safe;
    using Bond.Protocols;
    using OutputBufferReuse;

    class Program
    {
        static void Main(string[] args)
        {
            var firstStruct = new SomeStruct
            {
                Name = "first",
            };

            var sharedOutputBuffer = new OutputBuffer();
            SerializeToOutputBuffer(firstStruct, sharedOutputBuffer);

            sharedOutputBuffer.Position = 0;

            var secondStruct = new SomeStruct
            {
                Name = "second",
            };

            SerializeToOutputBuffer(secondStruct, sharedOutputBuffer);
            var dedicatedOutputBuffer = new OutputBuffer();
            SerializeToOutputBuffer(secondStruct, dedicatedOutputBuffer);

            Debug.Assert(sharedOutputBuffer.Data.Count == dedicatedOutputBuffer.Data.Count);
            for (int i = 0; i < sharedOutputBuffer.Data.Count; ++i)
            {
                byte shared = sharedOutputBuffer.Data.Array[sharedOutputBuffer.Data.Offset + i];
                byte dedicated = dedicatedOutputBuffer.Data.Array[dedicatedOutputBuffer.Data.Offset + i];
                Debug.Assert(shared == dedicated, $"Difference at index {i}");
            }
        }

        static void SerializeToOutputBuffer(SomeStruct obj, OutputBuffer buf)
        {
            var writer = new CompactBinaryWriter<OutputBuffer>(buf);
            Bond.Serialize.To(writer, obj);
        }
    }
}
```

and the .bond file:

```
namespace OutputBufferReuse;

struct SomeStruct
{
    0: string Name;
}
```

**Comment by markhotchkiss** [comment]
Hi, Thanks for the reply!

So it would appear that what I was doing was the following:

`using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Bond;
using Bond.IO.Safe;
using Bond.Protocols;

namespace MySharedBuffer
{
    class Program
    {
        private static Serializer<CompactBinaryWriter<OutputBuffer>> _serializer;

        static void Main(string[] args)
        {
            var outputBuffer = new OutputBuffer(100);
            _serializer = new Serializer<CompactBinaryWriter<OutputBuffer>>(typeof(SomeStruct));

            var myItems = new List<SomeStruct>();

            myItems.Add(new SomeStruct()
            {
                Name = "First"
            });

            myItems.Add(new SomeStruct()
            {
                Name = "Second"
            });

            myItems.Add(new SomeStruct()
            {
                Name = "Third"
            });

            var serializedItems = SerializeToOutputBuffer(myItems, outputBuffer);

            foreach (var data in serializedItems)
            {
                var input = new InputBuffer(data.Data);
                var reader = new CompactBinaryReader<InputBuffer>(input);
                var record = Deserialize<SomeStruct>.From(reader);
                var record2 = record;
            }
        }

        static List<OutputBuffer> SerializeToOutputBuffer(List<SomeStruct> items, OutputBuffer buffer)
        {
            var listOfSerializedObjects = new List<OutputBuffer>();

            foreach (var item in items)
            {
                var writer = new CompactBinaryWriter<OutputBuffer>(buffer);

                _serializer.Serialize(item, writer);

                listOfSerializedObjects.Add(buffer);
            }

            return listOfSerializedObjects;
        }
    }
}`

And it all now makes sense...

As I was returning the List from the Serialize method, everytime I added the output from the serializer to the collection I was changing all references inside the collection to the last iteration... (I think)...

I have now added a line which takes the output and does output.ToArray() and then re-used the output buffer which seems to have done the trick!

Thanks for all your help, it is much appreciated.
