### ISSUE TITLE
[C#] --preview-constructor-parameters fails with empty structs

### ISSUE THREAD

**Issue by Alxandr** [microsoft/bond#963]
When using `--preview-constructor-parameters` and having an empty struct, 2 equal constructors are created.

**Comment by chwarr** [comment]
@BertusGreeff: is this something you can fix?

**Comment by BertusGreeff** [comment]
Yes, I will look at this, thanks for the report.

**Comment by bhardwajs** [comment]
@chwarr , @BertusGreeff: I think we can close this issue now now that #1031 is merged.
