### ISSUE TITLE
Microsoft view on choosing Bond vs protobuf vs Avro in Azure service fabric?

### ISSUE THREAD

**Issue by sfsjoshi** [Microsoft/bond#964]
I'm developing streaming based application leveraging Azure service fabric(.NET Core ASF Apps). I'm looking for high performance (de)serialization framework. Need guidance on Microsoft view on choosing between Bond vs Protobuf vs avro? For service to service communication (Stateless service to Actor Service) would it be right solution to leverage Bond. Thanks in advance on your inputs. Thanks .

**Comment by chwarr** [comment]
Microsoft has no specific recommendation on this configuration. You will need to weight the pros/cons of each approach. If you have a more specific question about Bond, feel free to ask them here.

For a discussion how Bond compares to similar frameworks see [Why Bond](https://microsoft.github.io/bond/why_bond.html).

**Comment by playgithub** [comment]
protobuf leaks memory in Windows GUI applications.
I reported the bug  on Jul 4, 2019.
[#6342](https://github.com/protocolbuffers/protobuf/issues/6342)
2 other guys has proved it, but it hasn't been fixed.

**Comment by SunnyWar** [comment]
@sfsjoshi 	About 6 months ago I did an analysis of Bond versus ProtoBuff. I recommend you do the same thing. It is easier and takes less time than you might think. Here is now I went about it.
1. Get vcpkg [https://github.com/microsoft/vcpkg](url)
2. Install with vcpkg bond, protobuf and avro
3. Write a schema file for each according to the primary data structures that you need. This will help you understand some of the bigger pros and cons.
4. Have each generate the code based on your schema.
4. Write a test application in the language of your choice that uses the generated code. Have it do whatever you care about most: size, performance, throughput rate and make sure you enable it to run for an extended period of time without leaking or crashing.

btw: the result of my analysis was that Bond and Protobuf are near equal in terms of the size of the resulting streamed data. Protobuf performance was slightly faster in most cases but slower in some others.  The writing of the schema was easiest in Bond and the generated code was better, IMHO. Therefore I picked Bond.
