### ISSUE TITLE
Complex object with KnownType attribute

### ISSUE THREAD

**Issue by shashi127** [Microsoft/bond#967]
I have my response structure with inherited concept

  ```
  [Schema]
    [KnownType(typeof(CustomResponse))]
    public class ICustomResponse
    {
        [Id(0)]
        public int Id { get; set; }
    }

    [Schema]
    public class CustomResponse : ICustomResponse
    {
        [Id(1)]
        public int Payload { get; set; }

        [Id(2)]
        public int Output { get; set; }
    }
```

**My Return type of the method is ICostomResponse**

```
public static Method<CustomRequest, ICustomResponse> Method =
                new Method<CustomRequest, ICustomResponse>(.....
```

**Implementation would be**
```
	private static ICustomResponse AddTwoNumbers(CustomRequest additionRequest)
	{            
		return new CustomResponse { Output = additionRequest.X + additionRequest.Y };
	}
	
```

I wants to retrieve actual data returned from the server. But while I receive the response at client end it contains only the ICustomResponse object. Can't convert ICustomRespnse to CustomResponse object. 

Is there any way to include [KnownType(typeof(CustomResponse))] while serializing and  deserializing the object? 

 I refereed sample project and made few changes- https://github.com/Horusiath/GrpcSample

**Comment by chwarr** [comment]
Bond does not use `KnownType` to implement polymorphism. The [polymorphic container](https://github.com/Microsoft/bond/tree/master/examples/cs/core/polymorphic_container) example shows the canonical idiom used in Bond to represent polymorphic types. Notice the use of a kind/type field in the base type and how it uses `bonded` to avoid slicing. If you are using Bond-over-gRPC, service method return types are already wrapped in `bonded` in the generated code: no manual addition is needed.

**Comment by chwarr** [comment]
I've not heard anything more about this, so I'm going to close this issue. Please reopen if needed.

**Comment by shashi127** [comment]
Thanks for the information. Since I am using c#, I just updated the serialization and deserialization. It is working as expected.
