### ISSUE TITLE
Compile failures with char8_t by MSVC under /std:c++latest mode

### ISSUE THREAD

**Issue by QuellaZhang** [Microsoft/bond#968]
We've stumbled across some build failures in Bond after implementing support for char8_t under /std:c++latest in the development version of Visual C++. Could you help look at this? Noted that this issue only found when compiles with unreleased vctoolset, that next release of MSVC will have this behavior.

**Repro steps:**

1. open VS2017 x64 Native tools command tool
2. git clone --recursive https://github.com/Microsoft/bond.git D:\Bond\src
3. set _CL_=/std:c++latest
4. cd D:\Bond\src\compiler
5. powershell.exe -NoProfile -ExecutionPolicy Bypass ..\..\tool\Setup.ps1
6. cd D:\Bond
7. mkdir build_x64 && pushd build_x64
8. cmake -G "Visual Studio 15 2017 Win64" -DCMAKE_SYSTEM_VERSION=10.0.17134.0 ..\src
9. msbuild bond.sln /p:Configuration=Release;Platform=x64 /t:Rebuild

**Failures:**
D:\Bond\src\thirdparty\grpc\third_party\boringssl\decrepit\ripemd\ripemd_test.cc(112): error **C2664**: 'int fprintf(FILE *const ,const char *const ,...)': cannot convert argument 2 from 'const char8_t [54]' to 'const char *const '
D:\Bond\src\thirdparty\grpc\third_party\boringssl\decrepit\ripemd\ripemd_test.cc(112): note: Types pointed to are unrelated; conversion requires reinterpret_cast, C-style cast or function-style cast

**Comment by chwarr** [comment]
The code in question is from the boringssl library, which is used by [gRPC](https://github.com/grpc/grpc), which Bond then uses for Bond-over-gRPC. The Bond build doesn't change this code.

The Bond project doesn't want to maintain patches against/forks of its third party libraries, so the way I see to resolve this is to fix the issues upstream.

Can you check if a newer version of gRPC consumes a newer version of boringssl that has already fixed this issue? If so, submit a PR to upgrade Bond to that newer version. If not, work to land a PR in boringssl that fixes the issue. Consume that in gRPC, then consume that in Bond.

**Comment by chwarr** [comment]
I've not heard anything more about this, so I'm going to close this issue. Please reopen if needed.

**Comment by QuellaZhang** [comment]
@chwarr Thank you for the information. Reported source issue to gRPC  https://github.com/grpc/grpc/issues/18755 and confirm now.
