### ISSUE TITLE
Question: Is there any way to know when a schema will have a fixed size and what size it will be?

### ISSUE THREAD

**Issue by redknightlois** [Microsoft/bond#97]
We have specific optimizations in place where a Fixed Size serializable schema will use a different type of tree. Schemas are (in this case, but not required to be) known at compile time. Is there any way to know if say a type {T} will is fixed size and a bounded size for it. 

This property is obviously false when dealing with Dictionaries, Strings, byte arrays, blobs, etc.

**Comment by sapek** [comment]
This can only be answered for a pair (schema, protocol). For example in Compact Binary almost all types are variable length, the only exceptions are `bool`, `float` and `double` and 8-bit integers. In Fast Binary all integer are fixed size. Furthermore most protocols omit optional fields that are set to default value.

There is no such API.

**Comment by redknightlois** [comment]
Can be done from outside of Bond internals? (If there is no such API). 
Is there any intention to provide such an API?
If possible how?

**Comment by sapek** [comment]
The rules for determining if a schema is const length for a given protocol would have to hardcoded per protocol. There is no way to determine it programmatically. One could in theory imagine some way to encoding this as protocol metadata but I think it would only make sense to add if Bond itself had some feature taking advantage of fixed size fields.

As for determining what the size of a fixed length schema is, the easiest way would be to serialize an instance (e.g. default instance) to a stream that just counts bytes. We have [a stream like that](https://github.com/Microsoft/bond/blob/master/cpp/inc/bond/stream/output_counter.h) implemented in C++ and use it to calculate lengths in the first pass of Compact Binary v2 serialization.

**Comment by redknightlois** [comment]
Yes, I was actually thinking into implementing our own SimpleFastProtocol disallowing variable size types altogether; where we can estimate that without much problems. The solution used in C++ would also work, we use counting streams ourselves too.
