### ISSUE TITLE
IdAttribute - could we make Value public?

### ISSUE THREAD

**Issue by sofusmortensen** [microsoft/bond#977]
Hey,

I am experimenting writing a simple linq message filtering mechanism on top of Bond. I'd like to use reflection to extract the field id from a MemberExpression, but unfortunately Value in IdAttribute is marked internal. 

I know there is a way around this using reflection - but it would be nicer to have Value (get) visibility changed to Public. Any thoughts on this?

**Comment by sapek** [comment]
Can you use `ISchemaField` to get the metadata?

**Comment by sofusmortensen** [comment]
@sapek Thanks. You're right - I can make it work with Bond.Reflection.GetSchemaFields. 

Feels a little heavy - but I should probably cache Id anyway to avoid unnecessary reflection.
