### ISSUE TITLE
Query: Performance Module or Benchmark

### ISSUE THREAD

**Issue by mayadav1** [microsoft/bond#978]
Do BOND library has  benchmark. Want to check performance of BOND library with different compilers.

**Comment by chwarr** [comment]
Do these help?

* [Issue #122: Slow serialization](https://github.com/microsoft/bond/issues/122)
* [Issue #63: Benchmarks](https://github.com/microsoft/bond/issues/63)

**Comment by chwarr** [comment]
I haven't heard anything more, so I'm going to close this issue. Please re-open if needed.
