### ISSUE TITLE
Error C4296: '<': expression is always false

### ISSUE THREAD

**Issue by brandonpon96** [microsoft/bond#981]
Building bond version 8.0.1 using vc14 version compiler produces the error shown below:

1>d:\dbs\cx\azma\bond.cpp.oncorext.8.0.1\lib\native\inc\bond\core\protocol.h(200): error C4296: '<': expression is always false

Please advise, thanks.

**Comment by chwarr** [comment]
I've coded a fix for this. It's ready [for review](https://github.com/microsoft/bond/pull/982).

You may run into more instances of these, depending on exactly how you exercise Bond's templates. If you do, feel free to submit [a PR with a similar fix](https://github.com/microsoft/bond/pull/982) directly.
