### ISSUE TITLE
InvalidDataException when deserializing an polymorphic bonded object

### ISSUE THREAD

**Issue by s-j** [microsoft/bond#983]
Hi,

we have a bond object including `vector<bonded<Annotation>> Annotations` among other fields. Where Annotation is a polymorphic struct, e.g.

```
struct Annotation
{
    5: AnnotationType Type;
}

enum AnnotationType
{
	General = 0,

	Author = 1,
}

struct AuthorAnnotation : Annotation
{
    102 : Person Author;
}
```

We further trying to do e.g. `annotation.Deserialize()` which ends up in the following exception:

```
System.IO.InvalidDataException
   at Bond.Protocols.Throw.InvalidBondDataType(BondDataType type)
   at Bond.Protocols.CompactBinaryReader`1.Skip(BondDataType type)
   at lambda_method(Closure , CompactBinaryReader`1 )
   at Bond.Deserializer`1.Deserialize[T](R reader)
   at Bond.Deserialize`1.From[R](R reader)
   at Bond.Bonded`2.Bond.IBonded<T>.Deserialize()
```

Any suggestions why this happens?

**Comment by chwarr** [comment]
Such an exception is typically caused by payload corruption. You'll want to check how you're creating the payload and how it's being transmitted.

There was a [bug that was fixed a long time ago](https://github.com/microsoft/bond/blob/master/CHANGELOG.md#700-2017-10-24) with CBv2 and bonded fields if the CompactBinaryWriter was re-used. Are you using CBv2?

**Comment by s-j** [comment]
It seems that our bond version is older than, maybe 3.0 (gbc 0.3.0.5 for sure), but we are using CBv1 to the best of my knowledge. We typically instantiate the outer object using C# constructor and annotations as e.g., new Bonded<AuthorAnnotation>(new AuthorAnnotation { ... }). We mainly use it as internal format, but may also persist some items for caching. Any how, I cannot see the error appear when we retrieve items from cache - mainly when we deserialize the bonded field, but also this part sometimes fail to Serialize the outer object with the same exception. 

```
            var buf = new OutputBuffer();
            Serialize.To(new CompactBinaryWriter<OutputBuffer>(buf), item);
            var newItem = Deserialize<FeedItemWithMetadata>.From(new CompactBinaryReader<InputBuffer>(new InputBuffer(buf.Data.Array)));
```

I hope it is ok to PM you with more internal details.

**Comment by chwarr** [comment]
Haven't heard anything about this in a while, so I'm going to close this issue. Please re-open it if you have more details or need more help.
