### ISSUE TITLE
Can Bond handle arbitrary protocols?

### ISSUE THREAD

**Issue by Phantal** [microsoft/bond#988]
I'm putting together a list of tools in this technology space (eg thrift, avro, protocol buffers, protlr, kaitai struct, etc).  One thing that's not terribly clear after reading through the "Why bond?" page and skimming documentation: can Bond be used to parse an arbitrary protocol?

With tools like Kaiti Struct and Protlr the data encoding is fully determined by the schema.  As an example, [this page](http://doc.kaitai.io/) links to some articles demonstrating the use of Kaiti Struct for analyzing binary file formats and/or protocols, though that tool is [currently] only capable of **reading** the formats it can be used to describe.

In contrast, tools such as Thrift, Avro, Protocol Buffers and Flatbuffers all serialize into a format that is only partially determined by the schema they use as input.

**Comment by chwarr** [comment]
Yes, other protocols/formats are supported if they fit into one of the three models that Bond supports. See the [documentation](https://microsoft.github.io/bond/manual/bond_cpp.html#protocols) for a brief discussion.

There's not much documentation about implementing a custom protocol. If you have additional question, feel free to open issues.

**Comment by Phantal** [comment]
Chris,

  I read through relevant parts of the documentation but I think the answer
to my question is "no", though feel free to correct me if I'm wrong.

  I'm looking for something that can be used to parse arbitrary binary
protocols / file formats.  An almost perfect example is Kaitai Struct.  It
can be used to parse png, jpeg, elf, zip, etc; unfortunately it cannot be
used to write data out in those formats.

-brian

**Comment by chwarr** [comment]
Ah. Agreed. Bond isn't the right tool for this sort of parsing.
