### ISSUE TITLE
Can we upgrade to newer snapshots of stackage?

### ISSUE THREAD

**Issue by kapilash** [microsoft/bond#992]
It would be great to customize the generated code and to be able to reuse the utilities provided in the [bond library](https://hackage.haskell.org/package/bond).

However it is not possible today to add dependency on this library with recent versions of ghc/stack/cabal.

**Comment by kapilash** [comment]
I just wanted to share the impact of moving to [stack snapshot lts-14.4](https://www.stackage.org/lts-14.4) just in case such a move is in line with the project goals.

The changes are needed for the following three dependencies:

-  [aeson-pretty](https://www.stackage.org/lts-14.4/package/aeson-pretty-0.8.7) is at version 0.8.7
- [derive](https://hackage.haskell.org/package/derive-2.6.5/docs/Data-DeriveTH.html) library is missing
-  [megaparsec ](https://www.stackage.org/lts-14.4/package/megaparsec-7.0.5) is at version 7.0.5.


**aeson-pretty** has a relatively minor change - the [config datatype](https://www.stackage.org/haddock/lts-14.4/aeson-pretty-0.8.7/Data-Aeson-Encode-Pretty.html#t:Config) takes more values in the constructor. Aeson-pretty is used only in [tests](https://github.com/microsoft/bond/blob/3132eb2b90d29d916e703e42ec6482b9b89a86ce/compiler/tests/Tests/Syntax/JSON.hs#L98).

**derive** is used in [tests](https://github.com/microsoft/bond/blob/3132eb2b90d29d916e703e42ec6482b9b89a86ce/compiler/tests/Tests/Syntax.hs#L33-L46) and [quickcheck-arbitrary-template](https://hackage.haskell.org/package/quickcheck-arbitrary-template) can be used instead.

**Megaparsec** megaparsec 7 introduced a few breaking change described at https://markkarpov.com/post/megaparsec-7.html and https://github.com/mrkkrp/megaparsec/blob/master/CHANGELOG.md

The impact of it is the following
1. replace `notChar` with `anySingleBut`
2. `getPosition` and `setPosition` are to be replaced by `getSourcePos` and `setSourcePos`.  (NB: The latter needs to be implemented via `updateParserState`)
3. some error handling related changes to work with `ParseErrorBundle` instead of `ParseError`

In addition, there are a few changes in `stack.yaml` and `package.yaml`. stack would generate `bond.cabal`

The tests pass with the above changes

**Comment by lalo** [comment]
Thanks for the detailed summary of the upgrade path. Are you planning on submitting a PR with the above changes?

**Comment by kapilash** [comment]
Yes, I can send out the PR shortly.

**Comment by kapilash** [comment]
Raised #993

**Comment by chwarr** [comment]
Merged #993 in commit 7038e5b3b7e501d6df459efb4c02796eea70047c. Thanks!
